### ISSUE TITLE
Error 409 on token transfer without detailed explanation

### ISSUE THREAD

**Issue by dstreppa** [raiden-network/raiden#1020]
## Problem Definition
I am starting to play with Raiden state channels (SC) on Ropsten. I created an ERC20 token (address `0xc90e57fe7da3b8f6c86e20f640dd9785c52906f7`) and I registered it for Raiden. 
Then I realized to open a SC (address `0xa0fa2da5b393d3d4bcfded48fd2acb6b0f05b465`) from partecipant1 and to deposit tokens from partecipant2 ([LINK](https://ropsten.etherscan.io/address/0xa0fa2da5b393d3d4bcfded48fd2acb6b0f05b465#readContract)). 
But when I try to transfer some tokens I always receives a `409` error. 

Below a Python example: partecipant1 `0x677cb6525c553b8f9085755ffcf00dca1bee8e92` tries to send 10 tokens (its current balance is 20) to partecipant2 `0x2e960068875b8b3c4814ccc35fe35963f6556240`:
<pre>
> RAIDEN_SOCKET = 'http://127.0.0.1:5001/'
> TEST_TOKEN_ADDR = '0xc90e57fe7da3b8f6c86e20f640dd9785c52906f7'
> PARTNER_ADDRESS = '0x2e960068875b8b3c4814ccc35fe35963f6556240'
> payload_transfer = {'amount': 10, 'identifier': 42}
> transfer_url = '%sapi/1/transfers/%s/%s' % (RAIDEN_SOCKET, TEST_TOKEN_ADDR, PARTNER_ADDRESS)
> print(transfer_url)
> print("Payload: %s" % str(payload_transfer))
> r_transfer = requests.post(transfer_url, json=payload_transfer)
> print("Status response -> %i" % r_transfer.status_code)
http://127.0.0.1:5001/api/1/transfers/0xc90e57fe7da3b8f6c86e20f640dd9785c52906f7/0x2e960068875b8b3c4814ccc35fe35963f6556240
Payload: {'amount': 10, 'identifier': 42}
Status response -> 409
</pre>

And the Raiden output
<pre>
INFO:raiden.api.rest	127.0.0.1 - - [2017-09-14 15:16:31] "POST /api/1/transfers/0xc90e57fe7da3b8f6c86e20f640dd9785c52906f7/0x2e960068875b8b3c4814ccc35fe35963f6556240 HTTP/1.1" 409 195 0.029467 
</pre>

## Solution

I think a more detailed response would be very helpful to understand the problem. 

### System Description
<pre>
pi@smartpi:~ $ raiden --keystore-path  ~/.ethereum/testnet/keystore
Welcome to Raiden, version 0.1.0+git.r3d26d3a!
...
pi@smartpi:~ $ geth attach ipc:/home/pi/.ethereum/testnet/geth.ipc console
...
instance: Geth/v1.6.7-stable-ab5646c5/linux-arm/go1.8.3
...
pi@smartpi:~ $ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.16+commit.d7661dd9.Linux.g++
</pre>

**Comment by hackaugusto** [comment]
Hi @dstreppa, thanks for the issue.

#### About the message

The response should have a body with a description of the error, e.g. `r_transfer.text`. Was the response's `text` attribute empty? 

#### About your test

The code [409](http://raiden-network.readthedocs.io/en/stable/rest_api.html#id36) is used when:

> [...] the address or the amount is invalid or if there is no path to the target

Since you have checked the channel balance, and at the moment this is [the only channel](https://ropsten.etherscan.io/address/0x359deccfe410b41ccdbe666381baed0851b023fe#readContract), so everything seems good, i.e. its not an invalid address nor lack of balance.

So I think the nodes can not reach each other, this can be checked by opening the python interface with `raiden --console` and running the following:

```python
tools._api.get_node_network_state('2e960068875b8b3c4814ccc35fe35963f6556240'.decode('hex'))
```

[Querying the channel on both nodes](http://raiden-network.readthedocs.io/en/stable/rest_api.html#querying-a-specific-channel), `/api/1/channels/0xa0fa2da5b393d3d4bcfded48fd2acb6b0f05b465` can give a bit more insight, to make sure both nodes caught up with the channel and the deposits.

**Comment by dstreppa** [comment]
Hi @hackaugusto thank you very much for the response. I forgot the `text`field ;), I only printed out with `print(r_transfer)` and the result was `Response 409`. 
Anyway the response is not in JSON format but says: `"Payment couldn't be completed (insufficient funds or no route to target)."`
I started Raiden with the console option on `Node1` and this is the result:
<pre>
In [3]: tools._api.get_node_network_state('2e960068875b8b3c4814ccc35fe35963f6556240'.decode('hex'))
Out[3]: 'unreachable'
</pre>

Below the other checks:
<pre>
# Node1  (who opened the channel with a token amount of 20):
pi@smartpi:~ $ curl -X GET http://127.0.0.1:5001/api/1/channels/0xa0fa2da5b393d3d4bcfded48fd2acb6b0f05b465
{
  "balance": 10, 
  "channel_address": "0xa0fa2da5b393d3d4bcfded48fd2acb6b0f05b465", 
  "partner_address": "0x2e960068875b8b3c4814ccc35fe35963f6556240", 
  "reveal_timeout": 10, 
  "settle_timeout": 600, 
  "state": "opened", 
  "token_address": "0xc90e57fe7da3b8f6c86e20f640dd9785c52906f7"
}
# Node2 (the partner who deposited 15 tokens)
shiva@shiva-VirtualBox:~$ curl -X GET http://127.0.0.1:5001/api/1/channels/0xa0fa2da5b393d3d4bcfded48fd2acb6b0f05b465
{
  "balance": 15, 
  "channel_address": "0xa0fa2da5b393d3d4bcfded48fd2acb6b0f05b465", 
  "partner_address": "0x677cb6525c553b8f9085755ffcf00dca1bee8e92", 
  "reveal_timeout": 10, 
  "settle_timeout": 600, 
  "state": "opened", 
  "token_address": "0xc90e57fe7da3b8f6c86e20f640dd9785c52906f7"
}
</pre>

So it seems the nodes are not able to communicate, as you wrote @hackaugusto. I noted the balance of `Node1` is 10, not 20 as [here](https://ropsten.etherscan.io/address/0xa0fa2da5b393d3d4bcfded48fd2acb6b0f05b465#readContract), like transfer is taken into account only on `Node1`.

About the routing problem, I did also the first test on  `Node2`:
<pre>
In [1]: tools._api.get_node_network_state('677cb6525c553b8f9085755ffcf00dca1bee8e92'.decode('hex'))
Out[1]: 'reachable'
</pre>

So `Node1` is reachable from `Node2`, but not the contrary.  `Node2` is a VirtualBox virtual machine, can this be the cause? 

Thank you for the help.

**Comment by dstreppa** [comment]
I am confused :confused: ...now it works, but I don't understand why. I did nothing (only the checks above), but this is the result now:
<pre>
In [3]: tools._api.get_node_network_state('2e960068875b8b3c4814ccc35fe35963f6556240'.decode('hex'))
Out[3]: 'unreachable'

# After 30 minutes

In [5]: tools._api.get_node_network_state('2e960068875b8b3c4814ccc35fe35963f6556240'.decode('hex'))
Out[5]: 'reachable'

In [6]: tools._api.get_node_network_state('2e960068875b8b3c4814ccc35fe35963f6556240'.decode('hex'))
Out[6]: 'reachable'
</pre>

And now I am able to transfer the tokens. But I don't understand the cause of the problem, I only sends the commands above and started the two Raiden with `--console` option. To be sure I restarted them without the option and the transfers still work.

**Comment by dstreppa** [comment]
Now after an ~hour, `Node2`is again unreachable (in # the approximate time), and there is the `409` routing error if I try a transfer:
<pre>
# 08:30
tools._api.get_node_network_state('2e960068875b8b3c4814ccc35fe35963f6556240'.decode('hex'))
'unreachable'

# 09:00
tools._api.get_node_network_state('2e960068875b8b3c4814ccc35fe35963f6556240'.decode('hex'))
'reachable'

# 10:20

tools._api.get_node_network_state('2e960068875b8b3c4814ccc35fe35963f6556240'.decode('hex'))
'unreachable'
</pre>

I am using geth in light mode in both the nodes, can this be a problem?

**Comment by LefterisJP** [comment]
Hmmm @dstreppa your report is rather interesting. That could point to a problem in our "healthcheck" procedure.

It should not be relevant to the underlying ethereum node, only to the communication between the two raiden nodes.

The `"Payment couldn't be completed (insufficient funds or no route to target)."` error combined with the `'unreachable'` state means that the node thinks that the partner is offline because it can't reach it via the healthcheck (a ping and ack system) and thus takes it out of the channel graph and refuses to send a connection to it.

It could be that there is a problem there. Let us look at it and perhaps we will ask you also for more information. Thank you for trying it out and for giving us all these info.

**Comment by hackaugusto** [comment]
Hi @dstreppa , 

We currently rely on a smart contract called [`EndpointRegistry`](https://github.com/raiden-network/raiden/blob/7e24e229e9bf58f9975334b937fde3579d1e21f0/raiden/smart_contracts/EndpointRegistry.sol) to map an ethereum address to an public ip/port pair.

If the ethereum node used by one of the raiden nodes is lagging behind it may query an older block and get and old ip/port entry, the partner raiden node is online but seems unreachable because the wrong ip/port pair is used. The state will stay at unreachable until the ethereum node synchronizes and the endpoint reports the up-to-date ip/port pair. Were you using two different ethereum nodes, could be the case the one of this nodes is lagging behind?

If you want to check what is IP/port reported by the ethereum node, right after the node is started you will see a log line printed to the screen like this:

```
INFO:raiden.network.upnpsock    registered port-mapping per upnp internal=192.168.15.164:40001 external=<public_ip>:40001
```

Then you can execute the following line from the console to query the end point registry:

```python
>>> discovery.get('2e960068875b8b3c4814ccc35fe35963f6556240'.decode('hex'))
```

If the values don't match that is the problem. There is a PR in the making that will check that the etheruem node is synced to fix this https://github.com/raiden-network/raiden/pull/882.

If each node sees the correct endpoint, the problem then is on the network. Could you provide a little bit more detail about your network? I believe no one in the raiden team actually tested with virtualbox machines, either the nat punching is not working (we use [UPnP IGD](https://github.com/miniupnp/miniupnp) and [stun](https://github.com/jtriley/pystun) for this), or many packets are dropped by the network..

**Comment by dstreppa** [comment]
Hi @hackaugusto, thank you for the info. 
Unfortunately at the startup I don't have this log:
<pre>
INFO:raiden.network.upnpsock    registered port-mapping per upnp internal=192.168.15.164:40001 external=public_ip:40001
</pre>
But the following (I report all the log):
<pre>
pi@smartpi:~ $ raiden --keystore-path  ~/.ethereum/testnet/keystore --console
Welcome to Raiden, version 0.1.0+git.r3d26d3a!
INFO:raiden.network.sockfactory	trying to find uPnP port mapper... 
ERROR:raiden.network.upnpsock	no upnp providers found 
INFO:raiden.network.sockfactory	uPnP not available, trying STUN for port mapping... 
The following accounts were found in your machine:

[  0] - 0x5279448c8671bd5452f575682137ee8e3a605338
[  1] - 0x8538861622cf5ef9b967ad4458bee20ffa047247
[  2] - 0x677cb6525c553b8f9085755ffcf00dca1bee8e92

Select one of them by index to continue: 2
Enter the password to unlock 677cb6525c553b8f9085755ffcf00dca1bee8e92: 
INFO:raiden.network.discovery	endpoint already registered node_address=677cb652 host=195.176.65.203 port=40001
INFO:filelock	Lock 1866986416 acquired on /home/pi/.raiden/677cb652/.lock 
The Raiden API RPC server is now running at http://127.0.0.1:5001/.

See the Raiden documentation for all available endpoints at
http://raiden-network.readthedocs.io/en/stable/rest_api.html

Entering Console
......

In [1]: discovery.get('2e960068875b8b3c4814ccc35fe35963f6556240'.decode('hex'))
Out[1]: ('195.176.186.125', 62316)
</pre>

In my opinion there are two points:

1.  I have the log  `ERROR:raiden.network.upnpsock	no upnp providers found `
2. `discovery.get()` gets a socket (`'195.176.186.125', 62316`), corresponding to the IP of node `2e960068875b8b3c4814ccc35fe35963f6556240`

It seems to me a network problem, now I requested to our IT team to open the port `40001` (UDP and TCP to be sure ;)) for the network of `Node1`(195.176.65.x) and `Node2`(195.176.186.125 is the machine where the VM `Node2` runs), I hope this will help.

**Comment by LefterisJP** [comment]
@dstreppa Can you also run raiden with debug logging? Add `--logging :DEBUG` as an argument. `STUN` can also be fine for nat punching, but we have its log in debug mode.

And from this log:

`INFO:raiden.network.discovery	endpoint already registered node_address=677cb652 host=195.176.65.203 port=40001`

It seems you are trying to register your endpoint `195.176.65.203:40001` and it's already registered in the smart contrac

**Comment by dstreppa** [comment]
Hi,
sorry for the very late response, but now, after the port opening, I realize to transfer data. I don't know if it can be due to the `40001` opening. However I decided not to use VMs.

For completeness, I report some debug output:

<pre>
# Node 1
DEBUG:raiden.tasks  new block timestamp=1507705090.25 number=1847750
DEBUG:raiden.network.protocol   ACK RECEIVED node=98ff7d11 receiver=869d59e7 echohash=4d61bb52
DEBUG:raiden.tasks  new block timestamp=1507705106.96 number=1847751
DEBUG:raiden.network.protocol   ACK RECEIVED node=98ff7d11 receiver=869d59e7 echohash=4404ff0b
DEBUG:raiden.tasks  new block timestamp=1507705118.55 number=1847752
DEBUG:raiden.tasks  new block timestamp=1507705120.34 number=1847753
DEBUG:raiden.network.protocol   ACK RECEIVED node=98ff7d11 receiver=869d59e7 echohash=3dbccf53
DEBUG:raiden.tasks  new block timestamp=1507705124.19 number=1847754

# Node 2
DEBUG:raiden.tasks  new block timestamp=1507705090.58 number=1847750
DEBUG:raiden.network.protocol   ACK RECEIVED node=869d59e7 receiver=98ff7d11 echohash=c9480c42
DEBUG:raiden.tasks  new block timestamp=1507705106.9 number=1847751
DEBUG:raiden.network.protocol   ACK RECEIVED node=869d59e7 receiver=98ff7d11 echohash=0b52f9bc
DEBUG:raiden.tasks  new block timestamp=1507705118.68 number=1847752
DEBUG:raiden.tasks  new block timestamp=1507705120.37 number=1847753
DEBUG:raiden.tasks  new block timestamp=1507705124.57 number=1847754
DEBUG:raiden.network.protocol   ACK RECEIVED node=869d59e7 receiver=98ff7d11 echohash=f6f27625
DEBUG:raiden.tasks  new block timestamp=1507705129.79 number=1847755
DEBUG:raiden.network.protocol   ACK RECEIVED node=869d59e7 receiver=98ff7d11 echohash=a3ad01cb
DEBUG:raiden.tasks  new block timestamp=1507705141.08 number=1847756
</pre>

**Comment by hackaugusto** [comment]
Closing in favor of #1133

Thanks for the input @dstreppa
