### ISSUE TITLE
Clarification around closing of channels

### ISSUE THREAD

**Issue by devinrsmith** [raiden-network/raiden#1115]
On the Raiden 101 page it says "This withdrawal may be triggered by anyone, including addresses other than the two participants." Is there any more context around this? It seems non-obvious why this would be the case, and I'm wondering what the motivations around it are. Thanks!

**Comment by LefterisJP** [comment]
This is the channel's payout stage. After one side closes the channel and the other side provides its own view of the channel by updating their side there is nothing else to be done and the channel can be settles and paid out once the settle timeout runs out.

Since we can't do things automatically once a timeout passes in ethereum someone needs to initiate a transaction for the payout to happen. That someone can be anyone. Could be the ethereum alarm clock for example.

**Comment by devinrsmith** [comment]
Ah, I was confusing closing a channel and withdrawing from a channel. Thanks for the quick response!
