### ISSUE TITLE
Take chain reorg into account

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1121]
## Problem Definition

At the moment our code is not aware of chain reorgs. The code that watches for events does not check the `removed` field of the [`getFilterChanges()`](https://github.com/ethereum/wiki/wiki/JSON-RPC#returns-42) call.

It can happen that there is a chain reorganization and an event is generated by a transaction. We read it and process it and is later invalidated by a chain reorg and for some edge case reason (e.g. new block is after timeout, another tx happened in the meantime and user is out of ETH) it is not reapplied in the canonical chain.

In that case our current code would break and be wrong.

## Solution

Make our code and especially our state transitions aware of chain reorganizations. In the case of a reorg a previously valid event will be invalidated by issuing it again with the `removed` field being true as can be seen [here](https://ethereum.stackexchange.com/questions/7905/ethereum-event-log-removed-field). 

We should be watching for that and if it happens be able to invalidate recently fired events.

## Tasklist

Example:

- [ ] Watch for the `removed` attribute in all pending events
- [ ] Adjust our state transition logic to take invalidation of previous events into account
- [ ] Add a changelog entry.

**Comment by hackaugusto** [comment]
> Make our code and especially our state transitions aware of chain reorganizations

Note: The idea is to not add logic for reorgs inside every task, but to have a top-level state-transition function, e.g.:

```python
class BlockchainConfirmation(State):
  def __init__(self, child_state):
     self.child_state = child_state
     self.ordered_events = []

def state_transition(new_state, state_change):
  # queue blockchain events until they reach the # of confirmations block required
  if isinstance(state_change, BlockChainEvent):
    self.ordered_events.append(state_change) 
  if isinstance(state_change, Block):
    i = 0
    for blockchain_event in self.ordered_events:
      if blockchain_event.blocknumber + CONFIRMATIONS_BLOCKS <= state_change.block_number:
         dispatch(self.child_state, blockchain_event)
         i += 1
    blockchain_event.blocknumber = blockchain_event.blocknumber[i:]
  ...
```

**Comment by hackaugusto** [comment]
Related: https://github.com/raiden-network/raiden/pull/2498 https://github.com/raiden-network/raiden/issues/2449

**Comment by hackaugusto** [comment]
Adding a bit of detail to the issue:

The events channel open and deposit must not be applied unless they are confirmed. This is important for the receiving end of a channel, otherwise reorgs could revert the corresponding transactions and would be a safety issue.

The withdraw and coop settle have the side-effects applied off-chain first, and the clients must not allow the tokens to be used anymore, so these two don't really have safety issues, it's a problem only for the APIs (the API will block for more time because it is waiting for the confirmation block).

The operations update, settle, and unlock can only be applied on a closed channel, therefore they also don't have a safety impact. Here, however, the unlock has to wait for the settle to be confirmed, and the update for the close, because one transaction is a precondition for the next, and a reorg could reorder them.

The trickiest one is close, as long as the honest node does not send or accept new balance proofs for the channel *himself has closed*, he will be safe. If a *dishonest* node tries to play this he would at best receive some new payments before the channel is closed, and at worst we would lose tokens by mediating a transfer he cannot claim on-chain. This is the case because the closing party cannot update the balance proof used to close.

The two operations that I can see a benefit to apply before confirmation is the secret registration and the URL update for the service registry. The former is a way of revealing the secret, and the latter is just using the blockchain as a mapping.

For the REST API, if the semantics is to not complete the operation, then we should just dispatch the state change and return 202 to the user, if we use 200/201/4xx then the operation should be complete, to offer a consistent view of the data, this means the API should wait for the confirmation.

**Comment by hackaugusto** [comment]
closing this since we only work on top of confirmed blocks
