### ISSUE TITLE
Can it be used for private blockchain of poa (Proof of Authority）?

### ISSUE THREAD

**Issue by VinceXie** [raiden-network/raiden#1395]
If it can , how to use it?

**Comment by LefterisJP** [comment]
Hello @VinceXie we don't have a guide for Proof of Authority setup but in theory you can use it with a PoA chain just like you would with a PoW chain. Perhaps the better question would be for you to try and tell us where you get stuck.

**Comment by hackaugusto** [comment]
Closing this issue since we didn't get a response.

Yes, Raiden can be used with a PoA and in fact we use it for our testing infrastructure with geth. The Raiden binary must be executed pointing to the given PoA network making sure that the flags `--registry-contract-address`, `--secret-registry-contract-address'`, and `--discovery-contract-address` point to the addresses of the smart contracts on the PoA chain, to use the correct `--network-id` number and set `--no-sync-check` (these flags are for the current master and not the last release)
