### ISSUE TITLE
Replace slogging with structlog

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1416]
## Problem Definition

Slogging is a frankestein remnant of pyethereum. We should replace it with a proper structured logging implementation like [structlog](http://www.structlog.org/en/stable/index.html)

**Comment by andrevmatos** [comment]
[From Why of structlog](http://www.structlog.org/en/stable/why.html), we may also look into making more extensive use of the structured logging construct (_kwarg syntax for logging_), which should mean initially at least suggesting using more this syntax instead of the default, format-based syntax, and after, looking at making the replacement over current codebase, to make best usage of structlog features. String formatting can still be used, but shouldn't be a way to embed relevant information, as this is kwargs job.

**Comment by heikoheiko** [comment]
fyi, we used structlog in the past in pyethereum and stopped using it to minimize the number of external dependencies to improve security. this might not be important for raiden though. 

but question: while "Slogging is a frankestein remnant" what are the specific problems you are facing and trying to solve? will this speed up reaching the milestones?

**Comment by LefterisJP** [comment]
> what are the specific problems you are facing and trying to solve?

- Get rid of the pyethereum dependency and use the new py-evm code.
- Simplify the code in general and more specifically the [special test fixtures](https://github.com/raiden-network/raiden/blob/master/raiden/tests/conftest.py#L83) that exist to make pytest logging to work with slogging.

**Comment by palango** [comment]
Fixed by #1417 and #1434
