### ISSUE TITLE
Allow to hold off SecretRequest

### ISSUE THREAD

**Issue by pdobacz** [raiden-network/raiden#142]
Following the discussion in #112.

Receiver of a locked (mediated) transfer could be able to hold off asking for the secret, for a particular transfer id.

This is motivated by situations, where the receiver and sender need to agree on some details of the transfer before making it final. At the same time receiver and sender don't want to wait with initialization of the transfer.

This could take the form of a method like `raiden_api.allow_sending_secret_request(id)` and (possibly) providing an option to always allow immediately.

**Comment by hackaugusto** [comment]
With the [event handler class](https://github.com/raiden-network/raiden/pull/2405) this is now possible. one would have to add a custom handler which would delay the `SecretRequest` message.

However we are not adding this feature out-of-the-box, and the logic to decide when such a message should be hold is not available. Additionally, usage of the mentioned handler should be done with care, because it may break assumptions of the protocol and have unsafe results.
