### ISSUE TITLE
SyntaxError error when I Sart raiden

### ISSUE THREAD

**Issue by Sirinemra** [raiden-network/raiden#1455]
This morning, I installed raiden from the source
$ git clone https://github.com/raiden-network/raiden.git
$ pip3 install --upgrade -r requirements-dev.txt
$ python3 setup.py develop

And when I ran raiden, I have this error:
Traceback (most recent call last):
  File "/usr/local/bin/raiden", line 11, in <module>
    load_entry_point('raiden', 'console_scripts', 'raiden')()
  File "/home/ubuntu/software/raiden/raiden/__main__.py", line 7, in main
    from raiden.ui.cli import run
  File "/home/ubuntu/software/raiden/raiden/ui/cli.py", line 616
    raise RuntimeError(f'Unknown transport type "{transport}" given')
                                                                   ^
SyntaxError: invalid syntax

Could you tell me what's wrong with my installation.
Thank you.

**Comment by mat7ias** [comment]
I'm not part of the raiden team but I came across this and I think I can help. The main problem I can see is that you missed a number of steps in your installation, I didn't have a problem testing it out when I followed the guidelines from the detailed docs they provide https://raiden-network.readthedocs.io/en/stable/
You also downloaded their latest master branch instead of the latest stable release. Lefteris mentioned in the gitter that they're in the middle of changing the deep structure in the master branch so that they won't expect it to run for now. I don't think you should run into any issues if you follow the steps in their installation guidelines and run the stable release. If you still have problems then they regularly answer those type of support questions in the raiden gitter channel (https://gitter.im/raiden-network/raiden) so you might find the answer in there already.

**Comment by LefterisJP** [comment]
You also need python version 3.6

**Comment by LefterisJP** [comment]
Closing this issue as there has been no reply in 6 days. Please reopen if you have any further problems.
