### ISSUE TITLE
Where to limit the balance proof's `transferred_amount` - overflow at settlement

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1529]
A very big `transferred_amount` can cause an overflow when calculating the settlement amounts. this will cause the participant's tokens to be sent to the other participant.

The issue is where to set a limit to `transferred_amount`, which is going to be relative to the `deposit`.
My proposal is to only set this limit in the Raiden and not in the smart contract.

Reasons:
- `deposit` value can be very different per token
- Raiden client has access to all variables needed to set this limit dynamically
- Raiden client is the official client to be used. Using anything else of course poses a risk

Discussions:
https://github.com/raiden-network/raiden-contracts/pull/114#discussion_r194008259

**Comment by loredanacirstea** [comment]
@hackaugusto,  @err508, we can continue the offline discussions here with some opinion summaries.

**Comment by err508** [comment]
I can not see how this will solve the problems. Attackers can and will send transactions to the contracts even without having the Raiden-Client installed. I would like to suggest to really focus on secure standalone contracts.

**Comment by loredanacirstea** [comment]
@err508 , please propose an implementation then.

**Comment by err508** [comment]
@loredanacirstea 
see here for some suggestions:
https://github.com/raiden-network/raiden-contracts/issues/117

**Comment by hackaugusto** [comment]
> I can not see how this will solve the problems. Attackers can and will send transactions to the contracts even without having the Raiden-Client installed. I would like to suggest to really focus on secure standalone contracts.

This definitely doesn't exclude proper overflow handling in the smart contracts, but it's important for us to define an upper bound for the transferred amount.

**Comment by LefterisJP** [comment]
As @err508 said we must have this in the smart contracts or else someone can just brick a channel by manually sending a malicious transaction.

But yes indeed for usability reasons we should also have checks in raiden and have a limit so that for proper use of Raiden overflow via transferred amount never happens.

**Comment by loredanacirstea** [comment]
This should be fixed in the smart contract with https://github.com/raiden-network/raiden-contracts/pull/123

**Comment by hackaugusto** [comment]
These are the client rules that need to be enforced to avoid overflows:

1. `T1` and `T2` overflow checks must be enforced by the Raiden clients, and we assume they are properly validated, this implies that `0 <= T1 - T2 <= D1` and `0 <= T2 - T1 <= D2`.
1. The withdraw values W1 and W2 are agreed and validated by the Raiden client, where the constraint `W1 <= A1r` and `W2 <= A2r` must be enforced
1. The lock values `A1l` and `A2l` are agreed and validated by the Raiden client, where the constraint `A1l <= A1a` and `A2l <= A1a` must be enforced.

To enforce rule 1 we do:

- Apply the new deposit only after a number `X` of confirmations blocks [1](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L1376-L1377) [2](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L1308-L1313)
- We then define the available balance as [`A2a = D2 + T1 - T2`](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L565-L569), where `T1` and `T2` are updated only by valid balance proofs, meaning `A2a` will vary from `0` to `D2`
- We then define the distributable balance as [`A2d = A2a - L2`](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L587-L588)

For sending transfers, we validate the amount is lower or equal to `distributable`.
- [For direct transfers](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L781)
- [For mediated and refund transfers](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L836-L837)

 This is required for two reasons:
1. Sending an invalid balance proof, which tries to use more then the available distributable amount, may trigger the partner node to close the channel, making it short lived.
2. Depending on the transfer type, this may be used to steal tokens. E.g. a direct transfer with a larger transferred amount will ignore the locks.

For receiving transfers, we validate the amount is lower or equal to `distributable`.

- [For direct transfers the transferred amount must have changed by at most distributable](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L270-L283), the [locksroot must not have changed](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L218-L229), nor the [locked amount](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L244-L255)
- [For mediated and refund the lock amount must be <= the distributable amount](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L393-L405), the [locked amount must have increased by the lock.amount](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L368-L378), [the locksroot must include the new lock](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L344-L354) the [transferred amount must not have changed](https://github.com/raiden-network/raiden/blob/bb53706822a628750118e6215c7ea6c5a12b22e3/raiden/transfer/channel.py#L356-L366)

This is required because:
- Accepting a transfer with an invalid value, even one that benefits the receiver, may result in overflows on chain. Therefor invalid messages must be ignored
- It's a way to identify if a node is trying to play the protocol, which is interpreted as a malicious node

**Comment by LefterisJP** [comment]
@hackaugusto. Thank you for the detailed analysis and the links to the client code where the proper checks are happening. Along with the changes done in the smart contracts in https://github.com/raiden-network/raiden-contracts/pull/123 shouldn't we consider this issue done? Or have I misunderstood something in the scope?

cc @loredanacirstea

**Comment by loredanacirstea** [comment]
The above analysis has outdated parts after https://github.com/raiden-network/raiden-contracts/pull/131.
However, overflows should be handled properly in the smart contracts after the aforementioned PRs.

Overflow limit `transferred_amount + locked_amount < UINT256_MAX` has also been added in the Raiden client in https://github.com/raiden-network/raiden/pull/1567

We can close this issue from my part.

**Comment by LefterisJP** [comment]
Since nobody else disagrees with this I am closing the issue as having been handled by:

https://github.com/raiden-network/raiden-contracts/pull/123
https://github.com/raiden-network/raiden-contracts/pull/131
https://github.com/raiden-network/raiden/pull/1567
