### ISSUE TITLE
Make channel deposit idempotent

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden#1539]
New smart contract proxies receive a `total_deposit` value instead of the actual amount of tokens to be transferred at that point in time.
This needs to also be reflected in the rest of the code:

- `new_balance` related states and event handlers should be adapted
- api calls that deal with deposits should be renamed to `set_total_deposit` or similar and should also be made idempotent
- Also edit NettingChannelLibrary/Contract.sol to make its deposit function idempotent to mimic the `TokenNetwork.sol` functionality and make it testable without having to switch to the new contracts.

**Comment by hackaugusto** [comment]
Parent issue: #1383

**Comment by LefterisJP** [comment]
Edited description to add the steps required for this issue. Specifically to mention the API changes needed and the fact that API should also be idempotent in regards to depositing and that changes should also be made to old `nettingchannel` contract so that we can test fast, without changing the contracts to the new `tokennetwork.sol`
