### ISSUE TITLE
Is the RTT (raiden testnet token) not up anymore?

### ISSUE THREAD

**Issue by vnblr** [raiden-network/raiden#1586]
## Problem Definition
I was trying to play with the setup by syncing with testnet as given in the docs. I am not sure if the issue is with the webUI code or with the latest nodes on the testnet but when I click on the "Tokens" link in the UI, I just do not see any networks. Whereas all docs/videos I have seen (like https://www.youtube.com/watch?v=DDQP9EZ6qJM) shows a token network running called "Raiden Testnet token" or some such thing. 

Note that when I hit the endpoint api/1/tokens, I do see a list of tokens including the prominent ones like 0x0f114a1e9db192502e7856309cc899952b3db1ed  So mostly the end to end setup (like the Raiden API hitting rpc of geth on the local node) is running fine. testnet is fully synced up. 

### System Description
I used a c5d.xlarge machine (Ubuntu 16.04) in AWS and ran a sync using geth 1.8.11-stable-dea1ce05
Downloaded binaries of raiden from https://github.com/raiden-network/raiden/releases/download/v0.3.0/raiden-v0.3.0-linux.tar.gz

Please let me know if I need to do anything else to have the n/w visible so that I can do some dummy transfers and learn more.

**Comment by vnblr** [comment]
By the way, most of what I tried is from the https://raiden-network.readthedocs.io/en/stable/webui_tutorial.html link plus a bit of https://raiden-network.readthedocs.io/en/v0.3.0/api_walkthrough.html

This being my first reported issue, hope I have not missed anything fundamental in the reporting bit. Thanks in advance for your patience.

**Comment by ulope** [comment]
Hi @vnblr, yes the testnet still exists. 

The issue you're seeing is a known issue in the Web-UI. 
It doesn't show any entries in the token list when it's not receiving the events of their registration. 

One case we know of that causes this is using parity with warp-sync since it won't have the complete previous state after warp syncing which leading to missing events. 

We'll look into solving this issue.

For now, one possible solution for you is to not use warp sync with parity or switch to geth.

**Comment by vnblr** [comment]
Thanks @ulope 
Just to clarify - I am not using parity. I have the testnet fully synced up using geth (1.8.11-stable-dea1ce05). Also I could get microraiden fully working on the same rpc setup. So unlikely there is any problem with the node as such. 
In any case, will try and debug and wait for your resolution. Thanks
