### ISSUE TITLE
Routing should ignore channels that have been tried

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1675]
Thanks to the work made in [this](https://github.com/raiden-network/raiden/pull/1653) PR where the following scenario is tested:

A -> B -> C-> D

when A tries to send a payment to D and C->D has been depleted then a refund transfer is sent back and when B receives this refund transfer it queries the routing module for valid available routes and the "A->B" hop is returned. This is a bug.

Routing should ignore channels that have already been tried.

**Comment by hackaugusto** [comment]
Note: The logic of the Raiden node must not expect the routes to be always clear, this is just making sure the local routing returns reasonable results instead of unexpected values.

External routing services may return invalid routes, Including: routes to non-existing channels, to closed channels, to channels without capacity, channels being closed, channels which have been already used, etc..

**Comment by rakanalh** [comment]
Isn't this the correct behavior? B routed to C which couldn't forward to D which means that a refund transfer is issued to B as C has gone through it's list of available routes and couldn't find a viable way to D. B then considers a different route, but couldn't find anything because C was the only channel available. The logical thing here is to have B refund A for the transfer.

**Comment by hackaugusto** [comment]
@LefterisJP is this issue about the paths returned by [get_best_routes](https://github.com/raiden-network/raiden/blob/9870962df446a8a9b0c947535e869697bfb97967/raiden/routing.py#L48)

**Comment by LefterisJP** [comment]
If memory serves, it's either about `get_best_routes` or [filter_used_routes](https://github.com/raiden-network/raiden/blob/9373c616067430078931de0c69593da88b82691c/raiden/transfer/mediated_transfer/mediator.py#L131)

**Comment by hackaugusto** [comment]
so, isn't `filter_used_routes` sufficient for this?

**Comment by hackaugusto** [comment]
This should be implemented by:

https://github.com/raiden-network/raiden/blob/fcd187098d10d7e1553f2622b46a293093f0e977/raiden/transfer/mediated_transfer/mediator.py#L165-L192

closing the issue.
