### ISSUE TITLE
Move the batch unlock policy out of the state machine

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#1722]
Currently each participant calls batch unlock for one [half of the channel](https://github.com/raiden-network/raiden/blob/be2984577321fd67226307b2ee65c914db55adb9/raiden/transfer/channel.py#L1751). This may be misaligned with the user's interests (because the locks may be all locked or unlocked).

The unlock logic should be moved out of the channel code, and the decision can be expose thourgh the rest api interface.

**Comment by konradkonrad** [comment]
> The unlock logic should be moved out of the channel code, and the decision can be expose thourgh the rest api interface.

That's one option, another one would be a (probably) user configurable policy, that takes _gas prices_ vs _unlock gains_ into account.

One possible way to achieve that:

`ContractSendChannelBatchUnlock` event has the expected received token amount, and a gas estimation attached.
Instead of creating a transaction right away, it will be held in a pool of potential transactions.

A "pool watcher" will periodically check if
- `current_safe_gas_price * gas_estimate_for_transaction > expected_received_token_amount * token_eth_exchange_rate` or
- the transaction has become obsolete (someone else unlocked)

and only execute such transactions.

For tokens with a variable exchange rate against ETH, this will require a user set exchange rate for all tokens the user is concerned with.
The gas price setting (`safe`, `fast`, etc...) would also be a user policy.

**Comment by hackaugusto** [comment]
> ContractSendChannelBatchUnlock event has the expected received token amount, and a gas estimation attached.

I would remove this event altogether, and have this pool watcher decide when to queue the transaction (it would have to listen for `ContractReceveiChannelSettled` events)

**Comment by hackaugusto** [comment]
Update: This has been done. [`ContractSendChannelBatchUnlock`](https://github.com/raiden-network/raiden/blob/02afaf556c5eb85f3adf6be67a9bda5e7f7d7457/raiden/transfer/channel.py#L2292-L2297) is unconditionally emitted, and the [event handler](https://github.com/raiden-network/raiden/blob/02afaf556c5eb85f3adf6be67a9bda5e7f7d7457/raiden/raiden_event_handler.py#L464) will decide if the unlock should be sent or not based on how many tokens the node will receive.
