### ISSUE TITLE
Investigate why Matrix http connection pool fills up

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1847]
## Problem Definition

As described in #1780 the Matrix client sometimes causes a lot of `Connection pool is full, discarding connection` messges.
We should investigate why that happens and and fix the root cause, afterwards we can re-enable HTTP Keep-Alive (which was disabled in raiden-network/raiden-libs#106 as a temporary fix for the problem).

**Comment by rakanalh** [comment]
So far, the only place we seem to be spawning greenlets upon bootstrapping the Raiden node, which in turn open a bunch of sockets to communicate with the server with is here: 
https://github.com/raiden-network/raiden/blob/master/raiden/network/transport/matrix.py#L208
https://github.com/raiden-network/raiden/blob/master/raiden/network/transport/matrix.py#L553
Otherwise, any other bootstrapping task is executed serially. 
I would like to confirm this and see if i can populate the queues with messages that need to be sent and observe the behavior there.

**Comment by rakanalh** [comment]
I was able to reproduce the issue using the following snippet:
```
from raiden.transfer.events import SendProcessed
for i in range(100):
    events = []
    for _ in range(10):
        events.append(SendProcessed(decode_hex('0x6D1aE2fA14078B5Dbc46501Bcc0623C67aA7b5cF'), 'global', i))
    queueids_to_queues[(
        decode_hex('0x6D1aE2fA14078B5Dbc46501Bcc0623C67aA7b5cF'),
        'global' + str(i),
    )] = events
```
Placing this into the matrix client, would populate `queueids_to_queues` with 100 queues, 10 messages each and it would consistently trigger a connection pool issue.
