### ISSUE TITLE
leaving token network doesn't work

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden#1879]
`curl -X DELETE localhost:5001/api/1/connections/0x0f114A1E9Db192502E7856309cc899952b3db1ED` will return `[]`, but no channels are closed.

WebUI returns success for this action.

**Comment by LefterisJP** [comment]
@pcppcp Are you sure that no channels are closed after some time. The webui returns success for the action as it's an asynchronous call.

**Comment by pcppcp** [comment]
hmm, I'll try to reproduce it. Maybe it's related to number of open channels, but it didn't work for both webui and cli.

**Comment by rakanalh** [comment]
Debugging this lead me to check both `views.get_channelstate_for_receiving` and `views.get_channelstate_open`. The former will return an empty list while the latter would return the list of open channels. Going back to the APIs, we have a parameter: `only_receiving_channels` which defaults to `True`. Meaning that we will only be triggering leaving a channels `for receiving` while other open channels can still be open.
The `leave` method of the `ConnectionManager` is documented with:

>         Note: By default we're just discarding all channels for which we haven't
>         received anything.  This potentially leaves deposits locked in channels after
>         `closing`. This is "safe" from an accounting point of view (deposits
>         can not be lost), but may still be undesirable from a liquidity point
>         of view (deposits will only be freed after manually closing or after
>         the partner closed the channel).
> 
>         If only_receiving is False then we close and settle all channels
>         irrespective of them having received transfers or not.
The confusing part here is that `views.get_channelstate_for_receiving` returns the list of channels from which we actually received transfers. So the first sentence of the `leave`'s method comment contradicts the logic implemented. 

Calling the leave API:
```
http --timeout 1000 DELETE http://localhost:5003/api/1/connections/0x0f114A1E9Db192502E7856309cc899952b3db1ED only_receiving_channels=false
```
Successfully triggered all channels to close. 

### Suggested solutions:
1. Make `only_receiving_channels` false by default
2. Do nothing and explicitly document the choice that the user has to make. However, we have to take into consideration that the UI doesn't prompt the user for selecting which channels to close when leaving the network, which brings us to the first point.

@LefterisJP @hackaugusto please advise.

**Comment by LefterisJP** [comment]
@rakanalh hahaha nice find. So basically the function **should** have been doing what the comment says it does. But as you noticed, due to using `views.get_channelstate_for_receiving` it is doing the exact opposite. That is definitely a bug.

But let's take a step back and explain the reasoning here. In the past we could not recover from an irregular shutdown. Now with the WAL we can and we do so.

Instead what we guaranteed was that you safely use Raiden and shut it down regularly. Shutting down regurarly would cause you to close all channels and only after closing and settling would the shutdown be succesfull. To make that faster while keeping the safety guarantee we added this "only_receiving" flag to do what the comment describes. But it should have been `only_not_received` instead.

Now that we are done with the history lesson ... I could go as far as saying we don't really need that argument anymore. So I would remove that logic completely, especially considering it's not exposed from the web UI.
