### ISSUE TITLE
ChannelEndState.compute_merkleroot_without looks fishy

### ISSUE THREAD

**Issue by schmir** [raiden-network/raiden#188]
The following code can be found:

```
        if isinstance(exclude, Lock):
            raise ValueError('exclude must be a Lock')
```

It looks like it should read "if not isinstance....".

Then there's:

```
        if exclude.hashlock not in merkletree:
            raise ValueError('unknown lock `exclude`', exclude=exclude)
```

which also seems wrong (it should check if exclude_hash is not in merkletree).

Good thing is, the method is not being used.

**Comment by hackaugusto** [comment]
Thanks for the report.

A `DirectTransfer` could be sent with a `secret` value embedded, this transfer would have an up-to-date `locksroot` with the corresponding lock claimed, the method `compute_merkleroot_without` was used in this case to validate the `locksroot`.

This feature was dropped by me in the commit 05e79d9eda8f850a019893432ba12d78c2de07bf .

I removed the `secret` from the `DirectTransfer` at the time because:
- It was an under tested.
- It was an unused optimization.
- A secret can only be embedded in a `DirectTransfer` if at the time the transfer is being made there is a known Secret waiting to be used, and I considered this an unlikelly case.

Removing this fishy method is safe.
