### ISSUE TITLE
Investigate why travis integration test triggering isn't working 

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#1918]
## Problem Definition

We configured Travis to run the full integration suite when the trigger `[ci integration]` is included in the `HEAD` commit message. 
This didn't work in #1869 

This may be the same issue as #1887.

**Comment by andrevmatos** [comment]
When you look at Travis interface, to what commit it _sees_ (i.e. the commit that triggered that build), you may see something like 1087c9e1768ab6186373cccac5ea2759ff532c5a : `Merge 3664aaa into 31f2ac3`, a merge commit where the first parent is PR's HEAD, and the second parent is the current master's HEAD, even though the PR is fully rebased on current master.
As so, Travis doesn't see the actual commit message, but that `Merge` one, and therefore, doesn't trigger the correct stages. Looks like this merge commit also strips the `cron` status, as it's not not running integration tests. So it seems to be a GitHub issue rather than a Travis system or config one.

**Comment by ulope** [comment]
But cron is a Travis feature and given their track record, it seems possible that they changed something and didn't fully consider what other features it would break.

**Comment by LefterisJP** [comment]
Shouldn't we open an issue at [Travis itself](https://github.com/travis-ci/travis-ci/issues?q=is%3Aopen+is%3Aissue) for this?

**Comment by andrevmatos** [comment]
Reported here: https://github.com/travis-ci/travis-conditions/issues/7

**Comment by andrevmatos** [comment]
Sorry for the commit-reference spam, had to test every single possibility: `tag` regex condition made it fail, I think it's some kind of failure on the conditions/regex parser, since the tag is valid acording to documentation. Removing it, plus enforcing `conditions: v1`, which should be the default, made `[ci integration]` on commit-message trigger integration tests again.
