### ISSUE TITLE
Check the rest API for all exceptions that can crash the node

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#1944]
Go through the RESTAPI code and make sure that all exceptions are caught and handled properly and that nothing can cause the node to crash.

**Comment by LefterisJP** [comment]
Related to: #1966

**Comment by CosminNechifor** [comment]
Hopefully I didn't forget anything

- ``/address``  - is fine since there is no exception to handle (everything happens internally)
- ``/channels`` - No unhandled exception since this endpoint does not offer r
``get_channel_list`` any arguments, it will not raise an exception
- ``/channels/<hexaddress:token_address>/<hexaddress:partner_address>``: Patch endpoint has a problem -> When we call [patch_channel](https://github.com/raiden-network/raiden/blob/master/raiden/api/v1/resources.py#L65) this method calls  [get_channel](https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py#L1096), and because  ``token address`` or ``partner_address``  might not be valid, we can have an``InvalidAddress`` exception being raised from here: (https://github.com/raiden-network/raiden/blob/master/raiden/api/python.py#L80-L84)
- ``/connections/<hexaddress:token_address>``:  didn't see any uncought exception
- ``/connections``: didn't find any unhandled exception
- ``/payments/<hexaddress:token_address>/<hexaddress:target_address>``: 
	- In the **POST** endpoint we call ``initiate_payment`` we call the transfer (transfer_async) which might give us an uncought ``UnknownTokenAddress``.
	- In the **GET** - didn't found any uncought exception
- ``/tokens``: didn't find any unhandled exception
- ``/tokens/<hexaddress:token_address>/partners`` -> should catch ``InvalidAddress`` inside ``[get_partners_by_token](https://github.com/raiden-network/raiden/blob/master/raiden/api/rest.py#L886)``  
- ``/tokens/<hexaddress:token_address>`` ->  didn't see any uncought exception
- ``/_debug/blockchain_events/network`` -> didn't see any uncought exception
- ``/_debug/blockchain_events/tokens/<hexaddress:token_address>`` -> didn't see any uncought exception
- ``/_debug/blockchain_events/payment_networks/<hexaddress:token_address>/channels/<hexaddress:partner_address>`` -> didn't see any uncought exception

**Comment by LefterisJP** [comment]
Thank you Cosmin. This looks really good.
