### ISSUE TITLE
Matrix must process received messages synchronously when being started

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#2133]
## Problem Definition

Raiden's matrix transport at the moment syncs and handles invite events. However, with #2086, we should ensure that all events received are processed synchronously in the matrix `start` before returning. This makes sure that the API server will start iff Raiden is in sync and has processed all events received from the blockchain and transport.

This is required as we need to make sure that the API doesn't get called while the matrix is still syncing messages since in this case, the message queue will contain messages with the wrong order.

According to my discussion with @andrevmatos, this issue depends on #2081. That will help identify a checkpoint with which we can identify processed vs pending messages and only process pending messages that don't have a read receipt.

**Comment by andrevmatos** [comment]
On initial sync, the messages are received, but the room listeners weren't added yet (as the rooms weren't even created yet), so they aren't handled. So, at the end of `start`, all messages in the queue (sent while the node was offline) would have been received, but discarded. After start, only new messages/messages sent **after** initial sync, may be received and should be handled (well, actually after the respective `start_health_check` calls were made too).
#2081 proposes using matrix to have an on-server cursor of received messages, and sending them only one at a time, waiting for the read receipt to send another. This should ensure there's at most one message in the queue, and that they'll be handled once the node comes back online, so no need for retries.

**Comment by hackaugusto** [comment]
> we should ensure that all events received

Just as clarification, these are not *incoming* events from the Matrix service, [but Raiden events passed to start](https://github.com/raiden-network/raiden/blob/7684f387e01c6482616bff5ce3d12573685e9ae6/raiden/raiden_service.py#L269)

>  are processed synchronously in the matrix start before returning.

Also, we don't need to process the events in the sense "push the data to the chat rooms", we only need to make sure the `MatrixTransport` instance is properly initialized to avoid race conditions where a user action is handled before the events from the queue (assuming this is even possible).

> This is required as we need to make sure that the API doesn't get called while the matrix is still syncing messages

Also, not just the Matrix transport, but any transport must be fully initialized once `RaidenService.start` is done.

**Comment by rakanalh** [comment]
@hackaugusto 
> Just as clarification, these are not incoming events from the Matrix service, but Raiden events passed to start
If your concern about API calls resulting in an event being appended to `queueids_to_queues` before the existing items which are already there, i think this is not the case. Since both transports (matrix & udp) get a ref to `queueids_to_queues` which means [updates to the items](https://github.com/raiden-network/raiden/blob/7684f387e01c6482616bff5ce3d12573685e9ae6/raiden/transfer/node.py#L1045) will be seen by all parties who share this reference. [In matrix](https://github.com/raiden-network/raiden/blob/7684f387e01c6482616bff5ce3d12573685e9ae6/raiden/network/transport/matrix.py#L224) and [udp](https://github.com/raiden-network/raiden/blob/7684f387e01c6482616bff5ce3d12573685e9ae6/raiden/network/transport/udp/udp_transport.py#L195) `queueids_to_queues` is processed to dispatch existing items and most probably any items that get appended to the queues between "start" and the "send" greenlet.

**Comment by hackaugusto** [comment]
> If your concern about API calls resulting in an event being appended to queueids_to_queues before the existing items which are already there, i think this is not the case.

Yes, that is the race I'm concerned with. When a local action adds a new message to the **transport's queue** prior to it being properly initialized.

> Since both transports (matrix & udp) get a ref to queueids_to_queues which means updates to the items will be seen by all parties who share this reference.

The code in the link does not have a synchronization problem because we are following these steps synchronously:

- restore the latest snapshot state
- apply the pending events from the blockchain

At this point the off-chain state is synchronized with the on-chain state, and the queue will be correct state. Additionally we assume the cooperative schedule nature of the greenlets + the complete lack of IO inside the state machine code, which means that operations that change that queue will be atomically executed on top of the pristine state.

>  In matrix and udp queueids_to_queues is processed to dispatch existing items and most probably any items that get appended to the queues between "start" and the "send" greenlet.

The queue passed to the `start` must not be messed with. Ideally it would be a read-only reference to a given snapshot of the queue or a copy.

The protocols don't actually keep a reference to the queues, that queue is just used during start up to send messages which are pending from the last run, the new messages are then sent using [MatrixTransport.send_async](https://github.com/raiden-network/raiden/blob/7684f387e01c6482616bff5ce3d12573685e9ae6/raiden/network/transport/matrix.py#L248-L253) or [UDPTransport.send_async](https://github.com/raiden-network/raiden/blob/7684f387e01c6482616bff5ce3d12573685e9ae6/raiden/network/transport/udp/udp_transport.py#L342-L347), and since the `send_async` and `start` methods don't have synchronization, a race can happen there.

**Comment by andrevmatos** [comment]
#2268 changed the behavior on this, and may have solved this issue, for matrix at least:
- no reference to `queueids_to_queue` is kept, instead it's now a [read-only] property fetched straight from the state through a `view`
- `_send_queued_messages` is synchronous, and will finish inside `start`, but it also doesn't send the messages right away, but `send_async` them, which will in practice spawn a greenlet which will try to send the message **while it's in the queue** and **if** the peer is online, meaning that if a message is cleaned at some point, its greenlet will gracefully exit.

So, if the queue is fully initialized when the transport is started, no race should happen

**Comment by andrevmatos** [comment]
Ok, closing this as fixed by #2268. Everything is synchronous now here, of course depending on `Delivered/Processed` messages to clean the queues and stop retries (which are asynchronous by definition), but `start` only returns after all queued messages greenlets are started.
