### ISSUE TITLE
UI representation of token amount might be misleading

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/raiden#2275]
## Problem Definition

After I opened a channel and deposited 80 tokens I had the vague impression that I only deposited 8, because in the UI the amount was shown as ``0.0000008`` instead of ``0.00000080``.

**Comment by kelsos** [comment]
@CosminNechifor I had a discussion with @andrevmatos and he raised some valid points.
The default/suggested decimal value is 18 decimal points so you will have `0.100000000000000000` if you don't truncate decimal points instead of `0.1`.

I can understand the confusion when adding a lot of decimal points so I am gonna change the display to use scientific notation when displaying really small values.

**Comment by CosminNechifor** [comment]
@kelsos good idea.
