### ISSUE TITLE
Assert loops in all contracts are sanely bound

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#232]
This issue is also a subpart of #84 but I believe it's important enough to warrant its own ticket.

Unbound loops in solidity are very dangerous. At the moment we have a lot of `for()` loops in the contracts which are probably fine but we are bound by the block gas limit.

All for loops should be checked and proper checks be put in place, or the code should somehow be handled differently.

For example [here](https://github.com/raiden-network/raiden/blob/16060cb36d354f4320232b8504a9106dc04aed50/raiden/smart_contracts/ChannelManagerLibrary.sol#L71) we are iterating all the open channels and perform actions for each one. Once the number of open channels makes that loop reach the block gas limit the contract will be blocked forever.

All of our loops should be addressed and either limits be put in place or the code should be rethought.

**Comment by czepluch** [comment]
As discussed with @LefterisJP and @hackaugusto a good solution to this will be to use something like `mapping (address => (mapping(address => bool))`, and then use events to get the data that the current `constant` functions in ChannelManagerLibrary/Contract return. 

Solving this issue will also allow for a much more elegant and efficient solution for #93

**Comment by czepluch** [comment]
`Registry.sol` is also vulnerable to this https://github.com/raiden-network/raiden/blob/master/raiden/smart_contracts/Registry.sol#L7 .
I suggest we remove the array and use client side events to get the list of all assets instead

**Comment by czepluch** [comment]
It's been decided that issue should be split up into smaller issues. Quite some time has been put in to this issue already, but due to some difficulties it has not been finalized yet.

The current process of this issue is the following:

* Updated smart contracts to use mappings instead of arrays for keeping track of the open channels. (This means that we lose the possibility to retrieve all open channels by iterating through the array, but we should still be able to build the list of all open channels by querying events from the blockchain.) The smart contract tests are passing from this change.

* After above changes the call for getting all channels (https://github.com/raiden-network/raiden/pull/250/commits/e20a0cd69b067e22f965b9a19f21ed0648347c44#diff-c53a383092e17d1404bc7405c9568185L425) was no longer available. Therefore it was necessary to implement functionality for iterating through all events on the BC in order to build the list of open channels. This was attempted to be solved with this commit (https://github.com/raiden-network/raiden/pull/250/commits/a530f723c04f297eebeb554e6ef60727556a9c7a), but it seems that the problem is that `tester_client.py` is using some genesis block that does not omit events, and therefore nothing is added to the list of open channels. This leads to a lot of failing tests. And since parts of the code depends on the `assetAddresses()` function of the smart contracts, we cannot just swap changes to the smart contracts. 

* It's also been suggested that we access the storage of the contract directly to get the values from the mapping, but this turned out to not be possible either, since the values of the mappings are only stored as hashes.

* Going forward from here we need a way to ensure that events are omitted when using `tester_client.py`, so that we can build the list of open channels. @hackaugusto recently suggested that it might be worth looking into just returning here (https://github.com/raiden-network/raiden/blob/master/raiden/tests/fixtures/blockchain.py#L85), since that would mean that no genesis block is used.

This issue has been split out into smaller issues see #311 #312 #316 and #317

**Comment by czepluch** [comment]
fixed with https://github.com/raiden-network/raiden/pull/375
