### ISSUE TITLE
RPC calls for blocknumber and discovery should be cached

### ISSUE THREAD

**Issue by utzig** [raiden-network/raiden#234]
Some way of doing less RPC calls for getting the current block number and discovery information must be devised.

Regarding discovery, every time a `raiden` protocol packet is sent from a node to another node, a new RPC call for discovery is made (translates `raiden` address to host:port) in those places:

https://github.com/raiden-network/raiden/blob/master/raiden/raiden_protocol.py#L96
https://github.com/raiden-network/raiden/blob/master/raiden/raiden_protocol.py#L224

Regarding `block_number` there's lots of usage in the _run loops inside the greenlets created by `task.py`.

One approach to fix the problem is to add caching with time-to-live, which I did for a throughput demo. Commit here:

https://github.com/utzig/raiden/commit/92bf68da3005cb37024b921a70f4620b1fb8e33b

PS: This was a very simple implementation of a possible solution, but it's efficient enough to bring a single 3 node cluster with mediated transfers from 15 transfers/s up to 70 transfers/s without the `LogListenerTask`refactoring as suggested on #233. Probably not a good solution for a production product but works well enough for throughput demo. Some better architecture needs to be devised probably on the RPC client itself.

**Comment by hackaugusto** [comment]
duplicated: #124

**Comment by LefterisJP** [comment]
Adding here notes from our discussions on Raiden and client RPC connections during the Fuerte Ventura Retreat:

## Communication Protocol Used by Our RPC connection

JSON-RPC via an instance of pyethapp.rpc_client which is essentially
https://tinyrpc.readthedocs.io/en/latest/. It's making JSONRPC calls via HTTP


## Functions currently used when interfacing with an ethereum client

eth.blockNumber
eth_uninstallFilter
deploy_solidity_contract
eth_get_filterChanges
call()
polling transaction calls

### Problems

- It seems we are creating too many RPC connections and we must find a way around it:
https://github.com/raiden-network/raiden/issues/253

- We should be doing caching. What kind of caching strategy should we be doing?

##Ideas

- We have too many calls to the ethereum node, so we should try to reduce the number of node calls. Improve/implement caching?
- Poll only if there is a new block mined, to save RPC calls
- Poll for any event in a particular contract address and filter them on the application side depending on the results
- Why are we creating too many RPC connections when making client calls? Related to: https://github.com/raiden-network/raiden/issues/253
- What should be cached? Block number and all properties of the channel we should try to cache and not have to make calls to the client for every single time we want to query a property of the channel.
- Question: How do we handle chain reorganizations? What kind of caching strategy should we use in order to tackle chain
reorganizations? i.e.: If your cache has been updated with the value of a losing chain, then a chain reorganization happens and you need to update your cache. How do we handle that?

**Comment by hackaugusto** [comment]
> RPC calls for blocknumber and discovery should be cached #234

The issue as described above is fixed by the PR #286. The realated issue of number of connections is open at #253 .

Closing the issue since the caching is done with:

- Poll only if there is a new block mined, to save RPC calls.
- Caching the contracts properties and updating through events.
