### ISSUE TITLE
security problem about matrix room

### ISSUE THREAD

**Issue by nkbai** [raiden-network/raiden#2450]
## Problem Definition
for example Alice login to transport01.raiden.network,and the user id is @alice:transport01.raiden.network
and Bob login to transport01.raiden.network, and the user id is @bob:transport01.raiden.network

if Alice want to send a message to Bob,then Alice will create a chat room !alice_bob:transport01.raiden.network. 
it seems that there is no problem.

now there is  a hacker Eve who watch that alice and bob create  a channel on ethereum, so he create a room !alice_bob:transport01.raiden.network and mark this room is private.

if Eve create all the rooms for all the channel participants ,then raiden network is shutdown. no one can send message to each other.

Is this a possible attack?

**Comment by ulope** [comment]
Thanks for the report @nkbai and good thinking! :)

However, the room aliases are only a convenience feature mostly intended to ease debugging and human introspection. 

The room aliases aren't necessary for raiden to operate and the nodes will automatically use un-named rooms if they cannot assign or join an aliased one (e.g because the alias has already been taken).

**Comment by andrevmatos** [comment]
For reference:
https://github.com/raiden-network/raiden/blob/7facbf3f9ce025c8fcbaa76983deb2bab045540a/raiden/network/transport/matrix.py#L846-L856

**Comment by nkbai** [comment]
thanks very much.
