### ISSUE TITLE
How to handle contract features not available in the client (yet)

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#2467]
We need to decide how to handle features that are available in the smart contracts but not in the client yet.

A good example is `cooperativeSettle` (@CosminNechifor and @Dominik1999  came up with that):
Right now we update the routing information inside Raiden only on `ChannelOpened` and `ChannelClosed` events. However when calling `cooperativeSettle` no `ChannelClosed` event gets emitted which leaves the client in a wrong routing state. This is only a problem when calling `cooperativeSettle` manually though.

Possible solutions include:
1. Make `cooperativeSettle` emit a `ChannelClosed` event
1. Handle the `ChannelSettled` event to update the Routing state as well.

While 1) seems like the easiest solution it leads to other problems. As @loredanacirstea noted we also don't handle withdrawal events either, so in case someone calls `setTotalWithdraw` manually our internal routing based on the deposits will be wrong as well. 

This leaves us with the question if we should:
- handle these cases
- leave them unsupported (but what's gonna happen if we later implement the feature, will it be upgradeable)
- or even remove them from the SC for now (making place for the contract limits at the same time).

**Comment by LefterisJP** [comment]
So seems like we got a problem. Let me document here what our current predicament and our options are:

## Problem Definition

When trying to implement the smart contract limits we realized that there is no way to fit them in one contract. We hit the hard-coded bytecode size. At the same time as mentioned in the initial post we may have a problem if users use the coop-settle or withdraw functionality of the contracts directly without going through the client.

## Solutions

There are various ways to go ahead from here but they all involve trade-offs.

### Remove the features from the contracts

We can remove the features that are not yet implemented at the client side from the contracts all together.

#### Pros

- We would get rid of the bytecode side for the deployment problem
- We would not have to think about what potential side-effects could occur on the client side if someone tries to manually invoke the unimplemented client features by directly invoking the contracts.

#### Cons

- We lose the advantage of not needing to redeploy to take advantage of the new features. Up until now our thinking was that no redeployment would be needed until Ithaca and that we could simply implement the coop-settle and withdraw functionality in the client and make them available to users in incremental client-side only releases.

- We have to think about upgradability of the smart contracts right now and have to make a decision on how to handle the smart contracts upgrades that will have to come between Red Eyes and Ithaca.

### Split part of the contract code into a library

We can split part of the contract code so that it's properly deployable on the mainnet.

#### Pros

- We still keep the coop settle and withdraw in the contracts, allowing us to introduce them as new features only with client side upgrades.

#### Cons

- We need to write tests and adjust the client code if needed in order to make sure that manually invoking either coopsettle or withdraw does not cause any undefined behaviour or put the client in an unusable state.

**Comment by palango** [comment]
> adjust the client code if needed in order to make sure that manually invoking either coopsettle or withdraw does not cause any undefined behaviour or put the client in an unusable state.

Just a note on the scope of the changes for this:
- Handling coopsettle should be easiest with adding the event to the contracts, but event handling it in raiden would just be adding some code in the settle event code that checks if the route is still there and remove it if so
- Withdrawal support is easy in theory, by just listening to the events and adapting the channel balances accordingly. The more difficult problem here might be upgradability of the simplified version afterwards. (@hackaugusto , do you agree?)

**Comment by LefterisJP** [comment]
> withdraw should not be possible without client support, since two signatures are required. If the user is calling the smart contracts with invalid data for both clients there is not much that we can do

That is correct. Same goes for coopsettle. Both clients need to mess with the smart contracts manually, so if they mess up their channel by doing something unsupported that should not be our problem. As long as they don't mess up the network for anyone else.

> So I don't think that withdraw can be a problem. (Meaning we don't need to add code to handle it now)

It can be unfortunately for the same reason as coopsettle. Our global view of the network for routing is based on the total deposits. That may change if channels start withdrawing tokens on chain and the client is not aware of it.

**Comment by LefterisJP** [comment]
After a quick call we decided to go with removing the unimplemented functionality in the client: https://github.com/raiden-network/raiden-contracts/issues/265
