### ISSUE TITLE
Do not use globals that need to be reset in tests

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#251]
In some places (at least 
https://github.com/raiden-network/raiden/blob/master/raiden/tests/unit/test_service.py#L40-L55) we are manually setting class attributes in order to reset them at the bottom of the test functions. This can lead to hard to explain behavior if single tests (x)fail, because the reset calls will not be executed.
This should be fixed by using pytests [`monkeypatch`](http://doc.pytest.org/en/latest/monkeypatch.html) instead.

**Comment by hackaugusto** [comment]
What about a `RaidenProtocol` subclass for testing, like `UnreliableRaidenProtocol`?
Then we don't need to remeber to use the monkeypatch.

**Comment by konradkonrad** [comment]
If the functionality is needed in many places I'm fine with creating a reusable facade. From a transparency point of view however, it may be nicer to see the "patched" attribute in the test function directly. Either way, we should get rid of the "global" class attribute modifications.

**Comment by hackaugusto** [comment]
Other occurrence: https://github.com/raiden-network/raiden/blob/master/raiden/network/transport.py#L112

**Comment by himynameisbeni** [comment]
@konradkonrad  Can I take a look at this? I'd be interested to give it a go. I have a question though what exactly is the class attribute with the issue here, is it `ack_message`? also @hackaugusto if I solve this i can fix the other occurrence too.

**Comment by LefterisJP** [comment]
@himynameisbeni Since this issue is more than 1 year old and the links were not made to point to a particular commit then I am rather sure that they no longer point to the correct code.

@konradkonrad Can you update the link and specify the problem, provided it's still an issue?

**Comment by hackaugusto** [comment]
### Konrad's

The first commit before konrad comment from 2016-11-14 is d79e8c32b7c26f4fd57ca3b6efa8686815b5c5a4 , konrad was poiting at this code:

https://github.com/raiden-network/raiden/blob/d79e8c32b7c26f4fd57ca3b6efa8686815b5c5a4/raiden/tests/unit/test_service.py#L40-L55

I believe Konrad was talking about [`RaidenProtocol`'s class attributes](https://github.com/raiden-network/raiden/blob/d79e8c32b7c26f4fd57ca3b6efa8686815b5c5a4/raiden/raiden_protocol.py#L55-L57) and maybe about [`UnreliableTransport`'s `droprate`](https://github.com/raiden-network/raiden/blob/d79e8c32b7c26f4fd57ca3b6efa8686815b5c5a4/raiden/tests/unit/test_service.py#L39). These have been fixed since then:

-  `RaidenProtocol`'s `repeat_messages` was removed at commit https://github.com/raiden-network/raiden/commit/a6c228bfecf08949a9c053a386405fd52c753283#diff-a6ce7fafe4155e1d51ed77b8fa178d16L24
- `RaidenProtocol`'s `try_interval` and `max_retries` became an instance attribute at commit https://github.com/raiden-network/raiden/commit/c9f69fb3c974555f2c668d2790240e3551da592c#diff-36a2cc663db8263416e47081d1939e5eL73
- UnreliableTransport`'s was a [class attribute](https://github.com/raiden-network/raiden/commit/aa5d88d5f6d334ac98b13df6f9d379511288857b#diff-d1974d09e1f3f1e3b1513dcea66fdf85L206), which has been changed to an instance attribute by https://github.com/raiden-network/raiden/commit/aa5d88d5f6d334ac98b13df6f9d379511288857b#diff-1e6411d480fa40585f6564a174efff8eR50

### Augusto's 

The first commit before my comment from 2017-01-12 is baa96bb8c68531db9086846044510298113e21c2 , I was poiting at this code:

https://github.com/raiden-network/raiden/blob/baa96bb8c68531db9086846044510298113e21c2/raiden/network/transport.py#L112

This is still [in use](https://github.com/raiden-network/raiden/blob/baa96bb8c68531db9086846044510298113e21c2/raiden/tests/utils/messages.py#L10-L19), this actually doesn't *need* to be reset, but I think it needs to be fixed.

### Other occurrences

For the `DummyTransport`, used in tests:
- [`network`](https://github.com/raiden-network/raiden/blob/aa5d88d5f6d334ac98b13df6f9d379511288857b/raiden/network/transport.py#L153), this does the job of the EndpointRegistry smart contract, used when we don't want to run private blockchain for the test.
- [`on_recv_cbs`](https://github.com/raiden-network/raiden/blob/aa5d88d5f6d334ac98b13df6f9d379511288857b/raiden/network/transport.py#L154) unused, it can be removed.

### Fix

First:
- [`on_recv_cbs`](https://github.com/raiden-network/raiden/blob/aa5d88d5f6d334ac98b13df6f9d379511288857b/raiden/network/transport.py#L154) can be removed
  - [`track_recv`](https://github.com/raiden-network/raiden/blob/aa5d88d5f6d334ac98b13df6f9d379511288857b/raiden/network/transport.py#L180-L183) too can be removed

Second:
1. `on_send_cbs` can be changed to a decorator (the pattern not the language feature), recording sent messages by default
1. To do this [transport instantiation](https://github.com/raiden-network/raiden/blob/aa5d88d5f6d334ac98b13df6f9d379511288857b/raiden/app.py#L55-L65) needs to be moved out of the App constructor, this should be most of the work
1. Then the `UDPTransport` and `DummyTransport` constructors can diverge and the `network` can be passed as a constructor argument

**Comment by LefterisJP** [comment]
Hehe very nicely detailed Augusto! I believe you got all the info you need @himynameisbeni :)

**Comment by himynameisbeni** [comment]
@hackaugusto When you say move the transport instantiation out of the App constructor should it just have it's own function within the class?

**Comment by hackaugusto** [comment]
> When you say move the transport instantiation out of the App constructor should it just have it's own function within the class? 

Not a new function but a new argument for the constructor (`__init__`).

Currently the transport is instantiated inside the `App` constructor (shown in the excerpt bellow).

https://github.com/raiden-network/raiden/blob/aa5d88d5f6d334ac98b13df6f9d379511288857b/raiden/app.py#L55-L65

> Sorry for all the questions this is my first open source contribution :)

You're good ;)

**Comment by hackaugusto** [comment]
this was fixed by ca7ecd522e7b69555b2b6edfe5713009612c5345
