### ISSUE TITLE
REST API: Target channel balance is not immediately updated after the initiator returned the REST call

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2523]
## Problem Definition

When querying a channel's state (via the `/channels/<token_address>/<partner_address>` endpoint) from the target immediately after executing a payment (but after the payment HTTP call returned) the balance may not match because it takes a bit of time for the target node to update its local balance.

- [ ] Improve the documentation of the above endpoint informing the user that this may occur.

**Comment by hackaugusto** [comment]
Could you give a bit more of detail?

Are you querying the endpoint for the initiator, a mediator or the target?

**Comment by ulope** [comment]
Will provide more detail once I re-create it. It happened multiple times yesterday night while testing the scenario player. Just wrote it down so not to forget.

**Comment by hackaugusto** [comment]
Okay, I'm asking because it's expected to have a bit of delay before the REST API returns to the initiator and the nodes synchronize.

Right now the transfer is considered successful at this point:

https://github.com/raiden-network/raiden/blob/9ca97036f45b9f938a527d1f686d2e4ca24c5e1c/raiden/transfer/events.py#L316-L337

But that doesn't mean the initiator's payee or the target nodes have received an unlock yet, therefor the local balance will be updated but the remote may be lagging behind. (Note that the above is already quite conservative and adds a lot of latency just for the sake of consistency, I don't think we can actually improve much on it)

**Comment by ulope** [comment]
Ok, you're right. I was querying the payment's target's view of the channel right after the payment call to the initiator returned. 
So I guess there's no way around adding a short wait before querying the channel state.

**Comment by hackaugusto** [comment]
Okay, I updated the issue description to make it a documentation issue.
