### ISSUE TITLE
Many parallel transfers leads to some becoming stuck

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#2567]
## Problem Definition

This [scenario](https://gist.github.com/ulope/7fad24474a17056fd45f70960f01feea) leads to some transfers becoming stuck. Usually no later than the second repeat of the `serial` task set.

From quickly investigating the logs it appears that at some point messages aren't being processed anymore.

Needs more digging.

**Comment by palango** [comment]
This seems to have happened on the first run as well. Logs are attached.
![image](https://user-images.githubusercontent.com/90851/46351590-03531b80-c658-11e8-9219-930dd9208708.png)
[raiden-debug.log](https://github.com/raiden-network/raiden/files/2438050/raiden-debug.log)
[raiden-debug1.log](https://github.com/raiden-network/raiden/files/2438053/raiden-debug1.log)
[raiden-debug2.log](https://github.com/raiden-network/raiden/files/2438054/raiden-debug2.log)

**Comment by hackaugusto** [comment]
@palango The transfer did not get stuck, it expired.

- Node `fcfad555` started a transfer to `2a0374bf` with the id `4242318251562065606` at time `13:24:17`. It's local view of the block number was at block number `4156434`, and the lock's expiration was `4156454`.
- The corresponding message was sent at `13:24:17` and received at `13:24:19` the receiver's block number was at `4156444`, but discarded because it was out of order:

> 2018-10-02 13:24:19 [debug    ] Raiden event                   [raiden.raiden_service] node=2a0374bf raiden_event={"identifier": 4242318251562065606, "secrethash": "0x0c3b8baed28637cc49f10e767845a5a78d0897642483ff7d4c44d6fe67f04daf", "reason": "Invalid LockedTransfer message. Nonce did not change sequentially, expected: 14 got: 15.", "_type": "raiden.transfer.mediated_transfer.events.EventUnlockClaimFailed", "_version": 0}

- The message was retried at `13:24:24` and received at `13:24:25` and then it failed because it expired. the receiver's block number was at `4156445`:

> 2018-10-02 13:24:26 [debug    ] Raiden event                   [raiden.raiden_service] node=2a0374bf raiden_event={"identifier": 4242318251562065606, "secrethash": "0x0c3b8baed28637cc49f10e767845a5a78d0897642483ff7d4c44d6fe67f04daf", "reason": "lock timeout is unsafe. timeout must be larger than 10, but it is 10. expiration: 4156454 block_number: 4156444", "_type": "raiden.transfer.mediated_transfer.events.EventUnlockClaimFailed", "_version": 0}

The problem here is that the sender is reveal timeout blocks behind the receiver, which basically means the lock was inside the danger zone when it was sent, and the receiver rejected it.

The solution is just to increase the reveal timeout.

**Comment by LefterisJP** [comment]
I would go for a safety margin, and not only for Ropsten. 50 blocks sounds good.

**Comment by hackaugusto** [comment]
> So what would be a reasonable reveal timeout?

The reveal timeout is how long it takes for **one** transaction to be mined **under congestion**. Our current assumption is that `web3.py` gas price estimation will chose the price so that the transaction is mined in 20 blocks. So 50 blocks sounds good.
