### ISSUE TITLE
Integration tests fails with a single geth instance on travis

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#258]
### Why decrease the number of geth instances?

raiden tests dont /require/ more than one geth instance, decreasing from 3 to 1 would make the log output more readable since it removes interleaved/duplicated lines.

### What is the problem

The travis integration tests fail more often because of the lack of output, and since the build process is killed we don't see the output of the hanging test:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> 
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> 
> The build has been terminated

### Why not use --capture=no

Because it mixes the sucessfull / failed tests output and makes reading the output harder, it can also make the travis build fail if too much log is printed (more than 4mb)

**Comment by LefterisJP** [comment]
So this issue is for reducing the [number_of_nodes](https://github.com/raiden-network/raiden/blob/master/raiden/tests/fixtures/variables.py#L440) in tests ran in Travis?

We can use something like 
```
    if 'TRAVIS' in os.environ:
        return 1
    else:
        3
```

By not using `--capture=no` you refer to the pytest `-s` option, correct?


As for the issue at hand, sure we can try to reduce the number of geth instances, but let's just always keep in mind that tests should also reflect the real scenarios that raiden should work in. I will need to test how the integration tests will work with only 1 instance.

**Comment by hackaugusto** [comment]
> So this issue is for reducing the number_of_nodes in tests ran in Travis?

Yes.

`return 1` is precisely what I tried, I don't see a reason for locally using `3` instead of `1`. The builds with `1` geth instance failed:

https://travis-ci.org/raiden-network/raiden/jobs/176217247
https://travis-ci.org/raiden-network/raiden/jobs/176236060

> By not using --capture=no you refer to the pytest -s option, correct?

Yes.

**Comment by hackaugusto** [comment]
Closing since #405 is merged and we are not experiencing problems with geth because of the quantity of nodes.
