### ISSUE TITLE
Solidify the channel closing/settling strategies

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#278]
As seen in https://github.com/raiden-network/raiden/pull/276 the current methods for closing and settling a channel are not well defined and some thinking. To sum up, at the moment there are cases where a participant can close a channel without a transfer while transfers have been made requiring his counterparty to present 2 different transfers to the channel in order to settle.

Let us use this issue in order to decide on and solidify the different ways to close and settle a channel.
Once that is decided I can implement in in #276.

### `close(first_transfer, second_transfer)`
Allows closing a bidirectional channel by presenting the latest transactions from both participants. At the moment no checks happen on the transfers ... which allows you to abuse it by providing two different transactions by the same participant.

### `closeSingleTransfer(transfer)`
Allows closing a channel  by presenting the latest transaction. At the moment no checks for who this transaction comes from are made .

### `closeWithoutTransfer()`
Allows closing a channel that was unused. But ... can be abused and can also be called on a channel where transfers happened since the contract has no way to know about it before closing.

### `updateTransfer(transfer)`

After the counterparty has closed the channel this function gives you the ability to dispute the closing of the channel by presenting a more recent transfer .... but as things currently stand just like `close()` this should have the possibility of adding 2 transfers to allow challenging in the case of the counterparty lying and closing with an older transaction state on their part.

### `close(our_transfer, their_transfer)`
Allows closing a bidirectional channel by presenting the latest transactions from both participants. 
The function should also:
    - check that `our_transfer` comes from the `msg.sender` and that it is a channel participant
    - check that `their_transfer` comes from the other participant

### `closeSingleTransfer(transfer)`
Allows closing a channel that was used only unidirectionally by presenting the latest transaction.

### `closeWithoutTransfer()`
Allows closing a channel that was unused.

### `disputeTransfer(their_transfer, our_transfer)`

After the counterparty has closed the channel this function gives you the ability to dispute the closing of the channel by presenting a more recent transfer for them (`their_transfer`). We also need the ability to present `our_transfer` there too in case the counterparty used `closeWithoutTransfer()` on the channel. This is to facilitate for [this](https://github.com/raiden-network/raiden/pull/276#issuecomment-264309757) scenario where `closeWithoutTransfer()` is called while transfers have happened both ways in a single-funded channel.

Having a `disputeTransfer(their_transfer)` only during the above scenario would result in a failure at settling because of the an insufficient netted balance for the transfer and the deposit inside the contract would not be enough to do the token transfer.

Please present your ideas on what our `Target Channel Closing Functions` should be.

**Comment by konradkonrad** [comment]
I may be terribly off her, but I want to reiterate on what I wrote on #276:

Before I dive into the details, here are the preconditions to all my reflections:
1) a channel consists of two channel-end states
2) the state changes to a channel-end state are *received* transfers
3) each channel-end has a **strictly increasing** balance, that is, at any later state, the end-state's balance can only be higher
4) at settlement, the payout is calculated by netting the two channel end states and calculate an according final balance for the two ends

So:
I do not understand why any valid dispute should be allowed to contain `our_transfer` (i.e. a self-signed message). If we open up disputes to contain self-signed messages, then disputes will likely be never settled. Allowing self-signed messages allows manipulating the state of the other end.

Furthermore, I believe that containing `our_transfer` in the `close(our_transfer, their_transfer)` function is **only** a courtesy shortcut of saving the channel partner an on-chain transaction where they must provide their latest received transfer. I think the more generic name here leads to confusion as `close(our, their)` is actually a special case and the default case is `closeSingleTransfer(their_transfer)`.

I believe the default case for closing is this:
1) Alice writes her latest *received* balance to her channel end state.
2) Bob writes his latest *received* balance to his channel end state.
3) net balance is calculated and payed out from the overall deposits.

As an optimization, we allow Alice to provide her latest transfer **sent** to Bob, when calling `close(alices_transfer, bobs_transfer)`. If she does not lie about `alices_transfer`, then Bob does not need to write his own state himself. If she lies, he can call `disputeTransfer(alices_transfer)` in order to prove that he received a later (signed) state change for his channel-end state.

`closeWithoutTransfer()` should be only a special case for `closeSingleTransfer(None)`, which allows a participant to signal the channel that no transfer was **received**. By writing this state, the calling participant, say Alice, agrees that her channel end state balance was **never increased**. Now the other participant, Bob, is free to prove to the contract whatever balance he has received (and signed!) from Alice. After netting, the contract should pay out as much as Alice signed (up to the overall deposit).

Note, that a mismatch between overall deposit and the provided *received* balances can always happen, since either party can freely chose not to provide the latest (ever increasing) channel-end state to the contract, when closing. But: no party should ever be allowed to write updates to the other ends.

**Comment by LefterisJP** [comment]
Please note that what I wrote in the issue's desription is the current state of the contract which I also think is wrong and needs rework. Thanks for your points @konradkonrad, will have to read them carefully.

**Comment by LefterisJP** [comment]
After reading @konradkonrad's comments and also speaking to him in person I think that in order to reach the required protocol state we need to agree on the following:

1. When closing a channel participant should provide the latest transfer he has received.
2. By closing a channel, the closing party also agrees that this is the latest transfer he received from their partner and acknowledged that **they will not be able** to dispute that in the future. 
3. As a courtesy the closing party can also include the latest transfer they sent to their partner.
4. If (3) has not happened the partner should call `updateTransfer()` to show to the channel the latest transfer they have received from the closing party.
5. After (3) or (4) the channel can be settled. Settling should *first* pay out the party that did not close the channel and only if there is anything remaining should they pay out the rest to the closing party. With such a strategy we can be sure that a [scenario](https://github.com/raiden-network/raiden/pull/276#issuecomment-264309757) where the closing party tries to cheat by closing with an older state, or with no state gets punished for doing so.


If we are in ageement that the above 5 points constitute the general closing/settlement strategy I would like to proceed in [my PR](https://github.com/raiden-network/raiden/pull/276) by:

1. Updating documentation to explain the closing strategies and what they mean as we decide here.
2. Making `updateTransfer()` accept only 1 argument as before but with the rules we agree here.
3. Changing the `settle()` function so that it always pays the non-closing party first and only if there is 
    funds remaining pay out the other party.

**Comment by LefterisJP** [comment]
Closed by #276
