### ISSUE TITLE
Create Minimal JS/HTML User Interface

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#285]
Create a minimal user interface using javascript and HTML. Its goal should be to allow users to access and use Raiden via a simple interface which would expose most of the API through a GUI.

**Comment by heikoheiko** [comment]
@ezdac can something from the IoT prototype be reused? it had a nice UI and already accessed the API, right. Should max be part of the project? Is there a dependency on the API?

**Comment by ezdac** [comment]
from the IoT-Demo, only the frontend-templates could be reused partially.
Since the demo was in-app raiden, we only posted events from the IoT-nodes via http-requests to the UI-server.
https://github.com/ezdac/iot-prototype/blob/raiden/frontend/app.py

The important dependencies in the API that aren't implemented yet would be:
- the actual REST-endpoints and grammar
- responses for the method-calls that provide some success information 
- push events 

Please see the comments in #10

**Comment by ezdac** [comment]
From the UI a user should be able to:

- Manually open, close, settle(?) and deposit to channels
- Inspect events for incoming transfers, opened channels

Convenience functionality:
- name addresses manually for better referencing
- have some tokens of the mainchain in an xml (mapping address->name) for referencing

**Comment by agatsoh** [comment]
So According to our discussion:

In the UI we would be having two modes for visualizing the state of the raiden node and performing operations on them. We assume that most of the functions in the https://github.com/raiden-network/raiden/blob/master/raiden/raiden_service.py#L327 RaidenAPI class have been exposed along with lots of getter functions plus events that we need to visualize the current state of the user in raiden.

a. Standard Mode
1. In this mode we assume that all the channels have been opened, the deposits have been made and the user can see all this in the UI. 
2. The user simply does a transfer by selecting the asset address, amount, partner address and  does the transfer.
3. User can see how much amount he has transferred to which user in the past and what is the current state.
4. User can settle the channel or close the channel.

b. Advanced Mode
1. This is for the advanced users where users get opportunity to open channels, deposit amount an amount in the channels,  along with closing, settling the channels.
2. User should be able to register endpoint.

All these points are up for discussion and improvement.

**Comment by ezdac** [comment]
### Considering getters and events:

- retrieving information from the blockchain can be implemented with a getter method that gets called on UI-opening, since this information is global and permanently stored on the BC
- information like recent transfers and the success of them should only be built out of the emitted events inside the client and will not be available for retrieval from the API (for now?)

@LefterisJP *Question* - does the follwing hold true?

- only transfer-events and the channel-events (BC) should be used to build all information
- it is feasable that the node puts all events since it's instantiation in a queue and emits those once the client connects?

This is based on the assumption, that a raiden node is online *permanently*

**Problem**: on a reconnect the UI-client cannot retrieve this information again - but we still want to be able to at least get the current balance-state of channels

**Comment by jisaac89** [comment]
If you guys still need help with the front end, let me know. Recommend a combination of react, typescript and mobx.

**Comment by LefterisJP** [comment]
The [MVP user stories](https://github.com/raiden-network/raiden/wiki/MVP-User-Stories) should provide a rudimentary spec for what the UI should do.

**Comment by andrevmatos** [comment]
It is already working quite nicely. Here's a small list of current working or in-development features:

- register new token
- view own balances with each token
- join/create a new network
- open a channel with specific partner/token
- deposit channel
- transfer channel
- close channel
- settle channel
- (wip) view events stream for each kind of event
