### ISSUE TITLE
cannot start raiden-network 0.15.0

### ISSUE THREAD

**Issue by Giulio2002** [raiden-network/raiden#2915]
when i try to start raiden using ropsten testnet, raiden tells me that the ethereum network differs

![screenshot_20181028_142338](https://user-images.githubusercontent.com/29233688/47616498-d579bf00-dabd-11e8-97d7-e5462e0aaded.png)

if i try to start raiden using mainnet i get another error

![screenshot_20181028_142644](https://user-images.githubusercontent.com/29233688/47616523-2ab5d080-dabe-11e8-82f1-fe7e900159f0.png)

i run raiden on:
* Ubuntu 18.04( that uses plasma as desktop environment)
* Linux 4.15.0-36-generic

**Comment by LefterisJP** [comment]
Hello @Giulio2002.

This is because in anticipation of the mainnet release the mainnet configuration is now the default. If you want to use raiden on Ropsten you should specifically set: `--network-id ropsten` and then `--environment-type development` if you want to use the ropsten token network registry that does not have a token registration limit.

**Comment by Giulio2002** [comment]
Thank you very much for your help.
i suggest to add this into the releases notes.
