### ISSUE TITLE
Client crashes after channels settle

### ISSUE THREAD

**Issue by kelsos** [raiden-network/raiden#2932]
I was testing with the `raiden-v0.15.1.dev6+g14cba904-linux` binary on kovan. At some point I decided to leave all the networks and settle all my channels. I had all my nodes online and waited for the all the channels to settle.

As soon as all the channels settled and started disappearing from the webui, one of the nodes crashed. After the crash the node started crashing on start with a different message that seemed similar to the one described by Cosmin on #2931.

Since I couldn't start the client for that account. I removed the database for this specific account. (all the channels were settled before it crashed but if you think this might be somehow a cause for the issue I will give it another try).

After this I started all my nodes and started opening channels in an attempt to get the channels stuck. I somehow got one of the channels out of sync for mediated transfers, but I wanted to try once again the scenario to ensure that this was not a coincidence). So I started leaving the network on all of my nodes
and waited for all my channels to settle.

As soon as all of my channels settled 2 out of the 5 clients running crashed again. 

After this, these two nodes would crash each time I would attempt to start them. You can find the original crash message and the restart crash message for both the nodes on the logs logs [here](https://gist.github.com/kelsos/324809e7f3a15d18e831d99560c01e8f#file-0xc52952ebad56f2c5e5b42bb881481ae27d036475-log) and the databases [here](https://drive.google.com/open?id=13FY_-WtkeFIg_jx43EX-cYY-J-WTvMNa)

**Comment by kelsos** [comment]
I managed to reproduce it again on 8a305fee259a0c5688b51dd06e197a4a74a307fe so it seems that the issue still exists on master.

**Comment by kelsos** [comment]
I will try to see if I can create a scenario for the scenario runner that replicates the issue.

**Comment by LefterisJP** [comment]
> I managed to reproduce it again on 8a305fe so it seems that the issue still exists on master.

Yes we did not address this issue. It definitely still exists. We need to find a reproducible way to test it and then fix it.

**Comment by LefterisJP** [comment]
Full logs given to me by @kelsos 

`0x60FFe4daDE358246C49C4A16bB5b430d333B5Ce9`: https://gist.github.com/LefterisJP/ad86d221e4cacb122c62a19cc703fa81

`0xc52952ebad56f2c5e5b42bb881481ae27d036475`:  https://gist.github.com/LefterisJP/a2611a177d674c1e4185b9e2ed02c29a

**Comment by kelsos** [comment]
Here are the logs of one of the crashed nodes, of the tests today.

https://gist.github.com/kelsos/00ea38174c6dfc8885df8793b6756700

**Comment by LefterisJP** [comment]
So it seems that what happens is that once a channel [receives](https://github.com/raiden-network/raiden/blob/11c226c9183a8ebfe76cfb2ae73a8b99d65cec04/raiden/transfer/token_network.py#L170) a BatchUnlock for a valid channel it will subdispatch it down to the [channel](https://github.com/raiden-network/raiden/blob/11c226c9183a8ebfe76cfb2ae73a8b99d65cec04/raiden/transfer/channel.py#L2068) state machine and since we were the participant, the channel state is [ending](https://github.com/raiden-network/raiden/blob/11c226c9183a8ebfe76cfb2ae73a8b99d65cec04/raiden/transfer/channel.py#L2079) and then as a result of that we [delete](https://github.com/raiden-network/raiden/blob/11c226c9183a8ebfe76cfb2ae73a8b99d65cec04/raiden/transfer/token_network.py#L204) the channel from the channel maps.

Once that is done the problem can manifest in a few different parts of the code by crashing since we iterate the transfers_pairs and we don't delete it from there.

1. Whenever we receive a new block and [handle](https://github.com/raiden-network/raiden/blob/c22a189589c66f767fdc7d992d4d1cdb1963d3bd/raiden/transfer/mediated_transfer/mediator.py#L1054) it at the first function there is an [asserion](https://github.com/raiden-network/raiden/blob/c22a189589c66f767fdc7d992d4d1cdb1963d3bd/raiden/transfer/mediated_transfer/mediator.py#L853)
2. Whenever we receive a new block at `events_for_onchain_secretreveal_if_dangerzone()` there is an [iteration](https://github.com/raiden-network/raiden/blob/c22a189589c66f767fdc7d992d4d1cdb1963d3bd/raiden/transfer/mediated_transfer/mediator.py#L732) of transfers_pair which asserts inside `get_payer_channel()`.
    This is where Kelsos' node crashed. What I don't understand is why did it not already crash at (1).
3. Kelsos also reported a crash [above](https://github.com/raiden-network/raiden/issues/2932#issuecomment-437929821) where inside [clear_if_finalized](https://github.com/raiden-network/raiden/issues/2932#issuecomment-437929821) there is a key error due to the same reason (channel identifier not in the channel map) [here](https://github.com/raiden-network/raiden/blob/c22a189589c66f767fdc7d992d4d1cdb1963d3bd/raiden/transfer/mediated_transfer/mediator.py#L267)

I suppose the solution is to delete the transfer pair once a channel has been unlocked an completely removed from the channel map.

**Comment by kelsos** [comment]
It seems that I accidentally pasted the `0x60FFe4` logs for `0xc52952` too. If you check the full logs for `0xc52952` you can definitely see that the assertion error is logged just before the node stopped because of the crash.
```
2018-10-30 15:34:04 [error    ] Runnable subtask died!         [raiden.utils.runnable] exc=AssertionError("Couldn't find channel for channel_id: 55",) running=True subtask=<Greenlet "AlarmTask|Greenlet-2" at 0x7fdc3c1cd648: <bound method AlarmTask._run of <raiden.tasks.AlarmTask object at 0x7fdc3b2b13c8>>> this=<RaidenService c52952eb>
```

In all of my tests usually there was one node crashing with the assertion error and another node crashing with a different error. Today too, two of the three nodes that crashed, crashed with the sssertion error and one with the crash I posted above.

**Comment by LefterisJP** [comment]
This is also a critical bug as once it occurs we are going to be stuck in a restart/crash loop due and can no longer use the client.
