### ISSUE TITLE
Invalid secret request keeps following valid one from being processed

### ISSUE THREAD

**Issue by jomuel** [raiden-network/raiden#3001]
Another fuzz test finding, see `test_failing_path_4` in the open fuzz testing pr (#2887):

`ReceiveSecretRequest` is not processed if an invalid secret request for the same transfer happened before.

**Comment by palango** [comment]
A short walkthrough of the issue that @jomuel found:

* When the initiator receives a `ReceiveSecretRequest` it calls the initiator to handle it:
https://github.com/raiden-network/raiden/blob/c22a189589c66f767fdc7d992d4d1cdb1963d3bd/raiden/transfer/mediated_transfer/initiator_manager.py#L308-L317

* The initiator checks if the request if valid, and if not returns `(None, [EventPaymentSentFailed(...)]):
https://github.com/raiden-network/raiden/blob/c22a189589c66f767fdc7d992d4d1cdb1963d3bd/raiden/transfer/mediated_transfer/initiator.py#L273-L281

* This in turn is handles in the node and the task gets removed from the payment mapping:
https://github.com/raiden-network/raiden/blob/c22a189589c66f767fdc7d992d4d1cdb1963d3bd/raiden/transfer/node.py#L204-L205


My question is how this should be handled:
1. After a invalid request all subsequent `ReceiveSecretRequest` should be ignored
2. Allow a certain number of `ReceiveSecretRequest`s before invalidating the task (or let it run until the payment times out

**Comment by hackaugusto** [comment]
The rationale here is, since the message is authenticated, we know it's target who sent the message, if he sent an invalid `SecretRequest` we do *not* assume it's a bug, but we assume it is an attack, therefore we drop the payment completely.

I think this is a bug, because in the past that would be fine, we had no `RemoveExpiredLock`, with the introduction of that message, we need the initiator task to be living to remove the lock, otherwise we are going to lose capacity. Note, however, that this should not manifest itself as a synchronization (from what I see in your description)

**Comment by palango** [comment]
> So, in short, my opinion is that we should reject subsequent invalid secret requests.

Ok, so then there is nothing to do here. If the `ReceiveSecretRequest` is invalid it gets removed from the payment mapping and all subsequent ones will be ignored.

**Comment by palango** [comment]
I misinterpret Augustos second comment, the payment task should not be deleted as there might still be locks.

**Comment by jomuel** [comment]
Meanwhile I removed `test_failing_path_4`, and I want to keep it that way since it does not test for the bug @hackaugusto described. The behaviour observed in `test_failing_path_4` was correct and is now tested for in the initiator fuzz test.
