### ISSUE TITLE
Mypy-ify initiator.py

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3034]
## Problem Definition

This is part of work to make the state machine type-checkable to have one additional tool that will help us find bugs. 

## Task

Add types to `initiator.py` and then run mypy on the file: `mypy raiden/transfer/mediated_transfer/initiator.py --ignore-missing-imports` and fix any problems that may be found.  No need to go in other files, we will do the mypification file-by file.

**Comment by karlb** [comment]
> No need to go in other files, we will do the mypification file-by file.

@LefterisJP: Does this mean I should fix the errors in a shallow way for now, e.g. casting an `initator_state.transfer_description.target` from `Adress` into `TargetAdress` inside `initiator.py` instead of changing the declaration of `TransferDescriptionWithSecretState.target` to `TargetAddress` in `mediated_transfer/state.py`?
Or do you just mean "ignore errors from other files, but try to fix all problems at the source"?

**Comment by karlb** [comment]
So I've done the brute force approach and added typecasts: https://github.com/raiden-network/raiden/pull/3059 . Apparently, these are nearly the only type casts in the code base, which raises the question "Is this the wrong thing to do, or do most people just ignore all mypy errors?".

I know that avoiding casts is preferable when possible, but that would change type declarations in other parts of the code and thus create new warnings at other places. So I'd like at least some rough feedback first.

**Comment by LefterisJP** [comment]
@karlb 

> "Is this the wrong thing to do, or do most people just ignore all mypy errors?".

Most people ignore mypy errors -- which is something we are going to change.
