### ISSUE TITLE
type system improvements on fixed size datatypes and messages

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3051]
@andrevmatos [told me](https://github.com/raiden-network/raiden/pull/3049#issuecomment-439840082) he is implementing a PoC for a type system improvement.  I agreed to take up the PoC.  This issue keeps track of this.

**Comment by pirapira** [comment]
For now I'm waiting for @andrevmatos 's PoC, so assigning him on this issue.

**Comment by andrevmatos** [comment]
My improved types for Raiden: https://gist.github.com/andrevmatos/c51d73b536bca192404904664848319f
`int8.py` is the demo code, `sized.py` is the types implementation, `sized.pyi` is a shallow declaration compatible with `mypy`. Gives full safeguards for uint ranges and instantiation-time checks for `Address` and other `bytes` subtypes.
From there, we can go full OOP for all specific types and make proper use of `isinstance`/`issubtype` for everything, instead of `*_T` mixups.

**Comment by andrevmatos** [comment]
Additionally, allows better declaration/instrospection of types sizes with `len(type)`, which may/should be used as hints for binary serialization/sanitization/validation/packing/etc.

**Comment by LefterisJP** [comment]
@andrevmatos thank you for the gist. What are the runtime considerations as compared to the current types we have?

Also since types in python and mypy are still rather young could you point to any mature/well-developed python project that uses a similar type system as the one you propose in the gist?

**Comment by andrevmatos** [comment]
@LefterisJP closest I could find is the [Ethereum's HexBytes](https://github.com/ethereum/hexbytes/blob/master/hexbytes/main.py) module, which is used all over web3.py and other eth-* modules, AFAICS.
Notice we don't do heavy bytes handling, it's mostly passed around as values, so the wrapper classes shouldn't have relevant performance impact. Actually, it can even help get rid of those unneeded `pex` calls, as its `__repr__` is called only when/if the log is going to be printed.
About metaclass's `__getitem__` logic, it's inspired by stdlib's `typing` code, and shouldn't have performance impact either, as is used only at declaration time.
This sized type system came from my mind, I didn't see it anywhere, but in the end, it's not more than ol' python OOP, with explicit class hierarchy, as the `TargetAddress` example in my gist.

**Comment by pirapira** [comment]
I'll try to apply this implementation on our codebase.

**Comment by pirapira** [comment]
Waiting for #3079 to be merged.

**Comment by pirapira** [comment]
* [ ] also make sure `Secret` type is 32-byte long (the smart contracts only recognize 32-byte long secrets).  Related #3091.

**Comment by pirapira** [comment]
#3079 was merged.  Now I'll first remove `mypy` errors about `Address` type before continuing with this one.

**Comment by pirapira** [comment]
I tried replacing `typing.Address` with `sized.Address`.  I saw too many test failures.  I think it's better first to remove mypy errors.

**Comment by pirapira** [comment]
I'm dropping this while I'm taking over the smart contracts.

**Comment by hackaugusto** [comment]
this is done by our use of `to_canonical_address`

**Comment by andrevmatos** [comment]
Related, for reference: we have strict typing at compile/transpile time & validation at the edges at runtime, including sizes, with our `Int`, `UInt`, `HexString` & `Address` types in the [light-client typing system](https://github.com/raiden-network/light-client/blob/master/raiden-ts/src/utils/types.ts)
