### ISSUE TITLE
Some signatures are accepted by Raiden client but rejected by smart contracts

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3054]
I'm wondering if there is an attack with EIP-155 style chainID-aware signatures.

The Python codebase [seems to accept](https://github.com/raiden-network/raiden-libs/blob/master/raiden_libs/utils/signing.py#L102) signatures with `v == 37 or 38`.

The smart contract [doesn't seem to accept those](https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/contracts/lib/ECVerify.sol#L27).  v has to be 0, 1, 27 or 28.

So, can I create a BalanceProof or something that works with the Python core, but doesn't work with the TokenNetwork contract?  Is there a test about this?

**Comment by pirapira** [comment]
If a client believes a BalanceProof works, and the BalanceProof actually doesn't work onchain, that would be a problem.

**Comment by pirapira** [comment]
@hackaugusto @loredanacirstea which `v` values shall we accept?  {0,1} / {27, 28} / {37, 38} / {39, 40} / ... All of them?

{0, 1}: vanilla signature scheme.
{27, 28}: generic Ethereum signature (on all chains)
{37, 38}: Ethereum signature expected on chain_id 1.
{39, 40}: Ethereum signature expected on chain_id 2.
...

**Comment by LefterisJP** [comment]
@pirapira if it also involves a smart contract it's kind of hard to only unit test it -- because if you want a test that provides the same balance proof with `v=37` to both python and contracts then you need to deploy them. This is an integration test.

Alternative approach would be unit tests only here in Raiden for various `v` values, and unit tests for various `v` values in the smart contracts repository.

**Comment by andrevmatos** [comment]
I don't think it's a problem for Raiden, because the `v` value is set **on the signature** instead of on the data to be signed, so Raiden client can simply change `v` to whatever value is accepted by the smartcontract before submitting the transaction. This value is meant to only make a difference when calculating a **transaction signature/hash**, avoiding replay attacks between chains, but is trivial on message signatures. Of course, we still need to ensure the client, besides validating the `v` value, uses a valid one when eventually submitting it as a tx.

**Comment by andrevmatos** [comment]
For true replay protection on off-chain data signatures, the `chainId` **must** be inserted on the message to be hashed/signed, as done in [EIP712](https://eips.ethereum.org/EIPS/eip-712)'s `chainId` field of the `EIP712Domain` component of the to-be-signed data, or trivially added to our `eth_sign`'s/EIP191-version-byte-0x45 signatures by ensuring e.g. the first byte of the message (right after the length) is the chainId.

**Comment by pirapira** [comment]
I talked with @loredanacirstea and @hackaugusto , and his solution was, for Red Eyes,
* the Raiden client rejects signatures, if `v` isn't {27, 28}

But I noticed @andrevmatos 's solution is
* the Raiden client changes the `v` value when it talks to the smart contract.

I prefer outright rejecting because I like systems that fail on slightest weirdity.  Does this align with the team?

**Comment by LefterisJP** [comment]
> I prefer outright rejecting because I like systems that fail on slightest weirdity. Does this align with the team?

Yes outright rejecting sounds like a better approach.

**Comment by pirapira** [comment]
Alright!  Yes, anybody can change `v` so it's not security, but more like annoyance problem.  So I took out the security tag.

**Comment by LefterisJP** [comment]
Thanks for finding this out @pirapira. I would even argue this is a critical bug since it can indeed lead to loss of funds. Someone can have a customized client who uses different `v` values other than `27` or `28` and send them to their partner who will gladly accept them, while the smart contract won't accept them at settlement.
