### ISSUE TITLE
Codecov in Circle CI

### ISSUE THREAD

**Issue by luehrsFred** [raiden-network/raiden#3071]
As @konradkonrad  introduced for Travis in #3029 to fix #3020 codecov.io should be used in circle ci as well.

Before just copying, CircleCI should be tested if there is actually need for conditional execution of codecov. It might be the case that circle ci can then just speed up things and does not necessarily need to be conditional.

**Comment by luehrsFred** [comment]
#3020

**Comment by konradkonrad** [comment]
One take away from #3020 / #3029 was that incomplete test runs (because of partial testing set ups) lead to misleading coverage results on coveralls.
In more detail: if a travis test run skipped integration tests, the reported results would show a much lower coverage / a sharp drop in coverage. That was one of the reason here for the conditional full test run on nightlies.

**Comment by LefterisJP** [comment]
We should also perhaps consider switching to codecov.io instead of coveralls. We already use it in PFS now.

**Comment by rakanalh** [comment]
Edited the issue to integrate codecov instead of coversall.

**Comment by LefterisJP** [comment]
I changed the assignment since it's @jomuel handling circle stuff.
