### ISSUE TITLE
Complete Circle CI integration

### ISSUE THREAD

**Issue by luehrsFred** [raiden-network/raiden#3072]
## Abstract

This is an issue to gather issues to finalize Circle CI integration for full CI setup. 

## Backlog

- [x] CodeCov.io #3071 
- [x] mypy #1206
- [x] pytest time out #3073
- [ ] deployment #3266
- [x] add fuzz testing parallel to unit tests
- [ ] MacOS tests
- [ ] documentation about usage / tips / tricks
- [x] After Trial adapt resource classes
- [ ] split by single tests #3140

**Comment by LefterisJP** [comment]
@luehrsFred 

A hint. If you start in markdown with `- [ ] text` it will create a checkbox for you. Like this:

- [ ] This is a task to check

>  mypy #1206

Since Travis also does not have mypy yet I guess this can happen later after we have set up the basics.

> MacOS tests

In Travis we removed it due to speed concerns. If it slows us down even a tiny bit in Circle I would opt for making it optional (i.e. with a commit tag asking for OSX tests). The speed of a single PR's test runs is of paramount importance.

**Comment by luehrsFred** [comment]
> A hint. If you start in markdown with - [ ] text it will create a checkbox for you. Like this:

Of course.. Didn't check my syntax, my bad.

> MacOS tests

In Circle CI MacOs runs on a completely independent container. Since we have workflows in Circle now we could either let it run in a completely seperate workflow and mark it as not required for any PR (not 100% sure if this is possible) or we could also let the MacOS job run conditionally on a specific commit message (also feasible). Either way this is not set as high priority currently. I'm gonna take that into account and look for a way to run it as a "side test"

**Comment by luehrsFred** [comment]
#3137, #3127, #3140 is enough to move over to circle ci

**Comment by rakanalh** [comment]
I believe this is done since #3266 is merged.
