### ISSUE TITLE
Integrity of EnvelopeMessage (esp, something not in the balance proof)

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3082]
While discussion https://github.com/raiden-network/spec/pull/135#issuecomment-442115888, @konradkonrad asked a question, "shouldn't these `EnvelopeMessage`s contain two signatures?"  One signature should be on the balance proof being transferred (this signature will be useful onchain).  That protects only part of the message.  There should also be the other signature that protects the integrity of the whole message.

* [x] do we have one signature or two signatures on a `EnvelopeMessage`?
* [x] should we have two?  Does the transport layer provide enough integrity guarantees (@andrevmatos ?)

@loredanacirstea was also interested.

**Comment by LefterisJP** [comment]
> That protects only part of the message. There should also be the other signature that protects the integrity of the whole message.

That is arguably the most important part of the message which you also want to prove on-chain.

> do we have one signature or two signatures on a EnvelopeMessage?

Afaik we only have one, protecting the balance proof.

> should we have two?

Another question here would be to take the `EnvelopeMessage`s one by one and compare their packed data versus what is protected by the balance proof signature [here](https://github.com/raiden-network/raiden/blob/38971b372dafb3205cbd3df8cfc3306922a55eac/raiden/messages.py#L311).

```python
    def _data_to_sign(self) -> bytes:
        balance_hash = hash_balance_data(
            self.transferred_amount,
            self.locked_amount,
            self.locksroot,
        )
        balance_proof_packed = pack_balance_proof(
            nonce=self.nonce,
            balance_hash=balance_hash,
            additional_hash=self.message_hash,
            channel_identifier=self.channel_identifier,
            token_network_identifier=self.token_network_address,
            chain_id=self.chain_id,
        )
        return balance_proof_packed
```

So the following:

- Secret:
    - message_identifier
    - payment_identifier
    - secret

- LockedTransfer:
    - message_identifier
    - payment_identifier
    - recipient
    - lock (expiration and secrethash)
    - initiator
    - target
    - fee

- LockExpired:
    - message_identifier
    - recipient
    - secrethash

--

The `payment` identifier is not part of the protocol. It's on the application level on top of Raiden. Message identifier is just a random number used in the delivered/processed messages to signify which messages are delivered/processed. Perhaps we also use it in retry queues.

If a different `secret` or `secrethash` is used then the reveal secret and lock expired messages respectively will have no effect.

If the lock expiration is tampered with then the transfer may either take too long to expire or not be propagatable due to very low expiration.

If the `recipient`, `initiator`, `target` fields of a locked transfer is tampered with then the transfer may not be properly delivered.

If the `fee` field is tampered with then either the mediator will have no fees to gain or the fee will be too high that the transfer will fail. But this is for when we actually implement fees :)


> Does the transport layer provide enough integrity guarantees

The best people to answer this question would be @andrevmatos and @ulope but so far we have designed the offchain protocol with this assumption.

**Comment by konradkonrad** [comment]
Yes, I realized by following the history of `additional_hash` that I was mistaken about its purpose:
It is **not** a free field to add additional signed data by third party applications, but instead a generic way to sign the complete message: As we see, `additional_hash` is the hash of the `message_data` and hence leads to keeping the integrity of the other fields.
One could argue, that its naming is a bit too generic maybe...

Btw, thanks for the detailed explanation @LefterisJP :)

**Comment by LefterisJP** [comment]
>  but instead a generic way to sign the complete message

This is key. So if you want more data to protect with the signature the application should **additionally** hash them along with the message data.

**Comment by andrevmatos** [comment]
As stated by @LefterisJP and @konradkonrad , and also with some thoughts [here](https://github.com/raiden-network/raiden/issues/3083#issuecomment-442177975), `additional_hash` hashes the whole message. There's no risk of tampering in any field covered by it, as if it happens, the hash will be different, which will make the recovering of the signature return a completely different address and be dropped even in the transport, or in any of the above level (`sender` is calculated from the signature, so any tampering will mean a invalid sender on every level).
This hash effectively verify both integrity and authenticity of every field contained in it, as strongly as the balance proof data, with the _only difference of not being recomposed from scratch on the smart contracts_, instead passed already calculated by the client, saving a ton of gas on hashing and verifying values we don't actually use on-chain.
As stated in my linked comment, there's a lot of room for improvement in our [de]serialization code and removal of error-prone boilerplate in the `messages.py` code, but all values currently there are properly integrity-checked.

**Comment by andrevmatos** [comment]
IOW: looking at the code, you'll think `BalanceProof` is part of the other messages, and it is for [de]serialization purposes, but from signing/smartcontract perspective, actually the whole message is a member of the `BalanceProof`, signed, hashed and verified everywhere the same way as the later.

**Comment by pirapira** [comment]
Alright.  I'm convinced.  I'm trying to document what I learned here.  https://github.com/raiden-network/spec/pull/136
