### ISSUE TITLE
Attack vector: Partner can cause us to crash by manually doing blockchain unlock()

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3152]
## Problem Definition

After the [conversation](https://github.com/raiden-network/raiden/issues/3139#issuecomment-446502086) we had with @rakanalh in another issue I realized that we have an attack vector in the way `handle_contract_send_channelunlock()` operates.

In that comment I mentioned:

> I mean sure in theory the contract allows anyone to unlock but each channel participant only unlocks what he received from the partner

But the above assumes non-tampered clients and no manual blockchain transactions. If someone either changes his client or sends manual transaction the following may happen.

1. The channel gets settled. Ignoring `CONFIRMATION_BLOCKS` the partner can send an `unlock()` blockchain transaction with what he sent us. This would normally not be sent by the raiden client as the client waits for confirmation blocks and only sends unlocks for the partner state. But the partner has the data (merkle tree) and the contract allows anyone to call `unlock`.
2. If that transaction is mined in `settled_block` + `N` where `N < CONFIRMATION_BLOCKS`, then we will get our locked tokens out and the unlock data will be [removed](https://github.com/raiden-network/raiden-contracts/blob/ce4c328157eae5b8bc61202e00796301b44f318b/raiden_contracts/contracts/TokenNetwork.sol#L837) from the contract.
3. But since we are using a normal client our client will only process the `settle` at `settled_block` + `CONFIRMATION_BLOCKS`.
https://github.com/raiden-network/raiden/blob/8bb02c11dd863930a1f5dfbed0e417eec784d925/raiden/transfer/channel.py#L1722-L1735

4. So this will generate a `ContractSendChannelBatchUnlock` even though our partner already did the unlock manually ignoring the confirmation blocks. We don't get the `ContractReceiveChannelBatchUnlock` event in time since we would need to wait `CONFIRMATION_BLOCKS` to process it.

5. Then when we try to send the batch unlock both of the following will be false

https://github.com/raiden-network/raiden/blob/8bb02c11dd863930a1f5dfbed0e417eec784d925/raiden/raiden_event_handler.py#L331-L338

leading to an unrecoverable error here:

https://github.com/raiden-network/raiden/blob/8bb02c11dd863930a1f5dfbed0e417eec784d925/raiden/raiden_event_handler.py#L362-L371

and the client would crash.

## Task

This problem stems from one very fundamental flaw which we have already documented in https://github.com/raiden-network/raiden/issues/2885 but had said that we would push to the backlog since the races would rarely hit us in normal operation. The solution is the same as the one we started in 2885.

Unfortunately as this issue shows an adversary can take advantage of this and cause nodes to crash which is a rather critical problem. Also I think that other parts of the code may be vulnerable to same attack if we don't implement a consistent blockchain view. 

With that in mind I want to take 2885 out of the backlog and implement it along with this issue. There is already some WIP in this branch: https://github.com/hackaugusto/raiden/tree/explicit_blockhash by Augusto and myself. I would like to take it up and finish it.

EDIT: As per [this](https://github.com/raiden-network/raiden/issues/3152#issuecomment-446633182) comment there is still a special case where a consistent blockchain view will not solve this problem.

So this issue will also need to take into account the `state_change_identifier == 0` case.

**Comment by rakanalh** [comment]
The description makes sense. I have some comments on the solution.

The blockhash solution will resolve a problem which can happen when executing the two `detail_participant` calls here.

https://github.com/raiden-network/raiden/blob/eb03cc85ef1ca4d773e7c265e12b4fe0a5cf9ea3/raiden/network/proxies/token_network.py#L330-L338

However, in the case of this attack... the block containing the adversary's transaction calling the unlock would result in both of these two calls returning the same data (given that the block was mined before our node sent it's unlock call transaction). This returned data will contain zero-values for the locksroots which means that even calling the contract's unlock with the blockhash of the block at which unlock was called will return the same result (zero values).

Example:
-> Unlock by the adversary takes place at block 10 (hash: ABC)
-> We call the `detail_participant` with block_hash=ABC
-> Returned data is going to be the zero-values for both locksroots as the adversary called `unlock` for both channel participants.

I think the blockhash will result in parts of the problem and not completely. What we should do is prevent the client from crashing if the call to unlock was made by someone else. 

I think the other part of the solution would be to check the returned `locksroots` values from the contract `detail_participant` call, in case of a zero-value we know one of two things:
a. There weren't any pending transfers on our side to unlock in the first place (bug because unlock should have never been emitted from our node in the first place).
b. The unlock call was already made in our behalf by the partner (Presumed adversary)

**Comment by LefterisJP** [comment]
>  We call the detail_participant with block_hash=ABC

@rakanalh I don't think that the scenario you describe can happen if we have the consistent view of the blockchain implemented.

With that implemented we would enter [handle_contract_send_channel_unlock](https://github.com/raiden-network/raiden/blob/8bb02c11dd863930a1f5dfbed0e417eec784d925/raiden/raiden_event_handler.py#L303) with the blockhash of the settle block. So the view of the blockchain that this function would have would be before any unlocks happened even if they have already happened.

That would result in us wasting an on-chain transaction but at least we would not crash.

**Comment by rakanalh** [comment]
Ah ok... now i see your point now. I was under the impression that the blockhash will be for the block at which the unlock transaction was mined.

If that's the case then :+1:

**Comment by LefterisJP** [comment]
After a discussion with @konradkonrad in rocketchat he came up with very good point that there is a specific case where `state_change_identifier` can be 0 even if we got the consistent blockchain view. That is if the attacker somehow manages to get both the `settle` and the `unlock` transactions mined in the right order in the same blocks then we will still get to same problem.

So this case should be handled anyway and it should not crash and give a proper error message that someone else completed the transaction. Without the consistent blockchain view that someone else could also be us before a restart. See discussion [here](https://github.com/raiden-network/raiden/issues/3139#issuecomment-446581945)

If we got the consistent blockchain view the error message can be very specific and state that an someone (an attacker?) managed to send settle and unlock in the same block so channel is already unlocked.

**Comment by konradkonrad** [comment]
As I understand, this is not an attack, but a client bug:

> Anyone can unlock a transfer on behalf of a channel participant. unlock must be called after settleChannel because it needs the locksroot from the latest balance proof in order to guarantee that all locks have either been unlocked or have expired.

(see https://raiden-network-specification.readthedocs.io/en/latest/smart_contracts.html#smart-contract-functional-decomposition "Unlock lock")

In other words, the client needs to handle cases, where the unlock happened "behind the scenes" gracefully.

**Comment by LefterisJP** [comment]
It's a client bug that can be exploited through an attack. Wouldn't be seen in normal operation of the client as the code currently stands.

Exploiting a bug to crash your partner is an attack.
