### ISSUE TITLE
Extract server discovery and shared room discovery / creation into utility function

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#3291]
## Abstract

Sub-issue from #3243.
In the initial implementation the MS needs to be able to join a fully federated global room to receive balance proofs from Raiden clients.
Extract the server discovery / login mechanism and discovery room creation mechanism from the MatrixTransport into a utility function, this will provide a temporary solution to the MS until #3252 is implemented and the full MatrixTransport can be used by the MS.

## Tasks

- [ ] Extract server discovery, login
- [ ] Extract shared room creation 

## Time estimation

1 Week

**Comment by andrevmatos** [comment]
I think creation of the room should be quite easy, but this issue must also track filter receiving/sending logic for these _special_ rooms, since all send/receive logic holds certain assumptions about p2p architecture (e.g. `send_async` expects a peer address, receiving messages filters by invited-by peers). In this case, raiden transport should only send, not care about receiving, but some care must be put on this part as well
