### ISSUE TITLE
Convert most makefile targets into tox environments

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3341]
## Problem Definition

[Suggested](https://github.com/raiden-network/raiden/tree/test-review/ob-review#organisation-of-testing-activities) to us during our test review. This is probably a nitpick so I also put the "needs discussion" label.

Suggestion is to convert most of the makefile targets into tox environments - at least the ones that use Python tools and need some setup in a virtualenv anyway (like all the lint/test and documentation related targets). This might make this easier to digest to everyone involved.

**Comment by hackaugusto** [comment]
I think this is only a good idea if we remove the other options:

running the tests from setup.py
running the tests from make file
having custom scripts for travis/circleci

**Comment by ulope** [comment]
Oliver mentioned that tox has gained native parallelism support in the recent past. That alone could be reason enough to re-introduce it. 

We can't really use it on circle though since we use a lot of its native features (re-using workspaces between jobs, splitting tests based on previous timing data, etc.) to make it go fast.

**Comment by LefterisJP** [comment]
I don't think this is anything we need to spend time on right now. And in the interest of consolidating our testing plan I would say this should be closed.
