### ISSUE TITLE
Add docstrings to smart contracts

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#335]
Some of the smart contracts don't have docstrings. Is't mostly the *Contract.sol contracts that don't have any docstrings.

There are currently no docstrings in https://github.com/raiden-network/raiden/blob/master/raiden/smart_contracts/Registry.sol

https://github.com/raiden-network/raiden/blob/master/raiden/smart_contracts/ChannelManagerContract.sol

https://github.com/raiden-network/raiden/blob/master/raiden/smart_contracts/NettingChannelContract.sol

Furthermore `NettingChannelLibrary.sol` and `ChannelManagerLibrary.sol` could use a read through since there are a couple of undocumented functions.

**Comment by lsaether** [comment]
Hello, I am currently working on this. I am new to Solidity so this should be the best introduction for me into contributing to the project. Quick question-- do you want documentation on top of functions only or within the steps of that function as well? Are there guidelines posted somewhere that I should follow?

**Comment by LefterisJP** [comment]
Hello @lsaether. Welcome and thank you for your interest in Raiden!

The docstrings should only be on the top of the function. As an example you can look [here](https://github.com/raiden-network/raiden/blob/add63d467d87972b122760fc9b92c5137e5f8c5a/raiden/smart_contracts/NettingChannelLibrary.sol#L190) for the docstring of the `close()` function.

Note that in some functions you may see also the type of the docstring documented like [here](https://github.com/raiden-network/raiden/blob/add63d467d87972b122760fc9b92c5137e5f8c5a/raiden/smart_contracts/NettingChannelLibrary.sol#L84). Please do not copy this style. 
`@param caller_address (address) the address of the invoker of the function`
should be
`@param caller_address  the address of the invoker of the function`
That is because the type of the parameter does not need to be documented as it's already part of the code.

We will fix that shortly :)

**Comment by czepluch** [comment]
Not a lot of work left in this one. #375 Takes care of https://github.com/raiden-network/raiden/blob/master/raiden/smart_contracts/ChannelManagerContract.sol and https://github.com/raiden-network/raiden/blob/master/raiden/smart_contracts/Registry.sol

Only `NettingChannelContract.sol` that needs some work

**Comment by adrianbrink** [comment]
Should we assign ```work_in_progress``` or even close it?

**Comment by czepluch** [comment]
We can close it once your PR is merged
