### ISSUE TITLE
Use `_` for unused names consistently in the codebase.

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3352]
## Problem Definition

[Suggested](https://github.com/raiden-network/raiden/tree/test-review/ob-review#python-use-_-for-unused-names) to us during our test review. 

## Suggestion

We are not consistent through the codebase for the usage of `_` for unused arguments. There are quite a few places where e.g. `**kwargs` are collected in a function head but are not used. The resulting linter warning is silenced with `# pylint: disable=unused-argument`. This should not be necessary if using that convention also in those cases - e.g. **_. Then the linter does not need to be silenced either which results in less visual noise in the code.

**Comment by hackaugusto** [comment]
from what I gathered half of these are because of click, I'm not sure if we can remove the kwargs from there:

https://github.com/raiden-network/raiden/blob/ad3d0ad6affa4fab0c7b27fa97fa624eb7dea149/raiden/ui/cli.py#L450-L456

The other half is because the name matters, either we are overwriting a method and the argument name must be kept for compatibility, even if it's not used:

https://github.com/raiden-network/raiden/blob/a5e326b81635e2aac1967a645cd8b8283ba5e1de/raiden/network/throttle.py#L16-L17

Or we are using a fixture by name:

https://github.com/raiden-network/raiden/blob/a5e326b81635e2aac1967a645cd8b8283ba5e1de/raiden/tests/integration/long_running/test_stress.py#L347-L361

I have not checked the other `pylint: disable`

**Comment by ulope** [comment]
> from what I gathered half of these are because of click, I'm not sure if we can remove the kwargs from there:

Those are unnecessary. Mini PR to remove them: #3367

**Comment by LefterisJP** [comment]
I would close this. Can't avoid the unused argument warning with fixtures as arguments.
