### ISSUE TITLE
Generate Arm binaries

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#3401]
## Abstract

For Raiden usage in IoT (see Raspberry PI) it would be nice to also provide ARM binaries. This has been requested by Raiden users. cc @stefanbenten

## Task

- [ ] Modify the CircleCI deploy jobs to also create ARM binaries and include them as artifacts in the releases.

**Comment by ulope** [comment]
I made some experiments in that directions a while back.

Brain dump:
- PyInstaller and all dependencies work fine.
- Depending on the hardware and storage the single file bundle can be slowish to start due to having to extract the bundle into a temp folder
- There are multiple popular versions of the ARM architecture, which means we probably will need to provide multiple builds:
  - armv6: 32bit (RasPi 1, RasPi Zero (W)) - maybe not relevant due to being oldish and slow
  - armv7: 32bit (RasPi 2, many many other SBCs)
  - armv8 / aarch64: 64bit (RasPi 3, also many other SBCs)
- Building requirements, either:
  - Build on native hardware (needs a provider that has arm VPS / servers)
  - Use emulation. Keywords:
    - binfmt_misc
    - qemu-user
    - Patched qemu to run inside docker without kernel support
- [Docker has support for multi platform images](https://blog.docker.com/2017/09/docker-official-images-now-multi-platform/)


Whoever is going to work on this, if you need pointers: ask me.

**Comment by ulope** [comment]
Discussed this with @luehrsFred on Friday who will be working on it.

We've agreed on the simplest and fastest to implement solution:
- Use a remote docker daemon hosted on an ARM VPS / server
- Connect from CircleCI via SSH port forwarding or similar to that docker daemon

Pros:
- No need to modify the build scripts etc.
- Only minimal additional configuration on CircleCI needed

Cons:
- We need to run one ARM server for every architecture variant we want to support (not a big issue though, since most providers have pre-configured docker images)

**Comment by stefanbenten** [comment]
That sounds awesome! Looking forward to the release builds!

**Comment by stefanbenten** [comment]
Thanks for getting that done that quickly!
Will test the latest arm builds shortly!
