### ISSUE TITLE
Crash on restart of killing node while doing transfers

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#3432]
### Problem definition
I was doing some testing on the latest RC (raiden-v0.100.2rc5.dev3+ge83bbd4c.d20190206-linux). I was running a script doing mediated transfers and I killed the initiator node while doing so. Upon restart my node crashed. 

See logs here: https://gist.github.com/czepluch/300450d74d0434c40c84024c7e2f0e1a

And console output: https://gist.github.com/czepluch/bfa359b29c9883721b05eb85e7560e29

**Comment by LefterisJP** [comment]
Probably this is related to https://github.com/raiden-network/raiden/issues/3121 and could be the reason why #3121 happened. Not sure if this was a restart.

**Comment by rakanalh** [comment]
The `KeyError` seems to happen because the initiator was restarted during a transfer cycle. Once the initiator came back online, it proceeded with completing this cycle and the transfer was completed successfully. However, `raiden.targets_to_identifiers_to_statuses` was empty after restart because it's not re-populated with all the "initiator states" (pending transfers).
