### ISSUE TITLE
Pay PFS for route

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3461]
## Introduction

The PFS will have to be paid to provide a route for a certain transfer. 

## Requirements

- [x] Introduce a policy variable where the user can set the maximum amount required to be paid by client to the PFS.
- [x] Query the PFS for the latest IOU
- [x] Include the specified IOU structure that the PFS will accept as payment. More details on this can be [found here](https://raiden-network-specification.readthedocs.io/en/latest/service_contracts.html#oneton)
For now, we could use the above "Max amount" for testing until the PFS provides an endpoint with the pricing.
- [ ] Handle some specific IOU-related errors that the PFS might return, e.  g. that the IOU has already been cashed out or expires too soon.
- [ ] Update docs on pfs integration (new command line options and such)

~~## Open Questions:~~
**Note: Edit requirements based on answers below if additional tasks are required.**

~~1. Would this be a value on the maximum amount the client is willing to pay?~~
~~2. Does this value differ between an initiator asking for a route and a mediator mediating a transfer?~~
~~(assuming the PFS is called on every hop of the route)~~
~~3. What is the default value?~~

Related #216 

Expected: Mid march, 2019

**Comment by LefterisJP** [comment]
> A user policy is a variable that lives in `settings.py` for the user to modify to change the behaviour of Raiden and / or a value that raiden uses.

I understand policies as dynamic settings that can be dynamically changed in runtime. All values in `settings.py` are currently only set at the program's startup.

>     1. Would this be a value on the maximum amount the client is willing to pay

I guess maximum value per single PFS request.

>     2\. Does this value differ between an initiator asking for a route and a mediator mediating a transfer? (assuming the PFS is called on every hop of the route)

I don't see why it should. They both are requests to the PFS, and since they both ask the same thing, using the same endpoint they should be identical.

>     3\. What is the default value?

Good question. @palango ? I asked the same question in my comment [here](https://github.com/raiden-network/raiden/issues/3464#issuecomment-462514640) in issue #3464

**Comment by palango** [comment]
> * What is the default value?

We can set it arbitrarily for testing, one idea is to make the price query-able from the `/info` endpoint in the PFS.

**Comment by rakanalh** [comment]
Updated the issue to be about paying PFS

**Comment by rakanalh** [comment]
@palango The spec says this about client / PFS communication.

```
When requesting a route, the IOU is added as five separate arguments to the existing HTTP query params.
Field Name | Field Type | Description
-- | -- | --
sender | address |  
receiver | address |  
amount | uint256 |  
expiration_block | uint256 | last block in which the IOU can be claimed
signature | bytes | Signature over (`\x19Ethereum Signed Message:\n`, message_length, sender, receiver, amount, expiration_block) signed by sender's private key
```
However, the link to the [endpoint](https://raiden-network-specification.readthedocs.io/en/latest/pathfinding_service.html#arguments) does not show how we can send the above to the endpoint. Is there a missing parameter from the endpoint?

**Comment by jomuel** [comment]
The pfs might report several errors after requests to the `/paths` endpoint. Proposal to treat them:

In general, make one more try and raise a `ServiceRequestFailed` if that fails again. The following errors will just immediately raise a `ServiceRequestFailed`:
2107 DEPOSIT_TOO_LOW, 2102 WRONG_IOU_RECIPIENT as we have currently have no way to fix them when we happen
20xx as they are not IOU-related and might be treated seperately later.

Policy for second attempts:

2100 BAD_IOU (generic)
- we cannot tell what went wrong, so just try the same procedure (Query IOU, send a query to `/paths` based on it) on one more time.

2101 MISSING_IOU
- should never happen, as we always add an iou to the request. Just try the same procedure one more time.

2103 IOU_EXPIRED_TOO_EARLY, 2105 IOU_ALREADY_CLAIMED
- requires a new iou, so build one and try to query again with it.

2104 INSUFFICIENT_SERVICE_PAYMENT
- try again with the `pathfinding_max_fee` in the configuration if we were previously below it; otherwise raise a `ServiceRequestFailed`

2106 USE_THIS_IOU
- meaning there is an iou already and the pfs wants us to update it rather than start a new one. This might happen due to overlapping requests, so just try the procedure again.
