### ISSUE TITLE
User Policy - Raiden needs to deposit RDN tokens in UDC

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3465]
To be able to pay services.

The client also needs to have a user policy to define the minimum threshold to reach before invoking a new deposit.

Expected: End of Feb, 2019.

**Comment by LefterisJP** [comment]
Hmmm should that be part of the client functionality?

Can't this also happen outside of the client?
Before the user starts to operate Raiden they can do a deposit to the UDC manually.

I would rather not have to perform automatic deposits to the UDC (which should not be frequent anyway) from the Raiden client.

### Why I don't think this is a good idea

- UDC deposits would be big and not frequent. That's the whole point of the UDC. So having Raiden manage them has little benefit.
- I, as a user, would not trust the raiden client to manage an ether account with a big amount of ETH. Instead I would just refill the raiden client account with ETH whenever a new deposit is needed.

The " refill the raiden client account with ETH whenever a new deposit is needed." does not make sense .. since users can just do direct deposits manually on-chain without bothering with a third application like the Raiden client.

### What should we do then

1. Easier solution is to leave it up to the user to deposit to the UDC once, and perhaps have the raiden client let them know when it's running low so that they refill it if needed.
2. A more involved solution would be to offer some other kind of nicer user onboarding-UI external to the Raiden client which would offer a nice interface over the on-chain transaction. Speaking to MyCrypto for this could work

**Comment by palango** [comment]
For me this depends about which time frames we're talking.
- If we're talking short term and mostly us testing I agree that one can deposit by hand.
- If we're looking at the bigger picture, then I think this should be (semi-)automatic to make it more user friendly. But the whole onboarding story needs more work.

**Comment by LefterisJP** [comment]
>     * If we're looking at the bigger picture, then I think this should be (semi-)automatic to make it more user friendly. But the whole onboarding story needs more work.

As I said in my response above I don't think this should happen in the logic of the raiden client side for the reasons stated there.

But yes I would say let's just go manually now -- and if/when we target easier on-boarding spend some time thinking on this.

**Comment by rakanalh** [comment]
I'll scope this out since we go for the manual approach for now.
