### ISSUE TITLE
add setter methods to the RaidenAPI

### ISSUE THREAD

**Issue by ezdac** [raiden-network/raiden#356]
this is a split-up from #10, as stated in #325 

These are mainly setter methods for a Client to request a state-update inside the node.

**add following methods to the `raiden-service.RaidenAPI`**:

- `set_endpoint(endpoint, signature)`:
Set an `address - > endpoint` mapping in raiden's discovery to register a new node.
Returns an result-object (with fields: `success`, `data`), where data may be an Exception or empty.
This will serve for light-clients to register their endpoint without having to know the discovery.

**considerations for the general interface of state updating methods**

let the caller decide if the called method should be executed asynchronously or waiting
(== `gevent.AsyncResult.wait()`)

- `asset_swap(..., wait=<bool>)`
- `expect_asset_swap(..., wait=<bool>)`
- `transfer(..., wait=<bool>)`

The asynchronous method should be the default option,
but when calling via REST the waiting method should be default. 
That's because in e.g. JavaScript one can work easily with Promises.

**Methods that interact with the blockchain are blocking at the time being!**
(`deposit()`, `close()`, `settle()`, `open()`)
*Since the asynchronous methods are only important for a raiden python module, the implementation for an asynchronous option for those methods should be postponed to the point where the python module will get implemented.*

**Comment by LefterisJP** [comment]
@ezdac This issue sounds like it has to do with python library API and as discussed this is not something we are currently interested for the MVP. Is that correct or am I missing something?

Perhaps the `set_endpoint()` method could be added to the CLI interface as you ask for convenience but this has nothing to do with the Restful webserver API.

**Comment by hackaugusto** [comment]
I didn't understand the behavior of `set_endpoint`.

- Is it setting the endpoint of the local node? The local endpoint depends on the UDP port configuration, so this doesnt make much sense to me.
- Is it adding an endpoint for a different node? IMO this should be part of the discovery and not the api.

Also, for the method signatures. I prefer the use of the sufix `_async` as a documentation to the caller, that the function returns an AsyncResult object, instead of adding a boolean flag, this is more consistent with the current base and has the same benefits.

*If* we do add a `wait` variable, we should follow `gevent` and accept a float or None, to specify for how long the call should block.

**Comment by LefterisJP** [comment]
No longer relevant to the API and MVP milestone.
