### ISSUE TITLE
Use an actual blockhash instead of `latest`

### ISSUE THREAD

**Issue by rakanalh** [raiden-network/raiden#3619]
## Introduction

After having merged https://github.com/raiden-network/raiden/issues/2885, some tests still pass the `block_identifier` parameter as `latest` which might cause flakiness in some tests and/or other synchronization issues.

https://github.com/raiden-network/raiden/blob/2dd6224baa9e40b63703acfb04dd62f0376e247d/raiden/tests/integration/fixtures/smartcontracts.py#L59-L69

## TODO
- [ ] Replace all usage of `latest` with an valid blockhash from the running blockchain client.

**Comment by hackaugusto** [comment]
To prevent future errors we should change the proxies to **reject** `latest` as a value for `given_block_identifier`, this will make the offending tests fail and we can then fix them.

**Comment by hackaugusto** [comment]
We did this change, and turns out that using the blockhash was a bad idea. None of the JSON RPC methods support the blockchash, and web3 silently converts the blockhash to a blocknumber, which led to a two fold increase in the number of RPC requests.

I'm closing this since the change is implemented, but the goal is to introduce a new type to represent a block, with the block hash and block number, do the RPC requests using the block number, and use the block hash to detect long reorgs
