### ISSUE TITLE
Transport has to incorperate invited peers private_room setting upon room creation

### ISSUE THREAD

**Issue by err508** [raiden-network/raiden#3696]
If two clients have for some reason different `_private_room` settings, the one which uses public rooms sends messages that are ignored by the other client. 
A client should have means to learn the `_private_room` setting of the channel partner and adapt to it.

**Comment by andrevmatos** [comment]
This was intentional. The idea is that `_private_room` is the same for all clients on a given blockchain: e.g. mainnet always require private rooms, while the testnets default to public rooms. If a user falls out of sync on this, it's only by setting the parameter by hand, and he knows what's doing (e.g. testing a self-hosted network).
