### ISSUE TITLE
Wormhole attack

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden#3758]
I attended Matteo Maffei's talk in Darmstadt on 2019-04-05.  He talked about an attack on Raiden called ["the wormhole attack"](https://eprint.iacr.org/2018/472.pdf).

## Summary

In a mediated transfer involving more than three hops, two mediators can steal the mediation fee from the other mediators in between.

## How the attack works (short version)

In a mediated transfer involving five nodes, `A --> B --> C --> D --> E`, after E reveals the secret to D, D misbehaves.  Instead of revealing the secret to C, D sends the secret to B.  C doesn't notice that the payment succeeded, and gets no fees.  B and D together earn the amount that C lost.

## How the attack works (long version)

![mediation](https://user-images.githubusercontent.com/44281/55712186-96498580-59ee-11e9-9d6c-7a9e5eee37cb.png)

1. A sends a LockedTransfer (103 tokens) to B
2. B sends a LockedTransfer (102 tokens) to C
3. C sends a LockedTransfer (101 tokens) to D
4. D sends a LockedTransfer (101 tokens) to E
5. E sends a SecretRequest to A
6. A sends a RevealSecret to E
7. E sends a RevealSecret to D
8. **D does not send a RevealSecret to C**.  Instead, D tells the secret to B in a private channel.
9. B sends a RevealSecret to A
10. Balance proofs are updated in A-->B and D-->E.
11. The other transfers B-->C-->D time out.

At the end,
* A pays 103 tokens, as intended.
* B receives 103 tokens but pays nothing.
* **C doesn't receive anything, instead of one token as a fee.**
* D pays 100 tokens.
* E receives 100 tokens, as intended.

**Now B and D together gain 3 tokens, instead of 2 tokens.**

## Impact

* RedEyes is not affectted.  Nobody expects mediation fees.
* Ithaca might be affected, if somebody curious enough pulls it off.

## Mitigation

* at least document the attack and warn the users
* maybe ban payments involving more than three hops?
* Implement the scheme presented in [Matteo's paper](https://eprint.iacr.org/2018/472.pdf)
    * This changes the smart contract as well as the offchain protocol.
    * Lightning people have addressed this, I heard?

**Comment by pirapira** [comment]
I'll read [Matteo's paper](https://eprint.iacr.org/2018/472.pdf).

**Comment by pirapira** [comment]
I had some discussions with @hackaugusto @rakanalh and @konradkonrad 

* opening many small nodes costs more than creating a big hub
* this attack can minimize the latency of payment
* as a mediator you always have the possibility that the payment doesn't succeed

**Comment by hackaugusto** [comment]
Here are some extend comments which came out from our discussion. I don't see why this would be exploited.

#### For a rational attacker, one that wants to make profit from the attack

Assuming normal operation and a honest operator: She may operate a hub and open as many channels with a single address as viable, increasing the node's connectivity. A transfer routed through this hub will be shorter, allowing the hub to increase it's mediation fees (effectively the hub gets paid the fees that would go for the other hops by shorting the route and increasing its price).

This attacks adds another dimension to the fee computation that allows one to hide higher fees, because instead of having a highly connect hub with a higher fee, the attacker controls multiple addresses, jumps over the route's inner hops, and takes the fees from the other nodes. This has the same end effect through a different means.

This happens because the fee is computed on a per channel basis, regardless of the number of hops in the path, by using multiple addresses instead of one the attacker may open channels in the network maximizing their distance, and exploit it to increase and hide the higher fees.

Exemplifying:

Consider the path `?-A-hops-A-?`, where both A nodes are controlled by the attacker, and ignoring the number and who are the hops before and after. Assuming constant fees without loss of generality,  the total fee the attacker gets paid is equal `len(hops) * x + x`. For the honest node `len(hops)` is 0 and `x` is high, for the attacker `len(hops)` is hopefully high and `x` can be small.

The rational attacker would just rely on the fact the PFS doesn't know it controls both nodes, and hope it uses more then one of its addresses in a route, the attacker would then *not* send the locked transfer to the inner hops, otherwise it would have an increased cost for the locked collateral, this assumes a rational player, which would not increase its own collateral cost. This means there are no damage to the network's capacity, it's just a silly way of having a higher fee schedule.

Possible fixes:
- Onion encryption can fix this, since the attacker would not know if itself is part of the path nor who is the target, being force to respect the PFS route, and assuming a rational attacker it has the incentive to unlock all of its tokens.
- Allow fee schedules based on the number of hops in the path (or preferably, the difference in length to the next smallest possible route). This however needs some thinking, it may leak multiple routes, be hard to enforce, and relies to much in the PFS.

#### For an attacker which trying to DoS the network

For a path `?-A1-hops-A2-?`, this allows the attacker to have the funds of `A1` and all `hops` locked until the lock's expiration. This can be seen as an amplification attack, where at the cost of a single channel `A1`, the attacker can lock tokens of `len(hops)`.

However, this is the same as an attacker controlling a single address, with a single channel, finding the longest route in the network, starting a transfer, and never revealing the secret. This can be fixed by performance metrics of a channel, where a badly performing channel is closed and the address is blacklisted.

**Comment by pirapira** [comment]
I see. The attack is a problem for a rational hop that thinks it might be surrounded by irrational attackers.  But irrational attackers can do worse things with a single node already [An attacker can make a payment and never reveal the secret](https://github.com/raiden-network/raiden/issues/3769).

**Comment by pirapira** [comment]
In case of onion routing,

> assuming a rational attacker it has the incentive to unlock all of its tokens.

Fees must be more expensive than the capital cost of locked collaterals.  So, a rational attacker would invoke the wormhole attack.

I agree that in source-routing, a rational attacker would not speak to the hops even.

**Comment by pirapira** [comment]
LightningNetwork side, things look like this: http://diyhpl.us/wiki/transcripts/stanford-blockchain-conference/2019/privacy-preserving-multi-hop-locks/ For them it's more complicated because they have to use the primitives available in Bitcoin script.

**Comment by LefterisJP** [comment]
So @hackaugusto if I understand correctly you are arguing that this attack is just an extended version of someone DOSing the network by making transfers but not revealing the secret which has the same end-effect to the network?

**Comment by pirapira** [comment]
@LefterisJP this attack = "making transfers but not revealing the secret" + "short-circuiting payments by skipping mediators in the middle".

Yes "making transfers but not revealing the secret" is DOS.

"short-circuiting payments by skipping mediators in the middle" is beneficial to the end-users (better latency).

**Comment by pirapira** [comment]
Doing https://github.com/raiden-network/raiden/issues/3771 first might be easier.

**Comment by pirapira** [comment]
But I realized that duplicating this issue in `raiden/docs` causes some maintenance loads.

**Comment by pirapira** [comment]
I'll write something about this in the document and close the issue.
