### ISSUE TITLE
Simplify queue serialization

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#3777]
## Abstract

The message queue serialization is unnecessarily dumping the `repr(QueueIdentifier)` into the state snapshot. 

## Motivation

This is a bit surprising and confusing, so we should probably remove the unnecessary extra key.

## Specification

Change the de/serialization functions to **and** write a data migration.

```python
def serialize_queueid_to_queue(data: typing.Dict):
    return [
        [queue_id, queue]
        for queue_id, queue in data.items()
    ]


def deserialize_queueid_to_queue(data: typing.Dict):
    return {
        queue_id: queue
        for queue_id, queue in data
    }
```

## Backwards Compatibility

This is backwards compatible with the protocol and smart contracts, and with the migration the storage is forward compatible with new clients

**Comment by rakanalh** [comment]
@hackaugusto The serialization after introducing dataclasses for `QueueIdentifier` was reworked here:
https://github.com/raiden-network/raiden/blob/4670be21117b070f55f0d3f73e8957240ab18b69/raiden/storage/serialization/fields.py#L57-L90

Does this satisfy the issue? if so, please feel free to close it. 
Otherwise, could you please elaborate on the alternative solution you have in mind?

**Comment by hackaugusto** [comment]
@rakanalh This is the line of code that I was talking about: https://github.com/raiden-network/raiden/commit/3397f36204a5985442f0735c419506954d44248c#diff-8b6687801f632fbd57e81eafca76487cR125 so the serialization of the queue itself, not the identifier.

**Comment by rakanalh** [comment]
`raiden/utils/serialization.py` module no longer exists and these serialize/deserialize functions were removed in favor of having specific fields in the `storage/serialization` module.

**Comment by rakanalh** [comment]
@hackaugusto and I agreed that this is to be closed.
