### ISSUE TITLE
Create a 'InitMediatedTransferTask' to compensate for nondeterministic paths

### ISSUE THREAD

**Issue by ezdac** [raiden-network/raiden#42]
As an initiator, the expiration of a transfer-lock is critical for a transaction to succeed but the path is not known beforehand.
The maximum valid lock-expiration is dependent on the settle_timeout of the first channel a node chooses for a MediatedTransfer - a very small initial lock-expiration time won't allow the transaction to succeed.
The 'InitMediatedTransferTask' should spawn MediatedTransfers and wait for confirmation or timeout,
then it should alter timeout/expiration-parameters accordingly.

**Comment by hackaugusto** [comment]
Closing because of the following changes:

276b2f18bcbac4adc4f5ad36353f12b8b03cb8fa Introduced `StartMediatedTransferTask` that is using the maximum expiration per channel `forward_channel.settle_timeout - raiden.config['reveal_timeout']`
beb0a7cf8b9d7b08c74c47111f5705e522666ad5 increased the default settle_timeout to allow for 20 hops (this might change in the future)
