### ISSUE TITLE
Do we need `cmdid`s and for which messages?

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#4297]
## Origin of `cmdid`s

The `cmdid`s were originally used by the UDP transport to identify the type of message received. Since we removed the UDP transport, they are not needed for that purpose, anymore. The Matrix transport uses a `_type` attribute instead to detect the message type.

## Can we remove the `cmdid`s from the messages?

Currently, the `cmdid` is included in the message signatures while the `_type` attribute is not. If we remove the `cmdid`, different message types with the same content will have the same signature. E.g. the messages `Processed`, `Delivered` and `ToDevice` all only contain a `MessageID`. This would allow attackers to take a `Delivered` message and create a `Processed` message just by changing the `_type` attribute in the JSON message. So we need something like the `cmdid` in the signature to prevent this kind of attack.

## Open Questions/Todos

- [ ] `cmdid` and the `_type` attribute are mostly redundant. Can we get rid of one? If we remove `cmdid`, we will have to include the type in the signature
- [ ] Can/should `cmdid`s be merged with [contracts.constants.MessageTypeId](https://github.com/raiden-network/raiden-contracts/blob/1db8c337682185a52177bb52bf30cc44735a7a3a/raiden_contracts/constants.py#L105)?
- [ ] Take care of `Withdraw`, `WithdrawRequest` and `RequestMonitoring`, which currently don't contain a `cmdid`

@rakan @pirapira

**Comment by pirapira** [comment]
> cmdid and the _type attribute are mostly redundant. Can we get rid of one? If we remove cmdid, we will have to include the type in the signature

Getting rid of one is desirable, I believe.  And yes, the signature should change when the type of the message changes.

> Can/should cmdids be merged with contracts.constants.MessageTypeId?

My only requirement: the signatures that's not supposed to go onchain should be useless onchain.  For example, if we don't use the prefix`"\x19Ethereum Signed Message:\n"` for such signatures, there is no need to align the cmdids with `contracts.constants.MessageTypeId`.  An alternative is to merge `cmdid`s and `contracts.constants.MessageTypeId`, and put the ID always in the same position in the signed byte sequence.

**Comment by hackaugusto** [comment]
This issue is mixing a lot of different things in one plate. Here are some notes:

- The smart contract requires and this must not change (to prevent replay attacks):
  - The signature to be tied to a specific channel. Currently done with chain_id, smart contract address, and the channel identifier.
  - The signature is tied to a specific message through a message identifier.

- The client requires that:
  - Off-chain messages, which are an envelope for the blockchain counter part, must have at least one signature respecting the smart contracts requirements (to follow the protocol).
  - Off-chain messages, which are **not** envelopes to blockchain messages, have to be authenticated and all the contents of the message must be authenticated (to prevent tampering and impersonation attacks).
  - Different messages don't happen to have the same shape as other messages or on-chain transactions.

Notes:
- For performance reasons envelope messages share the signature with the blockchain message, the same signature is used to authenticating for both the client *and* the smart contract. This means the one signature used by the client will comply with the format defined by the smart contract, and it will have the message identifier in it.
- The concept of cmdid and message id *are orthogonal*, changing one does not interfere with the other, but they *do overlap*. As longs as the constraints above are preserved they don't have to be equal.
- Because there is no support for any other type of authentication in the current transports (Matrix), signatures are also used for messages that are not sent to the smart contract.

**Comment by err508** [comment]
My five cents: Synchronizing and reusing a shared and smaller set of possible MessageTypeId/cmdid/_type for offchain and onchain messages seems like a good idea to me, as it decreases the likelihood of potential bugs, where e.g. MessageTypeId and cmdid collide and the authentication becomes reusable in a different context. 
I think it also makes sense to do what @pirapira proposed and separate onchain and offchain signatures where appropriate, to have clarity that some signatures can not work when used onchain.

**Comment by karlb** [comment]
If we keep the `cmdid`s, we have proper separation between onchain and offchain messages (with the exception of `EnvelopeMessage`s, where this is not desired). This works because offchain messages start with `cmd_id` (1 byte) + padding (3 byte) while onchain messages start with the address of the respective contract. Since contract addresses are hashes, it's sufficiently hard to create contracts for which these messages can become interchangeable (although the padding could be a bit larger to make this even more unlikely).

So my suggestion is to keep `cmdid`s and add also them to `Withdraw`, `WithdrawRequest` and `RequestMonitoring`. As far as I can see, this solves all requirements listed above with the exception of the deduplication between `_type` and `cmdid`. That could be done by removing `_type` and relying on the `cmdid` instead, but that is less important.

**Comment by hackaugusto** [comment]
> while onchain messages start with the address of the respective contract.

This shouldn't be true, every message starts with the cmdid on the first byte, [ref](https://github.com/raiden-network/raiden/blob/496bea922366861b29c64c108551dd3d7b59531e/raiden/messages.py#L229-L231)

**Comment by pirapira** [comment]
Whatever the message encoding is, onchain signatures are calculated from what Karl described, [ref](https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/data/source/raiden/TokenNetwork.sol#L1466).  What's the name of the thing that's signed here? It's a message, or not?

**Comment by hackaugusto** [comment]
> Whatever the message encoding is, onchain signatures are calculated from what Karl described, ref.

Humm, true, the method is overwritten [here](https://github.com/raiden-network/raiden/blob/496bea922366861b29c64c108551dd3d7b59531e/raiden/messages.py#L336-L350)

**Comment by karlb** [comment]
The `Withdraw` and `WithdrawRequest` messages are similar to the `EnvelopeMessage`s. They reuse the on-chain signatures and thus can't just get a `cmdid` without changing the contracts. https://github.com/raiden-network/raiden-contracts/issues/1110 has been created to take care of those two messages.

The only message that is left is `RequestMonitoring`. That message has two signatures, both of which are used on-chain, so just adding a `cmdid` is not the solution for that case, either.

**Comment by karlb** [comment]
To summarize:
* We do need `cmd_ids` to make sure that message signatures can't be reused for messages of other types
* Envelope messages have their `cmd_id` in the `additional_hash`
* The situation for `Withdraw*` messages is less clear. We have https://github.com/raiden-network/raiden-contracts/issues/1110 to improve that situation.
