### ISSUE TITLE
Invalid endpoint missing port 

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden#4301]
## Intro

Starting Raiden in this manner gives exception Invalid endpoint missing port when trying to access the web-ui

```
raiden --eth-rpc-endpoint https://rpc.slock.it/goerli --api-address "http://localhost:5011" --keystore-path ~/.ethereum/keystore/ --address 0x1Bc9667EDCb58197f4A5431FBf0c2289dDc235f3 --network-id goerli --environment-type production --log-file node-1Bc966-goerli.26June2019.log --log-config "raiden:debug" --enable-monitoring
```

## Problem Definition

The Exception [gist](https://gist.github.com/agatsoh/64ea2693ee4c55cf90d97d40eeadb9ae)

Thanks to @ulope for pointing that the exception occurs [here](https://github.com/raiden-network/raiden/blob/179ca4ec3e7ead8f419a024edae7ad3f5c7701cf/raiden/utils/__init__.py#L100-L101)

Raiden version 
`version 0.100.4.dev670+gcb9e6975b`

**Comment by ulope** [comment]
Further context: The issue occurs because the web3 endpoint is passed to the webui.
Before that happens the address is processed through `split_endpoint`

https://github.com/raiden-network/raiden/blob/096ab96936346ede8c423e0d6678299df9aa06a0/raiden/api/rest.py#L384

which since a recent refactor no longer accepts addresses without explicit port.
