### ISSUE TITLE
Raiden client sends wrong capacity updates to PFS

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#4377]
## Problem Definition

@ulope wrote:
Ok I looked at the logs, it doesn't appear to be a presence problem after all. See the timeline below.

However there still is some weirdness with some nodes not changing back to `UNREACHABLE` state after they shut down. 
But that should have no effect on those tests.

- `pfs5_too_low_capacity`:
  - Channels start opening `09:53:41`
  - PFS presence of all nodes becomes `REACHABLE` at `09:55:23`
  - Channels finish opening `10:02:52`
  - Scenario queries paths from `node0` -> `node3` at `10:02:52`
  - Empty response, scenario fails
  - Nodes are shut down at `10:02:53`
  - Presence state in the PFS for nodes `0` and `1` become `UNREACHABLE` at `10:02:53` and `10:03:23` respectively
  - Interestingly according to the log the other nodes don't seem to become `UNREACHABLE` at all.

- `pfs6_low_capacity`:
  - Channels start opening 10:05:23
  - PFS presence of all nodes becomes `REACHABLE` at `10:07:08 - 10:07:09`
  - Channels finish opening `10:14:53`
  - Scenario queries paths from `node0` -> `node3` at `10:14:53`
  - Empty response, scenario fails
  - Nodes are shut down at `10:14:53`
  - Presence state in the PFS for nodes `4` and `3` become `UNREACHABLE` at `10:14:53`
  - Presence state in the PFS for nodes `2` becomes `UNREACHABLE` at `10:15:28`
  - As above the remaining nodes don't seem to switch to `UNREACHABLE`

- `pfs7_simple_path_rewards` (simplified):
  - Nodes `REACHABLE` at `10:19:07 - 10:19:08`
  - Failing PFS request at `10:28:40`
  - Node shutdown at `10:28:40`
  - Nodes `3` and `1` become `UNREACHABLE` at `10:28:40`
  - Remaining nodes again no presence change
    - Interestingly this is consistent between both goerli pfs'

**Comment by christianbrb** [comment]
Needs a hand over from @jomuel to @karlb

**Comment by Dominik1999** [comment]
So I have also got the same error in the new pfs7 scenario. Short description:
( A <-> B <-> C <-> D)
1. Deposits only one-sided, A->B, B->C, C->D
2. There is a failing transfer from D -> A (no capacity)
3. Deposits on the other channel side, B->A, C->B, D->C
4. Should be a successful transfer from D -> A but the PFS gets incorrect CapacityUpdates and doesn't return a route

**Comment by karlb** [comment]
The client sends capacity updates with a balance of zero after doing a deposit. Here's why:
* The client receives `ContractReceiveChannelDeposit`
* `handle_channel_depsoit` (sic) is called
* `actionchannelupdatefee_from_channelstate` is called ot update both the fee schedule and the capacity.

This looks good, but actually `handle_channel_depsoit` does not add the deposit right away, because the event is not confirmed, yet. Instead it schedules that action for the block when the event becomes confirmed.
But `actionchannelupdatefee_from_channelstate` is executed right away, so it still sees the old channel state when creating the balance update message for the PFS.

**Comment by Dominik1999** [comment]
Very nice, thank you Karl!
