### ISSUE TITLE
Flaky test_cli_full_init_dev due to timeout

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#4450]
```
_______ ERROR at teardown of test_cli_full_init_dev[0.19.0-development] ________

>       lambda: ihook(item=item, **kwds),
        when=when,
    )

../venv-3.7-LINUX/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py:306: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../venv-3.7-LINUX/lib/python3.7/site-packages/six.py:693: in reraise
    raise value
../venv-3.7-LINUX/lib/python3.7/site-packages/six.py:693: in reraise
    raise value
../venv-3.7-LINUX/lib/python3.7/site-packages/six.py:693: in reraise
    raise value
raiden/tests/integration/cli/conftest.py:62: in raiden_testchain
    yield args
/usr/local/lib/python3.7/contextlib.py:119: in __exit__
    next(self.gen)
raiden/tests/utils/smoketest.py:209: in setup_testchain
    web3=web3,
/usr/local/lib/python3.7/contextlib.py:119: in __exit__
    next(self.gen)
raiden/tests/utils/eth_node.py:527: in run_private_blockchain
    yield executors
/usr/local/lib/python3.7/contextlib.py:119: in __exit__
    next(self.gen)
raiden/tests/utils/eth_node.py:429: in eth_run_nodes
    yield executors
/usr/local/lib/python3.7/contextlib.py:524: in __exit__
    raise exc_details[1]
/usr/local/lib/python3.7/contextlib.py:509: in __exit__
    if cb(*exc_details):
/usr/local/lib/python3.7/contextlib.py:377: in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
../venv-3.7-LINUX/lib/python3.7/site-packages/mirakuru/base.py:140: in __exit__
    self.stop()
raiden/utils/http.py:234: in stop
    super().stop()
../venv-3.7-LINUX/lib/python3.7/site-packages/mirakuru/base.py:284: in stop
    self.wait_for(process_stopped)
raiden/utils/http.py:158: in wait_for
    time.sleep(self._sleep)
../venv-3.7-LINUX/lib/python3.7/site-packages/gevent/hub.py:159: in sleep
    hub.wait(t)
src/gevent/_hub_primitives.py:46: in gevent.__hub_primitives.WaitOperationsGreenlet.wait
    ???
src/gevent/_hub_primitives.py:55: in gevent.__hub_primitives.WaitOperationsGreenlet.wait
    ???
src/gevent/_waiter.py:151: in gevent.__waiter.Waiter.get
    ???
src/gevent/_greenlet_primitives.py:59: in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
src/gevent/_greenlet_primitives.py:59: in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
src/gevent/_greenlet_primitives.py:63: in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   Failed: Timeout >45s

src/gevent/__greenlet_primitives.pxd:35: Failed
```

Seen in https://circleci.com/gh/raiden-network/raiden/66302#tests/containers/17

[raiden-debug_2019-07-25T09:12:26.036360.log](https://github.com/raiden-network/raiden/files/3430843/raiden-debug_2019-07-25T09.12.26.036360.log)

**Comment by karlb** [comment]
It looks like this test has been executed twice for no good reason.
```
raiden/tests/integration/cli/test_cli_development.py::test_cli_full_init_dev[0.19.0-development] PASSED [ 28%]
raiden/tests/integration/cli/test_cli_development.py::test_cli_full_init_dev[0.19.0-development] ERROR [ 28%]
```
Can anyone explain this?

**Comment by hackaugusto** [comment]
@karlb that happens when the test itself passes, but the fixture teardown raises an exception.

**Comment by hackaugusto** [comment]
There seems to be multiple things going on that made the test flaky, there is something wrong with the interaction of pytest-flaky and the logging system that produced a huge stack trace.

Besides that, it seems the main reason for this failure was parity, the process just takes too much time.

The test started roughly at 2019-07-25 09:11:57 (first line of this [log](https://66302-50646767-gh.circle-artifacts.com/17/eth-logs/parity/add4d310.log), the blockchain is the first thing that is started through the fixtures), this is the test setup.

The test itself spawns the Raiden client, that started at 2019-07-25 09:12:29.197603, and run roughly until 2019-07-25 09:12:32.798711 [first and last lines of this log](https://66302-50646767-gh.circle-artifacts.com/17/eth-logs/test_cli_full_init_dev%5B0.19.0-development%5D/raiden_nodes/cli_test.log)

The teardown phase ran until 2019-07-25 09:12:41.519634 [last line of this log](https://66302-50646767-gh.circle-artifacts.com/17/eth-logs/test_cli_full_init_dev%5B0.19.0-development%5D/raiden-debug_2019-07-25T09%3A12%3A26.036360.log), and it got killed with a timeout >45s

Parity kept running until 2019-07-25 09:14:18 because the teardown was not executed (the time out exception made the next test start, while the parity process from the previous test was still around) [ref](https://66302-50646767-gh.circle-artifacts.com/17/eth-logs/parity/add4d310.log)

**Comment by hackaugusto** [comment]
This should have been fixed by: https://github.com/raiden-network/raiden/pull/4458
