### ISSUE TITLE
Dirty node - not able to send payments

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4611]
## Problem Definition

Tested with v0.100.5a0

From @manuelwedler (please provide details/logs)

I came across one problem with a dirty node though. I opened a channel but was not able to send payments through it. The error was that there would be no path. I tried with and without PFS.

This only happened with that channel between those two specific nodes. Sending and receiving payments from those nodes to other nodes worked normally. After closing this broken channel and opening a new one between them, the error doesn't occur anymore.

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
command -v solc && solc --version
command -v geth && geth version
command -v parity && parity --version
command -v raiden && raiden version
[ -d .git ] && git rev-parse HEAD
```

**Comment by LefterisJP** [comment]
Hey @manuelwedler please provide us with the logs, more details and the DBs so we can properly debug.

**Comment by manuelwedler** [comment]
So this happened with two dirty nodes. Both could send payments to other nodes but it was not possible to send payments through the channel between them. I restarted node 2 a couple of times, also to test if it was related to PFS. Closing the channel worked normally. Sending payments between the nodes through a newly created channel did not give an error.

Here are the logs and DBs for the two nodes: 
[logs_dbs.zip](https://github.com/raiden-network/raiden/files/3515713/logs_dbs.zip)

**Comment by LefterisJP** [comment]
Thank you manuel. This is possibly a bug (?), we will see. Someone will investigate.

**Comment by LefterisJP** [comment]
So this seems to be Transport related.

Looking at the logs we got two nodes. Node1 (`0x65A148DE5d57279EB9FdFe8c11cF9A43E599a537`) and Node2 (`0x06292d52101159d4db5195F043FaD81Fc2F0bc50`)

Node2 tries to send a payment to Node1 with message identifier: `1859507807206688319` but that never reaches Node1 and thus Node2 keeps retrying until infinity.

As far as Node1 is concerned, Node2 is offline all the time. Here is the log excerpt of the `addresses_uids_and_presence`:

```
'0x06292d52101159d4db5195F043FaD81Fc2F0bc50': {'@0x06292d52101159d4db5195f043fad81fc2f0bc50:transport01.raiden.network': 'offline', '@0x06292d52101159d4db5195f043fad81fc2f0bc50:transport03.raiden.network': 'offline'},
```

@ulope do you have any ideas here?

Why are there 2 different matrix servers involved?

**Comment by ulope** [comment]
I'll take a look. 

The two servers can happen because of roaming (e.g. connecting from a different network location or because one of the servers wasn't reachable at some point). That is an expected part of how we use matrix and shouldn't cause issues.

**Comment by ulope** [comment]
Ok, had a look, unfortunately I can't really get a picture of what's happening because the logs of node 1 are incomplete. 

Those are the logs posted above:
- Node 1:
  - `16:11:59` - `16:18:25` (incomplete, start missing)
- Node 2:
  - `14:21:30` - `14:48:26`
  - `14:48:43` - `14:51:13`
  - `14:51:17` - `14:51:50`
  - `14:53:11` - `14:54:43`
  - `14:54:43` - `15:05:44`

As you can see there is no period where logs are available from both nodes.

**Comment by LefterisJP** [comment]
`Node 1` log's filename indicates the logs start at `14:20` just like `Node2`, so I assumed they are from the same time.

Did not check the timestamps themselves. @ulope a sidenote here to maybe make the log entry timestamps more visible in the generated html from`json-log-to-html.py`since right now it's an additive value to the start of the log which can cause confusion like it did for me.

@manuelwedler Can you provide the full logs for node1?

**Comment by ulope** [comment]
@LefterisJP There's a cli flag whether to show relative or absolute values. Also in relative mode you can hover over the value to see the absolute time.

**Comment by manuelwedler** [comment]
Ah sorry, I didn't realize that there are more logs. Here are the complete logs for Node 1:
[logs_node1.zip](https://github.com/raiden-network/raiden/files/3558856/logs_node1.zip)

**Comment by rakanalh** [comment]
@ulope can you look at the new logs please?

**Comment by ulope** [comment]
(There still seems to be a bit of log missing, from Node 2 before 14:21, would be nice to see what happened there.)

There are two small connected bugs here for which I created #4715 and #4716.

However apart form those there is still something weird going on here.
Sequence of events:
- `Node 1`:
  - `14:20:27` - Login in to `transport03`
  - `14:20:31.53` - Receives invite from `@<<Node 2>>:transport01.raiden.network`
  - `14:20:31.62` - Receives invite from `@<<Node 2>>:transport03.raiden.network`
  - Both invites got declined since `Node 2` wasn't whitelisted yet.

- `Node 2`:
  - `14:45:08` - Initiate transfer to `Node 1`
  - `14:45:08` - Room lookup for transfer. Existing room with offline user `@<<Node 1>>:transport01.raiden.network` is chosen (this is #4716)
  - Messages are sent into a room with the wrong users. Invite attempts are not repeated due to #4715.

The two concurrent invites can only happen if **two** instances of Raiden were running with the `Node 2` account (one logged in to `transport01`, one to `transport03`) which is of course a bad thing.

**Comment by manuelwedler** [comment]
@ulope Unfortunately I don't have logs earlier than the provided ones, but it was used before that of course.
There were definitely not two instances of Raiden with the same account running at the same time.

**Comment by ulope** [comment]
> There were definitely not two instances of Raiden with the same account running at the same time.

Hm very weird. I can't really think of another scenario that would lead to two invites from the same user on two different servers arriving at the moment the user comes online...

**Comment by LefterisJP** [comment]
@Dominik1999 @ulope Can you also write why this issue was closed?

**Comment by ulope** [comment]
@LefterisJP See my [comment](https://github.com/raiden-network/raiden/issues/4611#issuecomment-527167384) above. Two issues were split out. 

The duplicate invite is weird but we can't do anything about it since there are no more logs (and also once #4715, #4716 are fixed it shouldn't matter if it ever happens again).
