### ISSUE TITLE
Latest documentation does not seem to be up-to-date with the releases

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden#4764]
## Problem Definition

The latest release is https://github.com/raiden-network/raiden/releases/tag/v0.100.5a0

[Latest documentation](https://raiden-network.readthedocs.io/en/latest/) shows "0.100.5-dev1", which is one testnet release earlier.

![grafik](https://user-images.githubusercontent.com/35398162/64411549-b3fa4400-d08d-11e9-8e0d-f8b5bd3edb2c.png)

## Expected behavior

Latest documentation points to the latest release v0.100.5a0 - Antifragile Crocodile

Release name does not work a0 fails building 
Changelog problem. add a dash instead of. Will be changed RC

**Comment by LefterisJP** [comment]
As I had posted in the chat this is due to the `v0.100.5a0` release tag not being able to be processed by our `releases` changelog package.

We need to be changing that to `v0.100-5a0`. Doc builds should get fixed from the next release provided we use a release tag that is parseable by the `releases` changelog package.
