### ISSUE TITLE
Performance related question

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden#4872]
I'm running a Raiden node against Infura with a set of contracts I deployed myself.

Infura reports above ~150,000 daily calls from Raiden. Does it make sense. My node has one channel but is basically doing nothing.

Here are the method distribution as reported by Infura.

<img width="1360" alt="Screen Shot 2019-09-13 at 17 54 13" src="https://user-images.githubusercontent.com/9712754/64872653-3ff10a80-d650-11e9-97ba-c523940a4765.png">

**Comment by LefterisJP** [comment]
**Disclaimer**: Performance is still something we are not really tackling at all. There may be a lot of things that can be improved such as identifying and removing redundant RPC calls, miscellaneous optimizations, transport optimizations and so on and so forth.

As for the question. At the moment every half a second (there is even a TODO, to improve this) the alarm task runs. Which explains the `eth_getBlockByNumber` number(there is 86400 seconds in a day so just from that ~172800 RPC calls to `eth_getBlockByNumber` will happen).

https://github.com/raiden-network/raiden/blob/f8f14d62f4a2ae9308b85aa4ae100bea0a3fffec/raiden/tasks.py#L151-L154

When that happens the ethereum client is queried for the latest block. If a new block is detected then we go to the [new block callback](https://github.com/raiden-network/raiden/blob/develop/raiden/raiden_service.py#L695).

The new block callback asks for a lot of events logs since the last seen block for all contracts which explains the `eth_getLogs` number.

As for the `eth_getBlockByHash` I think internally web3 will call that whenever getBlock is passed a hash instead of an int.

**Comment by offerm** [comment]
Thanks @LefterisJP 

Will you be happy to set the self.sleep_time to 2 second in case the provider is Infura?
This should take the number of daily call below 100K and allow to use their "free" account.

**Comment by LefterisJP** [comment]
I think it should be more than fine. Considering the block time it can start even higher. We just never got around to it and we should. Already made an issue for this: https://github.com/raiden-network/raiden/issues/4877

**Comment by palango** [comment]
It's also strange that `eth_getBlockByHash` is so prominent as we have a cache for that.

https://github.com/raiden-network/raiden/blob/a7140e2c28202ca6a2f7ce10bcf3151690e65a1b/raiden/network/rpc/middleware.py#L34-L41

**Comment by hackaugusto** [comment]
@offerm I guess there is no need to special case infura in the alarm task, just setting the sleep to  `2` for every network should be fine.

**Comment by LefterisJP** [comment]
@hackaugusto We made this issue to make if configurable per network https://github.com/raiden-network/raiden/issues/4877

**Comment by hackaugusto** [comment]
I generate some profiling data from a integration test run. Most of the calls to `getBlock` are from the alarm task, the work @jomuel is doing on https://github.com/raiden-network/raiden/issues/4877 should have the biggest impact on this.

For the `getLogs` batching should have the biggest impact https://github.com/raiden-network/raiden/issues/2818

**Comment by rakanalh** [comment]
https://github.com/raiden-network/raiden/issues/4877 handles adjusting the new block query interval. Augusto also mentioned the specific issues that could help resolving the bigger issue of performance. Closing this one.
