### ISSUE TITLE
Ignore duplicated mediated transfers

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#490]
## Problem Definition

If a node receives the same mediated transfer twice it should assume a loop occurred and the transfer cannot be delivered.

## Tasklist

- [ ] Maintain a dictionary that can be used to query if the message is known or not
- [ ] Change the `RaidenMessageHandler` to ignore duplicated transfers.

**Comment by hackaugusto** [comment]
The same transfer going through the same node is not necessarily a loop. Consider the corner case represented by the following subgraph (arrows represent direction of the messages):

![raiden](https://cloud.githubusercontent.com/assets/310139/24682414/1bac4d46-1989-11e7-8ee9-568c4f6fa05c.jpg)

- A transfer from A to G must be mediated through B.
- B has 3 routes available with an equal number of hops
  - Suppose that B's choice is `B-C-T-G`
- If T does not have enough capacity in the `TG` channel then it must try a different route
- T uses the path `T-D-B-E-F-G`, making use of the node B again

**Comment by LefterisJP** [comment]
Note: This is not in the MVP scope.

We discussed this issue with @hackaugusto last night and think that an approach to handle this problem and differentiate between bad loops and good loops would be to drop Refund Transfers and replace them with mediated transfers.

This problem also will probaly be a non-issue if we switch to using a routing service or if we change the routing so that it's anonymous and the initiator chooses the route and it's immutable.

**Comment by konradkonrad** [comment]
Similar case:
- network: A <-> B
- mediated transfer A -> A via B (`sender == target == A`, `mediator = B`)

**Comment by hackaugusto** [comment]
I think this is a non-issue. Receiving the same transfer twice could sometimes be a problem, but it does not mean it will always be a problem.

**Comment by karlb** [comment]
Does closing this issue mean we can remove the respective comment from `RefundTransfer`?

**Comment by LefterisJP** [comment]
I guess so @karlb
