### ISSUE TITLE
What to do with `LockedTransfer.fee`?

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#4991]
It is in the code base and in the messages that are being sent. But I don’t see it actually being used anywhere. Although it does make sense to have such a field to prevent mediators from taking more fees than the target will allow. It’s better to fail early and provide clear error messages in such cases. Was this the original intention of the field?

Does anyone have a strong opinion on this?

- [ ] Make decision
- [ ] Change code (and maybe docstrings/comments)
- [ ] Update spec

**Comment by LefterisJP** [comment]
If I recall correctly the idea of the fee field was to determine earlier on the route (and not only at secret request) how much of the total amount is the actual payment and how much is allocated as fees.

I think we had even discussed that this should be called `remaining_fee` and that each mediator would also reduce it. Then perhaps we can fail the transfer at a particular hop and not only at the end if a mediator sees that taking off his fees from the amount would put the `remaining_fee` to negative.

**Comment by andrevmatos** [comment]
I'm starting to implement https://github.com/raiden-network/light-client/issues/246 , and just stumbled on this issue. I have strong opinions about it.
I start from the assumption that, in a payment system, it's a requirement from the sender's perspective that the receiver (target) of a payment/transfer receives exactly what they were supposed to. Not more, not less. I think this is essential for a payment system. It just feels wrong that the mediators take _arbitrary_ deductions from the **amount** as fees (actually without knowing about how much they can), and on a best effort, the target _informs_ the initiator about the amount they received, and the initiator then decides to accept it or not, completing the transfer by revealing the secret.

I agree with @LefterisJP , although I think we don't need to rename the field, just document what it means would be enough. All the fees logic must be played on the `fee` field. The initiator includes the maximum value it accept to pay in fees in this field, and the effective BP's transfering amount (how much `transferred_amount` will be increased on unlock) is `amount + fee`, and each mediator deduces its fee from this value. The last hop can forward `zero` fee (effectively deducing any remaining fee), it's more important that the target receives untouched `amount`. If for any reason on some hop the reamining fees are not enough, it should fail/refund the transfer, the same as if there was not enough capacity anymore in the channel.
This has some downsides though:
- PFS's `estimated_fee` may not be lowest value the remaining `fee` will reach, even if right, due to negative imbalance fees; so we either accept negative values on this field, or remove the possibility of negative imbalance fees, making the minimum possible fee deduction in any hop = 0
- fees are variable depending on route taken, so initiator must either attempt the transfer with a single (cheapest) route and its fee, decreasing the chance of success for the lack on alternative routes, but paying the minimum in fees;
- if the initiator wants to send multiple routes, it must use fee as the estimated fees of the most expensive route in the set (they may decide on some threshold on it though), and this will actually be spent by the last hop even if the cheapest route succeeds.

An alternative to the remaining fee approach is **accumulated fee** approach:
- initiator sends transfer with fee=0
- each hop increases this value by its fee and forward
- mediators expect an unlock with `transferred_amount = amount + (forwarded transfer fee - received transfer fee)`
- multiple routes can be forwarded/attempted, each will have its total accumulated fee at the end
- target includes total accumulated fee in `RequestSecret` to initiator, which can then decide if the total fee is reasonable before revealing.
- Advantage: multiple routes can be attempted, the fee of the cheapest succeeding one will be the effective fee for the whole transfer, initiator can have final stable picture of the fees while transfer is already complete/amounts locked in the path
- Downside (?): smart contracts (unlocking on chain) includes only the `amount` value (as no fee was included in the initiator's LockedTransfer, as it didn't know in advance how much it'd ending to be); so if the transfer needs to be unlocked on chain, no remaining mediator fees are paid. This can be an incentive for everyone to play off-chain, so may not be seen as an actual downside.

In all cases, `amount` **must not change**, and it must be strictly checked on SecretRequest. Effective/final  BP's `transferred_amount` though changes as to pay the fees on each hop.

**Comment by konradkonrad** [comment]
> * fees are variable depending on route taken, so initiator must either attempt the transfer with a single (cheapest) route and its fee, decreasing the chance of success for the lack on alternative routes, but paying the minimum in fees;

I am not sure if I can follow:
- with source routing, there are no alternative routes, right?

> * if the initiator wants to send multiple routes, it must use fee as the estimated fees of the most expensive route in the set (they may decide on some threshold on it though), and this will actually be spent by the last hop even if the cheapest route succeeds.

- for a diverted transfer (i.e. multi-route transfer with a single lock), a node would need to send different locked transfers, right?
- for trying multiple routes, the initiator **must** use different locks, so of course the initiator would set different `fee` values for those, right?

With the three points above, I don't quite understand the problem stated here.

As for the general approach:



> I think we had even discussed that this should be called `remaining_fee` and that each mediator would also reduce it. Then perhaps we can fail the transfer at a particular hop and not only at the end if a mediator sees that taking off his fees from the amount would put the `remaining_fee` to negative.


I agree.

**Comment by andrevmatos** [comment]
@konradkonrad the `result` from a PFS request is an array, which can contain multiple routes, and the `metadata.routes` passed in the `LockedTransfer` also is an array which can contain multiple routes to be _tried_. I'm not sure if it's used right now, but as per protocol, it seems we allow multiple routes to be passed and tried on each mediator (if transfer is refunded there), but there's no specific per-route fee (that would be quite hard to enforce on the BP anyway), therefore, as I also stated, we must either pass on a single route and its corresponding fee, or pass the fee of the most expensive route in list, and on this `remaining_fee` model, it'll be completely consumed.
This still need to be implemented over the `fee` parameter, again, receiver needs to know exactly how much it was supposed to receive, but again this may give problems if some mediator adds to this fee (negative imbalance fee) instead of it being decreasing only.

**Comment by andrevmatos** [comment]
@Dominik1999 I think the accumulated fee approach doesn't need the 5% increase on the mediators. Each of them can simply add and forward exactly their fee, which may or may not be larger than initial estimation due to imbalance fees, and upon SecretRequest, despite the total fee being -5, 0, 5 or 10% larger than PFS's estimation, the initiator can evaluate and decide to pay exactly the value it received from target over the succeeding route. 5% increase may or may not be util only on the PFS estimation.

**Comment by Dominik1999** [comment]
@karlb @andrevmatos @rakanalh let's have a call about this on Monday 07.10. 

Can you @andrevmatos describe in 3 bullet points what exactly your problem at the light client is that you try to solve?

**Comment by andrevmatos** [comment]
I'd say our problem is more conceptual than technical:
- From light-client/payer's perspective in a payment system, it should be a requirement to be able to pay an exact amount to a target, not more, not less.
- It's preferable a payment fails earlier (to avoid locking funds unnecessarily along the route) than be "completed" with wrong amount, or failing later because it ended being a different value than expected.
- Fee protocol also must be exact. Payer needs to know how much fees it's paying. PFS must not inflate estimations. It's on the payer's hands to decide if it's useful to send a relaxed fee to increase the chance of success, as it knows the data they got from PFS may be outdated when LockedTransfer passes through mediators.

Current approach makes these points it very hard or impossible to achieve. Technically we can implement it as is, but a `fee` field is already presend and there're a couple of ways to achieve these points without the current uncertainties.

**Comment by christianbrb** [comment]
Lightning is also adding the fee to the amount sent (see https://bitcoin.stackexchange.com/questions/84934/why-does-my-c-lightning-node-pay-more-than-the-invoice-plus-routing-fees), but has got two different fields to distinguish the payment amount sent and the value of the transfer.

Maybe @renepickhardt can explain this in more detail?
