### ISSUE TITLE
Nonce too low

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden#5044]
My Raiden node just shut down after approx 1h 20 min throwing this error: `FATAL: An unexpected exception occured. A traceback has been written to /tmp/raiden-exception-2019-10-07T12-49p_by1i8n.txt
{'code': -32000, 'message': 'nonce too low'}`

Raiden 0.200.0rc1
[raiden-debug_2019-10-07T11:28:06.284028.log.zip](https://github.com/raiden-network/raiden/files/3697553/raiden-debug_2019-10-07T11.28.06.284028.log.zip)
[raiden-exception-2019-10-07T12-49p_by1i8n.txt.zip](https://github.com/raiden-network/raiden/files/3697558/raiden-exception-2019-10-07T12-49p_by1i8n.txt.zip)
[node_0faa9bcd.zip](https://github.com/raiden-network/raiden/files/3697753/node_0faa9bcd.zip)

**Comment by rakanalh** [comment]
Talel did an on-chain transaction through metamask while the Raiden node is running causing the nonce to increase outside of Raiden making Raiden's local nonce invalid. This breaks the exclusive access rule to the Raiden client.

**Comment by konradkonrad** [comment]
@taleldayekh Did you read and comply with:
https://raiden-network.readthedocs.io/en/stable/overview_and_guide.html#requirements-for-safe-usage

> Unique account for Raiden: We need to have a specific Ethereum account dedicated to Raiden. Creating any manual transaction with the account that Raiden uses, while the Raiden client is running, can result in undefined behaviour

I am asking, because I see this transaction:

https://rinkeby.etherscan.io/tx/0x75e6008de6d1dac57402229599d7985dd2fdefd707e665c59867d5b380524327 at Oct-07-2019 12:29:18 PM +UTC (block explorer time)
