### ISSUE TITLE
Insufficient ETH crashes node when channel is closed via another node

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/raiden#5048]
I'm running two nodes that have a channel open with each other. One has ETH the other has no ETH. When I close the channel from the node that has ETH it crashes the node that has no ETH.

```ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}```

[node_83beef70.zip](https://github.com/raiden-network/raiden/files/3698262/node_83beef70.zip)
[raiden-debug_2019-10-07T15:08:46.360672.log.zip](https://github.com/raiden-network/raiden/files/3698263/raiden-debug_2019-10-07T15.08.46.360672.log.zip)

**Comment by palango** [comment]
Besides that crash there's also this scary message in the logs:
```
{"node": "0x83BEef7079F3cb453CF96d8Dac04F4E199D888F6", "raiden_events": [{"reason": "Invalid LockedTransfer message. Nonce did not change sequentially, expected: 7 got: 3.", "payment_identifier": "1570460502625", "_type": "raiden.transfer.events.EventInvalidReceivedLockedTransfer"}], "event": "Raiden events", "logger": "raiden.raiden_service", "level": "debug", "greenlet_name": "GMatrixClient._sync user_id:@0x83beef7079f3cb453cf96d8dac04f4e199d888f6:transport03.raiden.network sync_token:s165614_159030_0_16_668_1_1_2143_1", "timestamp": "2019-10-07 15:19:50.797069"}

**Comment by jomuel** [comment]
The nonce mismatches were caused by processing the same `ActionInitMediator` message multiple times with different message identifiers. Apparently the same `LockedTransfer` was sent multiple times by the partner. The first time is processed correctly in wal reply and the partner's database is lost, so it is difficult to tell why that happened.

For the crash itself, refer to issue #5060

**Comment by rakanalh** [comment]
We have to also figure out why Raiden crashed and summarize the result here. This has to be done so that we can handle potential failures early on even if the eth node is not "behaving well"

**Comment by jomuel** [comment]
There are two strange things happening in this log, which seem to not even be related:

- The crash due to an uncaught Geth exception, which is covered in #5060. (We know that the Geth node was not working probably and the problem is most likely not in Raiden here. However, Raiden should not just crash with no explanation if the underlying Eth node does unexpected things.)

- The failed transfers due to nonce mismatches that @palango pointed out above.

Let's call the partner node Alice and the crashed node Bob. Unfortunately we didn't keep Alices database, but Bob's log shows that Alice acted strange:

Alice sent two transfers with the same balance data, same nonce, but different message identifiers. Bob acted as expected, the first transfer was successful and the second was dropped due to nonce mismatch. Alice then retried the second transfer several times.

A likely explanation is that there were actually two transfers with the same amount of tokens sent through the Alice node, but after the first Alice and Bob went out of sync. While Bob had processed the transfer, Alice thought for some reason it hadn't happened or failed.
