### ISSUE TITLE
A user needs to know, when their ETH client doesn't work properly

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5060]
## Abstract

We were manual testing with a broken geth Ethereum client and Raiden showed a lot of different errors
- https://github.com/raiden-network/raiden/issues/5048
- https://github.com/raiden-network/raiden/issues/5051
- https://github.com/raiden-network/raiden/issues/5044

We need the Raiden Client to be predictable, so we need more checks. If the Ethereum client is somehow broken, the Raiden Client needs to notify the user but not crash.

## Specification

tbd

## Backwards Compatibility

If the feature is technical in nature and introduces changes to the Raiden Protocol, then please use this section to describe how backwards compatibility with the previous version of the protocol can be achieved.

**Comment by Dominik1999** [comment]
ok, that makes sense. Thanks @konradkonrad 

However, Talel was testing with a broken Geth Node, right? He did not notice this as a user. The client should somehow recognize that and inform the user in my perspective.

**Comment by jomuel** [comment]
As @konradkonrad said, everything we can do about unexpected exceptions will be speculative. What we could do is link to a troubleshooting page and/or provide a more elaborate error message with possible reasons:

- In case of an Eth node exception, state that the problem may be in the underlying Eth node like in #5048

- In the specific case of an Eth nonce mismatch like #5044, remind that Raiden must be the exclusive user of its wallet

- ...

However, distinguishing user errors, bugs in raiden and eth node malfunctions will hardly be possible, so exceptions caused by broken eth nodes like #5048 will still have to be fatal.

**Comment by hackaugusto** [comment]
not actionable
