### ISSUE TITLE
Don't block during startup while waiting for block to be mined

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#511]
## Problem Definition

Raiden can be quite slow when starting up since it needs to wait for a new block to be mined. This process is currently blocking, which is why it can take a long time to start raiden.

## Solution

Make the process of waiting for a block to be mined so that the node gets registered in the endpoint registry non-blocking

**Comment by LefterisJP** [comment]
I would rather to get rid of this waiting time. It is waiting for a block to be mined so that it can make sure it got registered in the endpoint registry.

We can still wait for this to happen but we don't need to block the entire app for that. As you also have just noticed it makes for a horrible user experience.

**Comment by czepluch** [comment]
Yes, that is a better solution :)

**Comment by czepluch** [comment]
Updated the issue

**Comment by LefterisJP** [comment]
This issue is handled with https://github.com/raiden-network/raiden/pull/685
