### ISSUE TITLE
Balance mismatches in scenarios (single channel)

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5150]
Related #5078 

This issue is the result of seeing some errors like the following in scenarios (this is from mfee1):
```
Value mismatch for "balance". Should: "10211" Is: "0"
```

From the logs it seems like the balances are consistent for the nodes itself. However, in the scenario we assert the same channels state from two nodes:
https://github.com/raiden-network/raiden/blob/c15867186e93c00490cb9407c120208e137a4b9e/raiden/tests/scenarios/mfee1_flat_fee.yaml#L68-L69

This shows that node 0 has processed the payment and updated it's balances, but node 1 didn't do that yet.

This leads to some further points:
- We can fix this scenario by adding a `wait: 5` task, however we should think about that problem and add better synchronization (there's probably other scenarios with this problem as well)
- Why does this race condition just now? It seems like something became slower, and therefore the race condition became more likely to happen.
- From the users perspective, does it make sense to return `200` from the API call, even if the other nodes haven't unlocked their locks yet.

**Comment by LefterisJP** [comment]
Hey @palango.

As also discussed in pm via rocketchat:

> We can fix this scenario by adding a wait: 5 task, however we should think about that problem and add better synchronization (there's probably other scenarios with this problem as well)

I don't think that adding `wait`, essentially sleeping, in any test is a proper solution. We need proper synchronization primitives implemented inside the SP for this.

> Why does this race condition just now? It seems like something became slower, and therefore the race condition became more likely to happen.

That's a very good question. Something slowing things down could also explain why the scenario [here](https://github.com/raiden-network/raiden/issues/5078#issuecomment-545824195) some times does not take the closed channel into account. Maybe because run is so slow that by the time it gets there, the channel is also settled (~40 blocks)

> From the users perspective, does it make sense to return 200 from the API call, even if the other nodes haven't unlocked their locks yet.

I don't see why not. As per our protocol a payment is considered successful once the initiator reveals the secret.

https://github.com/raiden-network/raiden/blob/c15867186e93c00490cb9407c120208e137a4b9e/raiden/transfer/events.py#L198-L220

Here you are looking at the problem from the view of a coordinator (the SP). For the coordinator we want the assertions to happen when all nodes have completely synchronized. **For that reason we need synchronization primitives in the SP.**

**Comment by Dominik1999** [comment]
> I don't see why not. As per our protocol a payment is considered successful once the initiator reveals the secret.

Why is that? I just want to understand. The initiator will send another message after revealing the secret, right? At least one unlock to its direct channel partner from what I understand. So there are tasks missing even from the perspective of the initiator and not only from a global coordinator perspective. 

So why do we not define the transfer as final when all steps/tasks of the transfer were performed?

**Comment by rakanalh** [comment]
It's because the protocol as it is right now doesn't introduce any message that notifies the initiator that the target received the unlock. IMO, there shouldn't be one because it's an informative message and does not add much value other than convenience. 

> I don't think that adding wait, essentially sleeping, in any test is a proper solution. We need proper synchronization primitives implemented inside the SP for this.

I agree, but this primitive is going to look like `wait_balance {"timeout": 10}` or something like that which is essentially a wait. Otherwise, the SP itself cannot do anything other than polling the APIs.

**Comment by Dominik1999** [comment]
Thanks Rakan.

> It's because the protocol as it is right now doesn't introduce any message that notifies the initiator that the target received the unlock.

I understood we send the 200 the moment the secret reveal is sent. Not when the unlock is sent. Or is that understanding incorrect?

**Comment by LefterisJP** [comment]
> I understood we send the 200 the moment the secret reveal is sent. Not when the unlock is sent. Or is that understanding incorrect?

Your understanding is correct Dominik. The API is essentially waiting on the event `EventPaymentSentSuccess` I posted about [above](https://github.com/raiden-network/raiden/issues/5150#issuecomment-545901728).

Once that event is seen the API returns.

**Comment by LefterisJP** [comment]
From what I understand Is this issue solved by adding the small wait between the transfers completion and their assertion, right?

**Comment by Dominik1999** [comment]
It happened again in pfs7

here are the logs

http://68.183.70.168/Scenario_player_Logs-pfs7_multiple_payments-1-latest-2019-11-01.tar.gz

Maybe this is caused due to internal routing was used due to a pfs timeout? @LefterisJP

**Comment by LefterisJP** [comment]
Looking at the logs right now @Dominik1999

**Comment by LefterisJP** [comment]
I don't think this can be due to the fallback to internal routing since the asserted amount is smaller and not bigger than expected.

```
Expected sum value \"500000000000000000\" for channel fields \"balance\". Actual value: \"499842499999999997\"
```

Here is the failing assertion: 

https://github.com/raiden-network/raiden/blob/3f76782be89459669cdec8065f2b7b4846113939/raiden/tests/scenarios/pfs7_multiple_payments.yaml#L82-L87

In a similar 100 transfers in bf1 we are waiting for 100 seconds and not only for 10. So this could be the reason.

https://github.com/raiden-network/raiden/blob/3f76782be89459669cdec8065f2b7b4846113939/raiden/tests/scenarios/bf1_basic_functionality.yaml#L232

**Comment by Dominik1999** [comment]
> I don't think this can be due to the fallback to internal routing since the asserted amount is smaller and not bigger than expected

But when the sum on the sender side smaller is, that means he paid more than expected, right?
Which would happen when for some payments there are an additional 3% paid, right?

**Comment by LefterisJP** [comment]
> But when the sum on the sender side smaller is, that means he paid more than expected, right?

Yes that is correct. My bad, did not notice it was on the sender's side.

But still no logs contain a `Could not connect to Pathfinding Service` entry, so there was no fallback to internal routing.

My theory is at the moment on the waiting not being enough. But will look further.

**Comment by LefterisJP** [comment]
## Analysis of the logs provided by Dominik

> My theory is at the moment on the waiting not being enough. But will look further.

Unfortunately that initial theory was wrong.

Here is a small analysis of the logs provided by Dominik [above](https://github.com/raiden-network/raiden/issues/5150#issuecomment-548792519)

The layout of the network is the following:

```
0 <-> 1 <-> 2 <-> 3
^                 ^
|                 |
v                 |
4<-----------------
```

The node addresses are:

node 0: `0xB84D30b5b4C9Cb3c50c59B80B54d7fF175256d6D`
node 1: `0xc9494C4ba5A80F9a707846f5583ABa31032B46db`
node 2: `0x585b40707AD540560023Cf7B2b27066C2005d559`
node 3: `0x4929839a7755eD7045D1fF5748942ddE054073cF`
node 4: `0xbD8F9924d82C93da64786ac1e78008e632258dC3`

token network address: `0xDa1fBc048f503635950058953f5c60FC1F564ee6`


## Checking Node 0's balance from the DB

Final balance of channel 0_1: `489962500000000001`
Final balance of channel 0_4: `9879999999999996`

`489962500000000001` + `9879999999999996` = `499842499999999997`

We expected `500_000_000_000_000_000` so that's a

`500000000000000000`-`499842499999999997` = `157500000000003`

difference. Which is why we see the error.

## Checking `EventPaymentSentSuccess` by node 0 from the DB

The total amount seen as sent by `EventPaymentSentSuccess is indeed `1_500_000_000_000_000_000`
which is `100` x `15_000_000_000_000_000`

but as we also know due to https://github.com/raiden-network/raiden/issues/5186 that amount does not actually equal the locked amount of the Locked transfers.

## Checking locked transfers locked amount sent by node 0 from the DB

Total amount sent: `1500157500000000003`

Ah-hah! There it is. The locked amount in total sent by node 0 contains exactly the extra amount of tokens we were looking for.

Checking the individual locked transfers we see `21`/`100` transfers were "bad" and instead of sending `15000000000000000` they either sent `15007500000000003` or `15007499999999999`.

## Now checking logs of node 0

We now check the logs of node 0 to see why we would make these "bad" locked transfers with the incorrect amounts:


```
{"url": "https://pfs-goerli-with-fee.services-dev.raiden.network", "token_network_address": "0xDa1fBc048f503635950058953f5c60FC1F564ee6", "payload": {"from": "0xB84D30b5b4C9Cb3c50c59B80B54d7fF175256d6D", "to": "0x4929839a7755eD7045D1fF5748942ddE054073cF", "value": 15000000000000000, "max_paths": 5, "iou": {"sender": "0xB84D30b5b4C9Cb3c50c59B80B54d7fF175256d6D", "receiver": "0x062C12c01D0f17fC9eAa33940D994594d91a0182", "one_to_n_address": "0xB3C76048dB9Fe3092a7F88CeEBC580CcbC223A46", "amount": 900, "expiration_block": 1772720, "chain_id": 5, "signature": "0xae4930de26dba3ba687def62f968feac5d4591864c0358a96a03e2f27650d5357127aa43cfa70f0c68cab9c7cd654eb2c2def8e7c4a99f2a3254f319d7f456061c"}}, "event": "Requesting paths from Pathfinding Service", "logger": "raiden.network.pathfinding", "level": "info", "timestamp": "2019-11-01 12:09:20.776333"}
{"first_sync": false, "sync_token": "s138019_112699_0_1_127_1_1_11054_1", "current_user": "@0xb84d30b5b4c9cb3c50c59b80b54d7ff175256d6d:transport04.raiden.network", "event": "Starting handle greenlet", "logger": "raiden.network.transport.matrix.client", "level": "debug", "greenlet_name": "GMatrixClient.listen_forever user_id:@0xb84d30b5b4c9cb3c50c59b80b54d7ff175256d6d:transport04.raiden.network", "timestamp": "2019-11-01 12:09:20.782859"}
{"current_user": "@0xb84d30b5b4c9cb3c50c59b80b54d7ff175256d6d:transport04.raiden.network", "event": "Sync called", "logger": "raiden.network.transport.matrix.client", "level": "debug", "greenlet_name": "GMatrixClient.listen_forever user_id:@0xb84d30b5b4c9cb3c50c59b80b54d7ff175256d6d:transport04.raiden.network", "timestamp": "2019-11-01 12:09:20.783559"}
{"response": {"our_address": "0xB84D30b5b4C9Cb3c50c59B80B54d7fF175256d6D"}, "status_code": 200, "event": "Request successful", "logger": "raiden.api.rest", "level": "debug", "timestamp": "2019-11-01 12:09:20.954410"}
{"routes": ["RouteState (0xB84D30b5b4C9Cb3c50c59B80B54d7fF175256d6D -> 0xbD8F9924d82C93da64786ac1e78008e632258dC3 -> 0x4929839a7755eD7045D1fF5748942ddE054073cF), channel_id: 1472, fee: -2", "RouteState (0xB84D30b5b4C9Cb3c50c59B80B54d7fF175256d6D -> 0xc9494C4ba5A80F9a707846f5583ABa31032B46db -> 0x585b40707AD540560023Cf7B2b27066C2005d559 -> 0x4929839a7755eD7045D1fF5748942ddE054073cF), channel_id: 1468, fee: 0"], "feedback_token": "UUID('517ac31b-2e5c-4d8a-88af-60b656b8cd7a')", "event": "Received route(s) from PFS", "logger": "raiden.routing", "level": "info", "timestamp": "2019-11-01 12:09:21.195414"}
{"node": "0xB84D30b5b4C9Cb3c50c59B80B54d7fF175256d6D", "state_changes": [{"transfer": {"payment_identifier": "1996458958578490982", "token_network_registry_address": "0x62436bbadB629498107278486C2A367FfdFEb2f3", "secret": "<redacted>", "lock_timeout": null, "initiator": "0xB84D30b5b4C9Cb3c50c59B80B54d7fF175256d6D", "token_network_address": "0xDa1fBc048f503635950058953f5c60FC1F564ee6", "amount": "15000000000000000", "secrethash": "0x6fca8280265075fe31fe0078ff827c419c043f90685c62c088638e37d590bf9f", "target": "0x4929839a7755eD7045D1fF5748942ddE054073cF"}, "routes": [{"forward_channel_id": "1472", "estimated_fee": "-2", "route": ["0xB84D30b5b4C9Cb3c50c59B80B54d7fF175256d6D", "0xbD8F9924d82C93da64786ac1e78008e632258dC3", "0x4929839a7755eD7045D1fF5748942ddE054073cF"]}, {"forward_channel_id": "1468", "estimated_fee": "0", "route": ["0xB84D30b5b4C9Cb3c50c59B80B54d7fF175256d6D", "0xc9494C4ba5A80F9a707846f5583ABa31032B46db", "0x585b40707AD540560023Cf7B2b27066C2005d559", "0x4929839a7755eD7045D1fF5748942ddE054073cF"]}], "_type": "raiden.transfer.mediated_transfer.state_change.ActionInitInitiator"}], "event": "State changes", "logger": "raiden.raiden_service", "level": "debug", "timestamp": "2019-11-01 12:09:21.201379"}
```

Above is the place in the logs where the first incorrect amount appears `15007499999999999`. Right before the `ActionInitInitiator` is a PFS request which returns a non-zero fee for the route. It's actually even a negative fee of `-2`

## Further questions

So the big question here is why would the PFS do that? This scenario is supposed to have no fees, right? Also why would the locked amount be bigger than the transfer amount if the fees are negative?

**Comment by Dominik1999** [comment]
so there was a fee deducted even if fees were set to 0?

**Comment by LefterisJP** [comment]
> so there was a fee deducted even if fees were set to 0?

Yeah, the PFS returned non-zero estimated fees for some routes. In the logs above it's `-2`.

@karlb  in rocketchat theorized this may be due to floating point inaccuracies on the PFS side.

He said: 
> I’ll have to dig through the code, but there might be a float(amount) in it somewhere that is used even when no fees are present.

**Comment by karlb** [comment]
Now that https://github.com/raiden-network/raiden/pull/5197 is merged, I get a green PFS7.

**Comment by LefterisJP** [comment]
That's good. So the reason the PFS returned `-2` as per my findings could have been indeed a floating point accuracy. Let's let few nightlies run and then we can close this issue.
