### ISSUE TITLE
Allow disabling internal routing for tests and SP

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden#5184]
As we saw in https://github.com/raiden-network/raiden/issues/5078 internal routing can be really tricky and lead to very hard to debug problems in testing. So I would like to propose:

- Add a way to disable internal routing for the purposes of tests and for the purpose of the SP
- Add specific tests/scenarios that test internal routing

This way we will not have any unexpected surprises and/or hard to debug problems like it happened with #5078

**Comment by rakanalh** [comment]
@karlb @palango could you guys please explain why we fallback to internal routing if the request to PFS fails? I think the better approach would be to fail early as @LefterisJP suggested in case the PFS is unable to provide the route.
Also, from a UX perspective, i think this unexpected behaviour is going to be confusing if i setup to use my own PFS and it fails then Raiden falls back to something else rather than telling me that my PFS is not working.

**Comment by LefterisJP** [comment]
We discussed with Rakan and think it may make sense to disable falling back to internal routing all-together. What do you guys think? Why do we even fall back to internal routing now?

**Comment by karlb** [comment]
I agree that we should not fall back to internal routing. It just makes things more complicated and harder to predict/debug. If someone wants to use the internal routing, it should be done explicitly.

**Comment by LefterisJP** [comment]
I am picking this up.
