### ISSUE TITLE
Test target state event for complete transfer

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#522]
## Problem Definition

TransferCompleted event must be used only after the secret is learned and there
is enough time to unlock the lock on chain.

A mediated transfer might be received during the settlement period of the
current channel, the secret request is sent to the initiator and at time the
secret is revealed there might not be enough time to safely unlock the token
on-chain.

## Tasklist

- [ ] Define a proper event for the success of the target transfer 
  - [ ] Take into account that mediators also need an event for transfer complete / failed
- [ ] Implement the unit test

**Comment by LefterisJP** [comment]
[Here](https://github.com/raiden-network/raiden/blob/b17fda83e938f57ba7fa23c5149074ad9e79acb5/raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py#L505) is the xfailed test

**Comment by LefterisJP** [comment]
@hackaugusto The xfailed test is still there: 

https://github.com/raiden-network/raiden/blob/1ff6e6e22017b16a22fcef0e23535d5c41c617cc/raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py#L696-L705

What exactly is the issue asking for? We now generate an `EventPaymentReceivedSuccess` for the target when we get a valid unlock.

https://github.com/raiden-network/raiden/blob/1ff6e6e22017b16a22fcef0e23535d5c41c617cc/raiden/transfer/channel.py#L2192-L2218

In the `is_valid_unlock()` predicate I don't see:

> must be used only after the secret is learned and there
is enough time to unlock the lock on chain.

So implementing this and adding a unit test is what this issue is for? Am I missing anything?

**Comment by hackaugusto** [comment]
> Do we accept mediated transfers if we enter the settlement period? I don't think we do?
So is this issue still relevant?

We don't anymore, this was true only for the PoC and I believe it changed already with Red Eyes.
