### ISSUE TITLE
Get rid of sys.exit(0) and better raise exceptions

### ISSUE THREAD

**Issue by Dominik2002** [raiden-network/raiden#5563]
## Important
Timebox it (1. we do anyways, 2. only if time and step by step) overall to 2 hours this week - 3 SP

## Goal
We want to spend less time debugging and therefore we need proper exit codes.

## Approach
Look for `sys.exit(X)` to make sure that the node exits with an error code if it is failing. Related to the "Sudden Node Death" Issue #5472 

1. Make sure no sys.exit(0) at all
2. Replace `sys.exits` with `raises` step by step 

Also related to https://github.com/raiden-network/scenario-player/issues/450

**Comment by karlb** [comment]
> Make sure no sys.exit(0) at all

The only `sys.exit(0)` is in `raiden/ui/console.py`, which is ok since it is not part of the normal operation. When going into the Raiden console and exiting it normally, this is not an error and thus really should return with return code 0.

No other parts of raiden do `sys.exit(0)`.

**Comment by LefterisJP** [comment]
Thank @karlb!

So then what should be done for this issue?

```
grep -r "sys.exit(" raiden                                                                                                                                                                                    ST 11   develop 
raiden/ui/cli.py:        sys.exit(1)
raiden/ui/cli.py:        sys.exit(ReturnCode.GENERIC_COMMUNICATION_ERROR)
raiden/ui/cli.py:        sys.exit(ReturnCode.ETH_INTERFACE_ERROR)
raiden/ui/cli.py:        sys.exit(ReturnCode.FATAL)
raiden/ui/cli.py:        sys.exit(ReturnCode.PORT_ALREADY_IN_USE)
raiden/ui/cli.py:        sys.exit(1)
raiden/ui/cli.py:        sys.exit(1)
raiden/ui/cli.py:        sys.exit(1)
raiden/ui/prompt.py:        sys.exit(1)
raiden/ui/prompt.py:        sys.exit(1)
raiden/ui/prompt.py:    sys.exit(1)
raiden/ui/console.py:        sys.exit(0)
raiden/tests/conftest.py:        sys.exit(
raiden/tests/conftest.py:        sys.exit(
raiden/tests/utils/smoketest.py:        sys.exit(1)
raiden/utils/cli.py:            sys.exit(1)
raiden/utils/cli.py:        sys.exit(1)
raiden/utils/cli.py:                sys.exit(1)
raiden/log_config.py:            sys.exit(1)
```
```
grep -r "sys.exit(" raiden | wc -l
19
```

So we got 18 instances of non-zero sys.exit().

It's not clear to me from the description of the issue what should be done so I would like to ask for a small clarification.

Should these instances be:

1. Replaced by `raise ExitWithErrorCode(XX)` exceptions, catch that exception at the top level and up there have a different error code returned per error? So that whoever sees raiden dying can deduce the reason faster just from the return code of the app?

2. The same as above ... apart from not raising an exception and catching it on the top level but exiting right there and then, but as above with a different error code each time.

**Comment by karlb** [comment]
I would
1. raise meaningful errors (not `ExitWithErrorCode` but `BadCliParameter`). Reuse or add new ones as needed. There should be no need to add too many different ones.
2. catch them in cli.py and do `sys.exit(ReturnCode.FATAL)`
3. (optional) create a few new error codes for the most interesting cases

**Comment by LefterisJP** [comment]
> raise meaningful errors (not ExitWithErrorCode but BadCliParameter). Reuse or add new ones as needed. There should be no need to add too many different ones.

Sure that would be cleaner, but I can't say yet whether we would need many new exceptions or not.

> 3. (optional) create a few new error codes for the most interesting cases

I would suppose that the last point is why the issue was made, no? To be able to deduce what happened simply from Raiden's return code.

Also another question. What is the benefit of raising an exception and catching it in cli.py and sys.exit() from there instead of sys.exit() directly where you would raise the exception? I mean sys.exit() also raises an exception itself (`SystemExit`)

**Comment by karlb** [comment]
The issue was mainly made because we had sys.exit(0) in the wrong place which caused all kinds of wrong assumptions why our processed died. Having the exits in one place seems helpful to provide a consistent set of return codes, but I see your point that it is technically mostly the same.

**Comment by LefterisJP** [comment]
> The issue was mainly made because we had sys.exit(0) in the wrong place which caused all kinds of wrong assumptions why our processed died.

@karlb As you also stated above there is currently only one  `sys.exit(0)` and that does not hurt at the moment. I guess you had in other places but already removed them, right?

> Having the exits in one place seems helpful to provide a consistent set of return codes, but I see your point that it is technically mostly the same.

I see. Thanks for explaining your view! I wanted to just see what was the thinking of raising + catching in cli.py + exiting instead of simply exiting. 

So the benefit would be:

- Having the exits in one place is more helpful to provide consistent error codes.

On the other hand having a common `raiden/error_codes.py` module with proper docstrings per error code would achieve the same result, no? And this way when reading the code it would be just one grep to find the originating reason for each error code. Plus we would not need to introduce any extra exceptions.

Does this make sense to you as an approach?

**Comment by karlb** [comment]
> @karlb As you also stated above there is currently only one `sys.exit(0)` and that does not hurt at the moment. I guess you had in other places but already removed them, right?

Not by me, but at least one other case of `sys.exit(0)` has been removed.

> On the other hand having a common raiden/error_codes.py module with proper docstrings per error code would achieve the same result, no? And this way when reading the code it would be just one grep to find the originating reason for each error code. Plus we would not need to introduce any extra exceptions.
> 
> Does this make sense to you as an approach?

Exceptions feel more natural to me and would allow catching specific ones (e.g. in tests), but I guess either way will work. I'm no authority on this, so use your own judgement.

**Comment by Dominik2002** [comment]
hey there, I did not read all the texts. But if there is doubt about the implementation, just ask augusto

**Comment by LefterisJP** [comment]
@karlb 

> Exceptions feel more natural to me and would allow catching specific ones (e.g. in tests), but I guess either way will work. I'm no authority on this, so use your own judgement.

I dislike the overuse of exceptions in Python but the argument you are making here is a good one about also having the ability to catch them in tests.

And thinking on it a bit further there could be parts in the code which would require catching the exception and exiting in some of the calls of a function but doing something else in others.

So perhaps in this case using exceptions give us more options in the future and this is what I will go with.

@Dominik2002 thanks for your input but I don't think it's needed at this point.
