### ISSUE TITLE
Specify design for backpressure mechanism for sending messages - Payments take way too long

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5637]
We need a backpressure mechanism to not send the same message over and over again in case the transport layer or a certain node is clogged. 

Goals for this week
- [ ] Please create an overview of 2-3 different mechanism and research how others do it 
- [ ] Set up a meeting with team and discuss approaches
- [ ] When team has decided, we create follow up issue about implementation

**Comment by ulope** [comment]
Related #2385

**Comment by hackaugusto** [comment]
A rough outline would be (I'm not proposing any algorithm, we should just use something out-of-the-shelve like C2TCP or any other congestion algorithm):

- Increment a counter on `enqueue`, for each message that is queued.
- Decrement the counter once the message is confirmed
- Use the rate of change of these values to determine the amount of messages that can be sent

Note: For UDP we had throttling, however i don't think that will be good enough here since the throttling doesn't take into consideration the other connections our partner has, and it may result in increase latency because the node is being overloaded.

**Comment by ulope** [comment]
Questions and ideas (from chat):
- Get rid of the per-message retry timers
- Keep track of the per-peer response time (running average of what period?)
  - Reduce retries accordingly (how? exponential, linear?)
- What about new messages, should they still be immediately sent at least once?
- Doesn’t this just degrade to effectively having very long retry intervals in most cases

**Comment by Dominik1999** [comment]
- [ ] Please create an overview of 2-3 different mechanism and discuss with team (set up meeting)
- [ ] When team has decided, we create follow up issue about implementation

**Comment by Dominik1999** [comment]
> Questions and ideas (from chat):
> 
> * Get rid of the per-message retry timers
> * Keep track of the per-peer response time (running average of what period?)
>   
>   * Reduce retries accordingly (how? exponential, linear?)
> * What about new messages, should they still be immediately sent at least once?
> * Doesn’t this just degrade to effectively having very long retry intervals in most cases?

What is the status of those questions?

**Comment by konradkonrad** [comment]
> Note: For UDP we had throttling, however i don't think that will be good enough here since the throttling doesn't take into consideration the other connections our partner has, and it may result in increase latency because the node is being overloaded.

I was about to suggest a similar approach, e.g. token bucket throttling (allows for full burst speed). I don't fully understand your reasons against it. Can you expand on 

> doesn't take into consideration the other connections our partner has

why are the partner connections relevant?
and
> result in increase latency because the node is being overloaded.

who's node is overloaded by what?

**Comment by hackaugusto** [comment]
> I was about to suggest a similar approach, e.g. token bucket throttling (allows for full burst speed). I don't fully understand your reasons against it. Can you expand on

The problem can be in the receiver and not in the sender. Relying on the sender to be well behaved will work some times, but not always. IMO the throttle should be implemented on both sides.

> why are the partner connections relevant?

The problem is not only the transport itself, but the CPU usage of the sender and the target. If the transport is healthy but the target is not, having a global throttle is not good enough, it has to be per recipient address.

> who's node is overloaded by what?

The recipient. Overloaded by its partners. Consider a start topology, the mediator is at the center with `n` connections, the other nodes are in the edge with `1` or `2` connections, the load of the mediator is significantly higher than the load of the edge nodes. The problem here is not the transport layer, but the mediator is receiving so many messages, and the processing of the messages themselves is taking so much time, that everything is brought down to a crawl. If the edges don't throttle themselves, they are going to make things worse as time goes by.
