### ISSUE TITLE
test_transport_does_not_receive_broadcast_rooms_updates is flaky

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#5663]
`test_transport_does_not_receive_broadcast_rooms_updates` is flaky:

- https://circleci.com/gh/raiden-network/raiden/102420#tests/containers/1

**Comment by fredo** [comment]
I looked into this issue a couple of days ago and Ulo and me have a theory why it might be flaky. 

Since sync is a long polling mechanism it is not enough to just change the internal filter in line [1178](https://github.com/raiden-network/raiden/blob/d944ebfc3654081cac5ea4c9782c7f5412c7b6c9/raiden/tests/integration/network/transport/test_matrix_transport.py#L1168-L1186)

Changing the filter only becomes effective with the next request which is triggered either by the sync timeout (20s) or by the server providing a response which happens when an event for the user arrives. 

In line [1186](https://github.com/raiden-network/raiden/blob/d944ebfc3654081cac5ea4c9782c7f5412c7b6c9/raiden/tests/integration/network/transport/test_matrix_transport.py#L1168-L1186) the test waits for the current sync to be finished. It might be the case though that the current sync already started before the filter_id was changed. In this case the filter for Transport2 was not effective on the call.
