### ISSUE TITLE
We change SERDE from to_checksum to address.hex()

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5679]
## Problem
In our SERDE we use `to_checksum_address`, which is very slow, compared to '0x'+ `address.hex()` 270x the speed. 

## Consequences
But this would mean that the JSON messages we send change slightly (using lowercase addresses instead of checksummed ones). So the Light Client would need to encode and decode in hexadecimal and not checksum anymore. No other consequences

**Comment by Dominik1999** [comment]
- [ ] change Docs
- [ ] change Spec

**Comment by christianbrb** [comment]
@kelsos @andrevmatos Could you paste your arguments here.

@Dominik1999 How is the validation of the addresses within the messages done?

Don't really know, if it is relevant, but the original discussion regarding EIP-55 is [here](https://github.com/ethereum/eips/issues/55).

**Comment by kelsos** [comment]
This is not an argument per se, mostly it is my understanding and thoughts on the matter, after reading the discussions and talking to Augusto so far.

The reasoning behind this change is clear and I am aware that this is of high importance for the core team to progress with Alderaan. I already discussed with Augusto and did my small research into the EIP55 and I understand that it makes more sense in the edges of the system where you have interaction with the users (it will still be there). So I don't think that conforming to EIP55 matters for a wire protocol that targets machine to machine communication.

I can also understand that this is an easy win with huge performance gains, that has a minimal cost on both the Core and Light Client.

Having said that, after reading everything in the discussion so far I can't help but wonder about under which conditions it is reasonable to break the protocol.

My understanding so far has been that a protocol should be independent of specific languages, tools or libraries. But in this case, the protocol change is caused due to `to_checksum_address`, a python utility in a third-party library, having an abysmal performance. 

What happens if tomorrow another dependency has some unforeseen limitations? What if we find TypeScript limitations or an issue with one of Light Client's dependencies, is it ok to break the protocol then?

To be honest I have no idea if this contributes anything to the discussion but here it is. 

Thank you very much for your hard work on improving the client :)

**Comment by andrevmatos** [comment]
My arguments against it are mostly three:
1. **Consistency:** I understand EIP55 is more relevant for user input and not for m2m comms, but these are both serialized, deserialized and validated as addresses, I don't see an specific in-protocol reason for breaking this consistency at **edges** of system, with one _face_ **requiring** eip55 format and other **requiring** lowecase, just because it's towards another client.

    At most, I could understand relaxing this **requirement** on all edges, and accepting lowercase, uppercase and checksummed addresses, deseralized to whichever internal format each client desires, and serializing to whichever of the 3 performs better on each client, with protocol requiring other implementations to accept any of them.

2. **Reasonability:** same as kelsos wrote above: I know protocol compatibility is not a priority at this point in time, but there's already a 2nd client implementing it, so we should be reasonable about why to break it, e.g. intrinsic protocol ineficiencies. A **slow 3rd party utility function** is not a good reason for it IMO. Besides it, python **implementation** may benefit it, but light-client's will be hindered (even though very slightly), as it'll need to lowercase internally-checksumed address strings upon serialization. When does one client is worth more than other, to justify such breaking change? Who balances and decides on it?

    Notice I'm not using the performance impact on light client itself as an argument, as I believe it to be negligible (although present), but as an argument to exemplify that what benefits an **implementation** may impact negatively others, so implementation shouldn't be enough of a reason, and actual protocol correctness/consistency to be.

3. **Alternatives:** IMO, the protocol should be touched as a last resort, after trying implementation fixes for implementation issues. I'd like to see profiling arguments before and after at least the following suggestions are implemented and tested:
- Reduce function usage to bare minimum, using it only on messages serialization
- Cache (only important) addresses or messages
- Replace it with fast implementation (C lib/extension/bindings, etc)

    While there's still options to properly fix implementation, working around such issues by changing protocol shouldn't even be considered.

**Comment by Dominik1999** [comment]
Thank you @andrevmatos and @kelsos for that very concise style! 
_Just a side note: I highly appreciate the numbered list of points with bolded points, it is very easy to read, to comprehend and to react._

I understand as the main point here what you write in **Resonability**. So who decides when and how to change the protocol. My understanding atm is, 

- the python client has the goal to get three green scenario runs
- we change whatever is reasonable to get those green runs
- we do not have any external dependency to customers or clients, without dependencies it seems complex enough for us
- we understand that this is a pain in the ass for the Light Client team, so we try to communicate changes upfront

As long I do not hear anything differently from Stefan / Kamal, we will do it that way and also change the protocol when it seems reasonable for us.

As an example, this discussion alone, I took notes just for my time, took me 3 hours writing and talking to Augusto, Karl, Christian, Stefan and you guys. ATM this is not time well spent, compared to the time the change would take. 

+++++

To your points in particular (I do not want to left those points regarding content not process aside):

_Please correct me when I am wrong: Only 1. is a contextual point against that change, whereas 2.goes against the process of changing protocol and 3. shows alternatives._ 

1. **Consistency:** You are right, there is no in-protocol reason for breaking the protocol. There cannot be, right? The reason to change protocol must lie outside the protocol. In our case, it is performance. So we simply put performance over consistency after evaluating the consequences.

2. **Reasonability:** That seems not to be a point about the change but about the process. Implementing this specific change would take less time than creating that post for you if I am not mistaken. However, I see that this process, - we change what we want - is a bad process from your perspective. I am sorry and we try to make it as easy as possible. 

3. **Alternatives:** This seems not to be a point against this implementation but alternatives for the implementation. This is highly appreciated. It would be nice to have you here in the team for a while :)

**Comment by konradkonrad** [comment]
Note: there is another optimization waiting in 

https://github.com/raiden-network/raiden-contracts/blob/6f082cf490dad726918a157cb16dbd426aec8620/raiden_contracts/utils/proofs.py#L27-L44

which is called from 

https://github.com/raiden-network/raiden/blob/7902a9559ea4498be74504e8283d1f9f733eafa8/raiden/utils/packing.py#L33-L41

essentially adding a totally unnecessary roundtrip of bytes->hex->bytes encoding for addresses.
