### ISSUE TITLE
Filter out presence information from the global rooms

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5774]
Because of the frequent amount of tests, the global rooms used to exchange messages with the MS, PFS, etc. reaches a very high user count (currently `13644`). Because of this, under some circumstances the synapse server will take a long time to compute the response for the first unfiltered sync, more than 40 seconds. This results in failures with the `MatrixSyncMaxTimeoutReached` exception.

The fix is to filter out the presence information from the global rooms, they are not needed since we also have presence information for the users that we have a room with.

- [ ] Filter the presence information of the *global rooms*, only download the presence data of the private rooms.

**Comment by ulope** [comment]
A slight complication:
The filter spec only allows global presence event filtering, that means we can't just exclude presence events for users from the broadcast rooms.

Therefore we need to dynamically update the filter every time a new user is added for an address. 
Also we need to listen for membership change events on the discovery room since we will no longer be able to discover roaming users via the presence events (since they will be filtered out).

**Comment by andrevmatos** [comment]
We're working on a solution to it at https://github.com/raiden-network/light-client/pull/918
With _lazy members loading_, we can filter out members state from global rooms, while still receiving presence events updates for users on these rooms.

**Comment by palango** [comment]
@ulope Can you go a bit in detail what you mean with *"membership change events on the discovery room"*

@andrevmatos I'm not following, can you also go into a bit more detail.

**Comment by andrevmatos** [comment]
On Matrix syncing, there's 2 ways to get informed about users, which we need to keep in mind:
- on initial sync, we get the list of users as `membership` room state. This is not related to presence, but user info. This is probably what is slowing down a lot initial sync for you guys, and can be filtered out in 2 ways:
  - filtering out room state completely with `not_rooms`, but then you can't rely on user being part of room's `_members` or alike
    - notice this may possibly require checking if user data is present, and fetching it explicitly from user's profile if e.g. `displayName` is missing upon any event (e.g. presence) for that user. This may not be a problem for users we share a non-filtered room with (e.g. partners)
  - enabling [lazy members loading](https://matrix.org/docs/spec/client_server/r0.6.0#lazy-loading-room-members), which skips sending huge `membership` data on initial sync, but sends any user metadata together with any event for that room related to that user
- **presence** events are different and a bit tricky:
  - they're **not** rooms events, but global events, **but** they're affected by rooms: we only receive presence events from _users of interest_, which are mainly users we've a room with (including global rooms). It may be required to test if filtering room state out (e.g. global rooms as per above) affects or not this _users of interest_ list.
  - they may be skipped on initial sync, and explicitly fetched for whitelisted/users of interest, but it's wise to not filter out on next syncs, as these events are required to know about roaming users

We're implementing all of above in the Light-Client on the PR linked above, if it may be useful for you somehow. It's still WIP, and we're testing the edge cases above, but the current form already made initial and looping sync calls fall from tens of MBs to a few KB each, while keeping presence events intact.

**Comment by ulope** [comment]
@andrevmatos Yes, lazy members is definitely something else that we should be doing. But this issue is specifically about the presence updates. Since we don't keep local state in non-light Raiden we get presence updates for all (currently) ~13k users during the first (or rather second) sync. 
Generating that response takes ~40s on the server and results in 3MB of json.

@paul Changes in room memberships are pushed as state events (in contrast to regular events, e.g. messages). These are delegated to state listeners (`Room.add_state_listener`). 
Newly added members should be forwarded to the `UserAddressManager` so it can decide if it's a new user for a known address (similar to what its doing now in `_presence_listener`).

**Comment by andrevmatos** [comment]
Yes, I know, just wanted to mention here because of the described relationship, as Paul asked to give a more detailed explanation of our findings/approach.

**Comment by ulope** [comment]
Obsolete since #5931 was implemented.
