### ISSUE TITLE
Fix race condition on whitelist and sync

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#5859]
## Abstract

ATM invites are processed automatically, this is done to fix race conditions were the invite would arrive before the node performed the whitelisting. This however does not remove a race condition with receiving messages in the room and the whitelisting. 

## Motivation

The only downside of this race condition is that it will increase latency of the first few messages, it can be interesting to remove this unnecessary latency.

## Specification

On whitelist, the node should check if a room already exists, and if it does, then it should retroactively fetch the existing messages. (Thanks @fredo for the solution)

## Backwards Compatibility

This is an internal change, it should be backwards compatible.

**Comment by fredo** [comment]
Should we rely on the server storing the messages and fetch them? And if yes until what point in time (the server purges the history from a given point). 

The other solution would be waiting for the other node to retry the message. This could be slightly more less performant but does not rely on the server. 

Since this case only happens in a predicted short time frame (the messages are being sent before the whitelist) this looks to me only as a slight optimization not to wait for the next retry by fetching the messages retroactively. 

What do you think? (I think we discussed that already loosely)

**Comment by ulope** [comment]
@fredo your suggestion is basically #4110

**Comment by karlb** [comment]
I assume this is outdated due to the major changes in how we use matrix.
