### ISSUE TITLE
We need a clear rule when to send a PFSFeeUpdate and go with it

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#5897]
## Abstract

At the moment PFSFeeUpdates are being sent with the following state changes:

https://github.com/raiden-network/raiden/blob/3ad70315695445c2a4f05966a98098bbfe41ed5c/raiden/raiden_service.py#L738-L748

and not with any event.

This seems not to follow a clear rule, e.g. sending such an update only with confirmed BC events [is this statement even true? I cannot see a general rule, but maybe there is?]. Furthermore we should make sure that PFSFeeUpdates are being sent by both partners triggered by the same event or state_change. 

- [ ] research and document solution for that and put in the spec
- [ ] get approval for suggested spec from @hackaugusto or @karlb 
- [ ] implement change, change two lists  of events and state changes 

## Motivation

Not going with a certain rule might lead to race conditions.

## Specification

to be specified. 

## Backwards Compatibility

Should be backwards compatible.

**Comment by Dominik1999** [comment]
+++ this is not a blocker for the release ++
- [ ] research and document solution for that and put in the spec
- [ ] get approval for suggested spec from @hackaugusto 
- [ ] implement change, change two lists  of events and state changes

**Comment by karlb** [comment]
Here's my try at justifying the current state. What do you think @palango @hackaugusto? If this sounds reasonable, I'll put it into the spec.

---

### When to send `PFSFeeUpdate`s

The fees depend on the total channel capacity across both participants, so whenever that changes, a `PFSFeeUpdate` should be sent. The capacity changes when participants deposit to or withdraw from a channel. For both of these actions, there is a time uncertainty between the initiation and the confirmation of the action. The updates should assume the lower capacity during time, since it is the safe thing to do and it matches the node's internal state.

#### Deposit

With this pessimistic approach, the update must be sent when the blockchain confirms the deposit. 

#### Withdraw

The update will be sent when the withdraw is successfully initiated (`ReceiveWithdrawRequest` on partner and `ReceiveWithdrawConfirmation` on the withdrawing participant). If the withdraw succeeds on-chain, this fee remains correct. In the unlikely case that the withdraw never reaches the blockchain, we have to revert back to the old fee schedule by sending a new fee update on the `ReceiveWithdrawExpired` state change.

**Comment by palango** [comment]
> `ReceiveWithdrawConfirmation` on the withdrawing participant

Isn't the capacity already locked when sending the request to the partner?

**Comment by karlb** [comment]
> > `ReceiveWithdrawConfirmation` on the withdrawing participant
> 
> Isn't the capacity already locked when sending the request to the partner?

Not sure, I haven't found the code to do that where I expected it for neither of them:
https://github.com/karlb/raiden/blob/d99ec08745cad3239d17003d54062f08ddedb8ff/raiden/transfer/channel.py#L1653-L1691
https://github.com/karlb/raiden/blob/d99ec08745cad3239d17003d54062f08ddedb8ff/raiden/transfer/channel.py#L2011-L2051

**Comment by karlb** [comment]
Looking at the code again, the [addition of the element to `withdraws_pending`](https://github.com/karlb/raiden/blob/d99ec08745cad3239d17003d54062f08ddedb8ff/raiden/transfer/channel.py#L1673) is locking the capacity, so you are right that it happens in `send_withdraw_request`. So the fee update would happen in

```
PFSFeeUpdate (withdrawer and partner)
SendWithdrawRequest (withdrawer)
ReceiveWithdrawRequest (partner)
SendWithdrawExpired (withdrawer)
ReceiveWithdrawExpired (partner)
```

But I would stay with the general reasoning I wrote above. Does this sound reasonable?

**Comment by palango** [comment]
> Does this sound reasonable?

It does.

- For the deposit it would be `ContractReceiveChannelDeposit`
- Payment events should be handled correctly, right?

**Comment by karlb** [comment]
> For the deposit it would be `ContractReceiveChannelDeposit`

Yes, this is what I mean with the first entry in my last comment. Fixed.

- Payment events should be handled correctly, right?

Payments don't change the fee schedule, so they work fine with regards to the `PFSFeeUpdate`. I haven't checked the PFSCapacityUpdate in detail, but at least the current code contains reasoning for why not to send it on some state changes:
```python
PFS_UPDATE_STATE_CHANGES = (
    ContractReceiveChannelDeposit,
    ReceiveUnlock,
    ReceiveWithdrawRequest,
    ReceiveWithdrawConfirmation,
    ReceiveWithdrawExpired,
    ReceiveTransferCancelRoute,
    ReceiveLockExpired,
    ReceiveTransferRefund,
    # State change | Reason why update is not needed
    # ActionInitInitiator | Update triggered by SendLockedTransfer
    # ActionInitMediator | Update triggered by SendLockedTransfer
    # ActionInitTarget | Update triggered by SendLockedTransfer
    # ActionTransferReroute | Update triggered by SendLockedTransfer
    # ActionChannelWithdraw | Upd. triggered by ReceiveWithdrawConfirmation/ReceiveWithdrawExpired
)
PFS_UPDATE_EVENTS = (SendUnlock, SendLockedTransfer)
```
Errors in that list would also be less severe, as superfluous entries would do no harm (apart from wasting resources) and omitted entries won't cause too many problems since there's a high likelyhood that another updated will be send soon due to one of the other state changes/events.

Any potential improvements on the `PFSCapacityUpdate` should be the topics of a separate issue.
