### ISSUE TITLE
Add API Endpoint to shutdown raiden

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6113]
## Abstract
If Raiden is started other than the CLI it might be difficult to shutdown Raiden easily (especially for non-technical users). This could happen if Raiden is started by the wizard. 

## Motivation
Non-technical users are controling raiden by some UI (e.g. the WebUI). The user should be able to shut raiden down via an exposed endpoint in order to have a controlled shutdown. 

## Specification

- [ ] Provide an RestAPI Endpoint to shut raiden down gracefully
- ~~Take security measures into account that not everybody can shutdown the node~~

**Comment by karlb** [comment]
We could print a shutdown code as a parameter for the WebUI, e.g. `http://localhost:5001/#shutdown_code=ADHLnecai2321`. Then the WebUI can send that back when calling the shutdown.

But it seems wrong to me to protect a shutdown call more strictly than payment calls, since the latter is a more interesting target for malicious uses. It could also suggest to people the REST API is protected in some way.

Therefore I would leave the protection out and just ask people nicely not to shut down nodes in a workshop setting (and/or maybe restart then automatically on exit).

**Comment by ulope** [comment]
Although I originally brought this up, the discussion we had in the standup call convinced me that we should just add the plain endpoint for now and then think about proper API access controls after the release.
