### ISSUE TITLE
MFEE2 fails at the transfer 'Target does not have a channel with sufficient capacity'

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6149]
On Goerli MFEE2 fails with 

`{"result": "scenario error", "message": "HTTP status code \"409\" while fetching http://127.0.0.1:55127/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x0f551F07b686EE1353ACE29e3436fB1c3a98aB30. Expected 200: {\"errors\": \"Payment couldn't be completed because: PFS: Target does not have a channel with sufficient capacity ([0] < 10000) (2201)\"}", "event": "Run finished", "logger": "scenario_player.main", "level": "error", "timestamp": "2020-05-12 09:35:50.693841"}`

[scenario-player-run_mfee2_proportional_fees_2020-05-12T09_28_19.log](https://github.com/raiden-network/raiden/files/4614708/scenario-player-run_mfee2_proportional_fees_2020-05-12T09_28_19.log)

**Comment by Dominik1999** [comment]
works for me locally. I will test it again with the remote servers once https://github.com/raiden-network/scenario-player/pull/559 is done

**Comment by hackaugusto** [comment]
```
complete tasks:
  "task": "<OpenChannelTask: {'from': 0, 'to': 1, 'total_deposit': 100000}>",
  "task": "<OpenChannelTask: {'from': 1, 'to': 2, 'total_deposit': 100000}>",
  "task": "<OpenChannelTask: {'from': 2, 'to': 3, 'total_deposit': 100000}>",

  "task": "<WaitBlocksTask: 2>",

started tasks:
  "task": "<TransferTask: {'from': 0, 'to': 3, 'amount': 10000, 'expected_http_status': 200, 'identifier': 150561102211000001}>",

failed task:
  {\"errors\": \"Payment couldn't be completed because: PFS: Target does not have a channel with sufficient capacity ([0] < 10000) (2201)\"}

**Comment by hackaugusto** [comment]
My assumption here is that the PFS didn't see the deposit done by node 2 to the channel 2-3 after the wait of 2 blocks, which is usually sufficient (so the scenario is flaky). The only way to reliably fix this is to add extra coordination in the scenario player, it has to:

- Wait for all the Raiden nodes see all the channel open events (the REST API can only wait for the local node's state to be updated). This makes sure the local graph used for path validation is properly updated. (This can be weakened to only the nodes starting a payment, since mediators and target don't validate the routes, the next requirement would ensure the channels exist). 
- Make sure every party for every channel sees all deposits. This makes sure that once a node receive a locked transfer the balance will be available for the transfer proceed. (same problem as above, the REST API can only guarantee the local state).
- Make sure every PFS sees every channel open and channel deposit. This make sure that once the route is requested from the PFS the server is synchronized with the blockchain and it will be able to find the route. (This can be weakened for only the PFS used by initiator nodes, since the other PFS servers don't matter)

The changes above can only be done at the scenario player, since that is the only node that knows what has finished across the whole network.

As a work around, since the changes above can take some time, we should just increase the wait blocks, this however will still be flaky and may eventually fail again.

**Comment by Dominik1999** [comment]
That looks like the problem that the Scenario Player somehow tries to coordinate processes as the central authority in a decentralized network. 

Should we increase the `wait_blocks` to 5? Currently it is at 2

**Comment by hackaugusto** [comment]
@Dominik1999 doing the change manually is very error prone, I added it to the scenario player:

https://github.com/raiden-network/scenario-player/pull/563

**Comment by Dominik1999** [comment]
you are a fucking monster @hackaugusto

**Comment by Dominik1999** [comment]
can we close this?
