### ISSUE TITLE
Implement WebRTC for sub-second payments 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden#6198]
## Abstract

We want to use WebRTC to be used in Raiden to allow for sub-second payments (with 1 mediator). As a fallback, if WebRTC does not work at any given moment, the Raiden Client should use Matrix. WebRTC is already built in the Light Client. 

## Motivation

Most promising Raiden use cases are in the space of M2M micro-payments. Those payments are most likely required to be sub-second.

## Specification

This needs to be specified. As a basis we could use https://github.com/raiden-network/raiden/pull/6028/files

## Implementation plan

Please create a plan on how to implement it. This plan should contain small steps with the goal of having sub-second payments in a mediated transfer with one mediator. Goal is to have a demo at the 17th of June

## Backwards Compatibility

Most likely backwards compatible

**Comment by hackaugusto** [comment]
Notes:

- STUN is sufficient for a start, since if direct P2P communication fails the messages can be proxied through Matrix. @andrevmatos said TURN over the servers is faster, but that has to be measured and can be implemented on a second step

**Comment by andrevmatos** [comment]
Just to clarify, in my informal measures, TURN over coturn server is faster than Matrix (with its http /sync roundtrips), but of course slower than P2P STUN, which is the "standard" mode for WebRTC. But, since most (90%+ according to webRTC statistics I saw around) STUN connections should succeed, it shouldn't be a problem to skip TURN (with its additional server requirement) and have Matrix room as the only fallback.

**Comment by karlb** [comment]
Closed in favor of (mostly done) sub issues.
