### ISSUE TITLE
 ContractDiscovery initialization failed.

### ISSUE THREAD

**Issue by gguoss** [raiden-network/raiden#625]
## Only For Bugs
``` python
     blockchain_service = BlockChainService(
         privatekey,
         decode_hex(registry_contract_address),
         host=rpc_host,
         port=rpc_port,
     )

     discovery = ContractDiscovery(
         **blockchain_service**,
         decode_hex(discovery_contract_address)  # FIXME: double encoding
     )
```
ContractDiscovery used  blockchain_server as parameter to init. howerver, ContractDiscovery's parementer is node_address as follows:
``` python
class ContractDiscovery(Discovery):
    """ Raiden node discovery.

    Allows registering and looking up by endpoint (host, port) for node_address.
    """

    def __init__(self, node_address, discovery_proxy):
        super(ContractDiscovery, self).__init__()

        self.node_address = node_address
        self.discovery_proxy = discovery_proxy

    def register(self, node_address, host, port):
        if node_address != self.node_address:
            raise ValueError('You can only register your own endpoint.')

        endpoint = host_port_to_endpoint(host, port)
        self.discovery_proxy.register_endpoint(node_address, endpoint)
```
When you run command as follows:
```
raiden --eth_rpc_endpoint 127.0.0.1:8545 --registry_contract_address 79eafd0b5ec8d3f945e6bb2817ed90b046c0d0af --discovery_contract_address 2ce636d6240f8955d085a896e12429f8b3c7db26
```
will raise error(**'You can only register your own endpoint.'**)
### System Description
raiden v0.0.5, geth 1.5.8-stable-f58fb322, solidity 0.4.12-develop.2017.5.5+commit.2d89cfaa.Linux.g++

**Comment by LefterisJP** [comment]
@gguoss Thank you for the report and for taking the time to look at it.

The code you refer to is from the [`tools/`](https://github.com/raiden-network/raiden/blob/master/tools/scenario_runner.py) directory, which contains helper scripts to help us with testing and deploying.

As we are more focused on finishing the core code right now it's natural that directory to have fallen behind due to lack of usage.

The `You can only register your own endpoint.` is not related to that code. It is telling you that you are trying to register a different address from the one you set as your using address when you start raiden.

Is this on a local testnet? Do you interact with the CLI at all or you get it only if you type:
`raiden --eth_rpc_endpoint 127.0.0.1:8545 --registry_contract_address 79eafd0b5ec8d3f945e6bb2817ed90b046c0d0af --discovery_contract_address 2ce636d6240f8955d085a896e12429f8b3c7db26`

**Comment by gguoss** [comment]
@LefterisJP Thx.
yes, its local testnet.
I'm running used follow steps:	
1.python tools/config_builder.py full_genesis > mycustomgenesis.json
2.geth --datadir /tmp/privategeth init mycustomgenesis.json
3.geth --datadir /tmp/privategeth --networkid 123 --nodiscover --maxpeers 0 --rpc --minerthreads 1 --etherbase c13f2e8e9c92d81de806023d68cc64fe85bf6740 --mine
4.raiden --eth_rpc_endpoint 127.0.0.1:8545 --registry_contract_address 79eafd0b5ec8d3f945e6bb2817ed90b046c0d0af --discovery_contract_address 2ce636d6240f8955d085a896e12429f8b3c7db26

interact with the CLI select address:c13f2e8e9c92d81de806023d68cc64fe85bf6740

I don't know endpoint is node address or account address?

**Comment by bogdanbatog** [comment]
@gguoss thanks for instructions - it's also useful to get started. 

@LefterisJP I'd like to help, but as I'm just getting familiar with the design and the codebase, i could use some pointers. Are there any simple issues that I could start with? Also, I suggest using `easy` or `help_wanted` labels to make it more clear for contributors.

**Comment by czepluch** [comment]
@bogdanbatog for easy issues we use https://github.com/raiden-network/raiden/labels/low_hanging_fruit

**Comment by LefterisJP** [comment]
This should already be fixed for the raiden client.  (https://github.com/raiden-network/raiden/commit/44179fc92da583e5a1aeeae5e351859e47bf45b1)
The tools directory is indeed outdated but not something we support at the moment.
