### ISSUE TITLE
Settled channels are shown in list channels API

### ISSUE THREAD

**Issue by ischepin** [raiden-network/raiden#6444]
## Issue checklist

To help us more easily debug your issue please check the boxes for which requirements for safe usage or Raiden were followed:

- [x] The Ethereum node was always up to date with the chain tip and never stopped running.
- [x] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [x] The Ethereum account used by Raiden always had sufficient ETH.
- [x] The Raiden DB that exists by default at ~/.raiden was never altered or deleted.
- [ ] The Raiden node was never restarted. If yes please provide more info.
- [x] The ethereum node was not switched while Raiden was running.
- [x] The Raiden REST API is protected from public access.

## Problem Definition
Settled channels are shown as opened in list channels API (GET api/v1/channels).

### Steps to reproduce:
1. Open a channel in any token network
2. Close a channel and wait for it to settle
3. Restart raiden node
4. Retrieve a list of open channels from the node

Whats even worse, if I try to close this channel again using webui or API the raiden node will crash (`raiden.exceptions.RaidenUnrecoverableError: The channel was not open at the provided block (0xcf07c12f24201113c376f22702fc60e382336bbc10a66caa5679e4286d54b1c5). This call should never have been attempted.`

[raiden-debug_2020-08-05T11:30:36.186629.log](https://github.com/raiden-network/raiden/files/5028122/raiden-debug_2020-08-05T11.30.36.186629.log)

### System Description
Network: ropsten
ETH node: infura.io
Raiden version: `raidennetwork/raiden:latest` docker image (`raidennetwork/raiden@sha256:6ffb7356519464d5e1e7a0dedecbe136c9ff3f2022b6c13b1ba84a200049ee9c`)
```

**Comment by Dominik1999** [comment]
Thank you @ischepin for that bug, that is indeed a nasty one. 

So your node `
0xcbe2a5e0ed585824e435c570bd8c89ed382f283f` 
- opened https://ropsten.etherscan.io/tx/0xba113f15ffb40ef94a66e375a78331e67dabdd0ba735151b4d0cb2697a407416
- deposited https://ropsten.etherscan.io/tx/0x487f486dfe0390bd4d6f07357616e551cb1f204604b8b5f26f7a7afc5347470f
- closed, see https://ropsten.etherscan.io/tx/0x0106a8f1002dd8ad648f58ebca3512529d2b2bcc3fd8afbc384514c7640f3a62) channel Nr. `6` 

and everything worked so far - the transactions were successful on the blockchain. 

Then the Raiden Client was restarted (or started) and fetched all the blockchain events. Because Ropsten is not used for Raiden there are not so many events. So the Raiden Clients decode and dispatch all events in batches and not interleaved. However, the decoding logic for the channel close depends on the dispatch of the channel open.

We will now decode and dispatch per item instead of batch-wise.
