### ISSUE TITLE
Call events can not be sent in Rooms with more than two users

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#6526]
According to the spec and after testing, I found out that m.call.* events are filtered out by the synapse server if

There are other than exactly two users in a room
The receiving participant is offline
This leads to a problem in the current room design.

It is possible that multiple users are in a room since roaming between the Matrix servers in a federation result in creating a new user for each server. If a user ever roams and gets invited into an existing room, signalling via matrix wont work anymore.

After discussing with @ulope and @andrevmatos there are two possible solutions

solution 1
Signalling could be send as pure messages (m.room.message) and the transport can check for these messages, filter them and act accordingly.

solution 2
For each user pair a new room is going to be created. For this to happen, the lower address should not invite any user of the partner's address into one room but creating new rooms for each user. Performancewise this would be a little bit lower since a new room must be created for each new roaming user.
Also the number of rooms would increase but since we do not care about room history this should not have an effect on synchronization.
@ulope mentioned thoughts about knowing which room to use and that we had some troubles about that in the past.

I opt for solution one but this must be coordinated with the LC to be compatible in the future.

**Comment by andrevmatos** [comment]
I don't think performance of creating a new room with included `invite` is slower than simply inviting the other user. Also the issues about choosing the room to talk on is an algorithm issue from us, nothing inherent from Matrix itself.

That said, I also vote for solution 1, since this decouples us a little bit from matrix protocol itself (like the mentioned restrictions for native voip signaling), and we don't expect the Raiden client to ever need to accept a videocall from a Riot client anyway. I'd just like to push for reusing the `m.call.*` names for the `msgtype`, in order to make it more explicit to the mind the corresponding mapping.

Also, switching to signaling using `m.room.message` events (even if they replicate the current `m.call.*` events) allows us switching to **ToDevice** API, which ditches completely the need for rooms/invites roundtrips and statekeeping, and also are lighter for servers since they don't keep history on these (native `m.call.*` events aren't forwarded by Synapse, as of my tests, but messages are).
I already have a working prototype of ToDevice messages, signaled using specific Capability, and it works fine, and speed up transfers by making one-time messaging faster, like SecretRequest/Reveal.
