### ISSUE TITLE
bf6: slow SecretRequest message

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6600]
In this run of bf6, the payment with the secret has `0x030b3c6ba2663591e7c4f899e017f87dcfc1b842cc3ff592f6178959aa3e16c3` stalled for 24 minutes because a SecretRequest took a long time between sending and being processes:

```json
{"timestamp":"2020-10-09 11:04:57.631436","node":"0xDe6E76A41eaBC3Bf0a5F2EE4823EcB74e8C4E9ec","re":"raiden.transfer.mediated_transfer.events.SendSecretRequest"}
{"timestamp":"2020-10-09 11:28:44.128089","node":"0xd1Cf051542ef2cC9E94dF005713d1e9D2aA95DfA","sc":"raiden.transfer.mediated_transfer.state_change.ReceiveSecretRequest"}
```

This is run with raiden at revision 922e4fdf0.

Logs and dbs: https://drive.google.com/file/d/1XXev3xiZa0D1-JDj58w0Yy01iIGPBBgk/view?usp=sharing

**Comment by fredo** [comment]
After analysing the logs I came to the following findings: 

Running BF6 sometimes leads to either 

- Payments taking a long time ~14 minutes
- or timeout after 24 minutes

## Cause

This actually is related to a broken state of web rtc channels which stays undetected by the clients. While the `readyState` is still `open` messages do not get through to the other participant. The logs show that the sending node calls `channel.send()` but the receiving node does not receive the message.
Unfortunately, the state is inconsistent that it **sometimes** still receives messages or messages take a long time to be send. I.e. the node sends a particular message **15 times** due to the retry queue, the message is received by the target **only once** and at arbitrary run time. I assume that it is a retried message which does go through at one point.

Since `channel.send()` is not an awaitable function, I assume that it writes the message to some buffer which is supposed to be picked up by a different process at one point. Somehow this seems to work unreliably. 
@andrevmatos have you ever tried a high throughput test with the light client? If so, have you experienced the same behavior?

**Comment by konradkonrad** [comment]
IIRC @fredo found that the problem is related to https://github.com/raiden-network/raiden/pull/6606 but that was not the complete fix. The calls to `peer_connection.close()` need to be guarded by a lock (or similar), to make sure that no previous `close()` interrupts a newer connection.
