### ISSUE TITLE
Inconsistent reveal timeout limits

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6645]
There are inconsistencies in the handling of the reveal timeout parameters in the CLI and API.

In the CLI there is a minimal value of 20 required. In the API I can open a channel without the limit being checked.

**Comment by ezdac** [comment]
I don't necessarily see this as a bug - the CLI/config parameter concerns the `default_reveal_timeout`, that 
will only be applied if no explicit reveal timeout is given.
Since the start of the Raiden CLI will expose an API instance with this config, the behaviour is according to the CLI parameter.

When the "default" reveal timeout is meant as a minimum value, this is different - but then it should also be checked in the inner layers of Raiden and should probably be renamed.

**Comment by ezdac** [comment]
Plan to action:
- In general, we would like to have a minimum reveal timeout (global constant), that can't be undermined anywhere in the public APIs and should be checked in the innermost public API layer - errors due to this should bubble up to the outermost API layer
- the above default timeout setting should be checked to comply to this in the outermost API layer (CLI params) as it is now.
