### ISSUE TITLE
Mint Tokens endpoint doesn't return Tx Hash

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden#6649]
## Issue checklist

To help us more easily debug your issue please check the boxes for which requirements for safe usage or Raiden were followed:

- [ x ] The Ethereum node was always up to date with the chain tip and never stopped running.
- [ x ] No Ethereum transaction was sent for the account that Raiden manages by another app.
- [ x ] The Ethereum account used by Raiden always had sufficient ETH.
- [  ] The Raiden DB that exists by default at ~/.raiden was never altered or deleted. [Custom raiden dir specified]
- [ x ] The Raiden node was never restarted. If yes please provide more info.
- [ x ] The ethereum node was not switched while Raiden was running.
- [ x ] The Raiden REST API is protected from public access.

## Problem Definition

Minting endpoint doesn't return Tx hash as docs suggest.
https://raiden-network.readthedocs.io/en/latest/rest_api.html?highlight=mint%20token#post--api-(version)-_testing-tokens-(token_address)-mint

Already discussed with @karlb

**Comment by ezdac** [comment]
The problem is that the methods of the Blockchain-Proxy objects don't return anything (in general):
https://github.com/raiden-network/raiden/blob/29cb8c09607343e949e54afcc72308c25a57ce16/raiden/network/proxies/custom_token.py#L45-L46

Additionally, the (not-existing) internal return value is not trickled up to the REST endpoint:
https://github.com/raiden-network/raiden/blob/29cb8c09607343e949e54afcc72308c25a57ce16/raiden/api/rest.py#L618-L619

@karlb So this is an easy fix, but as an architectural concern, we should ask ourselves wether the interface of `mint_for` should deviate from other proxies that involve Ethereum transactions by returning the TxHash on a successful Tx, or wether we should return the `TransactionMined.transaction_hash` for all Proxy methods?

**Comment by karlb** [comment]
Returning the tx_hash seems the obvious thing the do when creating transactions. I'm in favor of doing that for all functions, but start with this one to see how it works out before touching all of them.

**Comment by ezdac** [comment]
Follow up issue: #6688
