### ISSUE TITLE
Backwards incompatibility: "network-id" can no longer be configured via config file

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden#6690]
## Problem Definition

#6564 internally renamed `network-id` to `chain-id`. 
The problem is that in click the "internal name" (e.g. the one without leading dashes if one exists) is the 'canonical' name of the option.
The config file uses the canonical name, therefore `network-id` is no longer usable there since it got renamed to `chain-id`.

This is a backwards incompatible change.

## Possible solutions

- Do nothing and accept the breaking change
- Implement a way to rename options and warn users about that fact
- Rename the internal option and "fix" it after the config file has been applied (meh, pretty hacky)

**Comment by ezdac** [comment]
Wouldn't it overall be better to just parse the config file before the CLI-option parsing?
Like this the config options naturally act as defaults that can be overwritten by CLI-options.
I haven't completely looked into the feasibility, but in `click` a `default_map` arg  can be passed to the [context ](https://click.palletsprojects.com/en/7.x/api/#context)

Also see for reference: https://github.com/click-contrib/click-configfile

**Comment by ulope** [comment]
The problem with parsing the config file earlier is that the location itself is changeable via options (either implicitly through `--datadir` or explicitly through `--config-file`).
The click-configfile project seems to be pretty unmaintained (last commit is 3+ years ago)

But yes, in general a more unified way of handling config / cli would be nice.

**Comment by ezdac** [comment]
As it turns out, this seems to be a pretty easy fix:

injecting the config file parsing logic into the  `GroupableOptionCommandGroup.invoke()` method: https://github.com/raiden-network/raiden/blob/670367c2b719e450114d6e99f1d0aef06ff8dff3/raiden/utils/cli.py#L191

Here the context can be accessed (I tested the interplay with `datadir` and the overwrite of `--config-file` from CLI), 
so that the correct path is accessible as `ctx.params["config_file"]`.

(For reference: 
Now we still need a solution for the above issue, since we are working with the "internal representations" but this makes things a bit easier.
