### ISSUE TITLE
Check minimal transfer expiration

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden#6704]
In https://github.com/raiden-network/team/issues/894 we agreed to the minimal allowed value for transfer expiration that should be accepted by the client.

It needs to be checked that
- the client accepts transfers with the minimal and great expiration
- the client rejects transfers with lower expiration that the minimal value

The default expiration should stay the same

**Comment by ezdac** [comment]
As of this https://github.com/raiden-network/light-client/issues/2409#issuecomment-741810176 and https://github.com/raiden-network/light-client/pull/2436/commits/2496d07715bb72160d0b32e9f656a23f8f0abefc it looks like this is no problem anymore, @palango can you verify this?

**Comment by ezdac** [comment]
So as mentioned above, the LC seems to have mirrored the behaviour of the Py-Client, in that it mediates payements as 
long as `reveal_timeout < lock_expiration <= settle_timeout ` (with additional confirmation margins).

I am still not sure wether we should make our acceptance criteria for forwarding payments more strict, like `reveal_timeout + x < lock_expiration <= ..` ? Theoretically, the reveal_timeout can be custom, so this can implicitly be done by setting a higher individual reveal_timeout by the node. See also this discussion: https://github.com/raiden-network/raiden/issues/6737

**Comment by andrevmatos** [comment]
If we consider how fast WebRTC transfers are, it makes sense to allow receiving/mediating transfers on the strictiest margin (i.e. `currentBlock < (dangerZone = expiration - revealTimeout`), which is what currently the LC and PC clients allows. We've implemented a small margin for off-chain payment of 10% (default=5 blocks) before danger zone, while PC uses twice revealTimeout, but both should be compatible and implementation-specific, as long as the protocol acceptance criteria is the same (`<`).

About the custom revealTimeouts along a path, the correct solution is for the PFS to return the maximum revealTimeout on each given route, and the client should use it for calculation above. IIANM, currently, the PFS already holds this information, but uses only to validate a route as **viable iff** no maximum revealTimeout is larger than the minimum settleTimeout on alongside that route (and discard the route if not, because there wouldn't be an `expiration` which would be acceptable by all nodes in the route). So, it's just a matter of including this `max(revealTimeout)` (and maybe also `min(settleTimeout)` for self-validation) on the PFS response payload.

**Comment by ezdac** [comment]
> the PFS already holds this information, but uses only to validate a route as viable iff no maximum revealTimeout is larger than the minimum settleTimeout (minus some margin?) alongside that route, and discard the route if not, because there wouldn't be an expiration which would be acceptable by all nodes in the route.

Unfortunately, this does not seem to be the case. As noted in #6737, the only thing the [PFS seems to be doing](https://github.com/raiden-network/raiden-services/blob/d724adfc7896f55e2d1d9d00b0dbd501b85eabe1/src/pathfinding_service/model/token_network.py#L171-L181)  is to check for each edge in a path, wether the condition `settle/reveal >= 2` is true. This only takes into account local timeouts, and does not compare timeouts across paths

**Comment by ezdac** [comment]
I will close this, as the PC is compatible with the LC as of the issue description. 
Just to summarise the findings of what happens in the PC:

As @andrevmatos described, the PC only checks for `currentBlock < (dangerZone = expiration - revealTimeout)` **on mediated transfer acceptance** (as the role of the mediator as well as target):
https://github.com/raiden-network/raiden/blob/3e466b852d31d0e1807e3184ecf5cc7e31d4e867/raiden/transfer/mediated_transfer/mediator.py#L111-L115

While the check **on transfer initiation** is more strict and mirrors what the PFS checks for each edge in a possible route:

https://github.com/raiden-network/raiden/blob/f544ceb2a86a98872cb034fe6d626f454293669a/raiden/transfer/channel.py#L250-L262

Regarding unsynchronized reveal_timeouts between partners and the lack of global reveal_timeout consideration for the PFS, there still is #6737 for discussion.
