### ISSUE TITLE
Forbid two Raiden instances to run with the same database

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#671]
## Problem Definition

Prevent two instances from running at the same time with the same database.

## Solution

Use a file lock under the data directory to prevent this from happening

## Tasklist

- [ ] On startup create a lock file, if the creation fails abort the process and inform the user (he may need to manually delete the fie if the system had a hard crash)

**Comment by metabench** [comment]
How about checking if any other Raiden instance processes are running, and if there is no other process found, it presents the user with the option of deleting the lock file? How about checking the lock file to see if it's not been accessed since the system started up?

I mention these things as they would improve usability by eliminating a step that the user would need to take. Code bloat would be one disadvantage - but would the improved usability, be enough to pay attention to removing a possibly unnecessary step. Needing to manually delete a file after a hard crash would prevent the Raiden instance from starting automatically upon reboot.

**Comment by LefterisJP** [comment]
Adding code to detect other running raiden processes may be an overkill and hard to do for different kind of Operating systems.

But if at Raiden's startup we detect the lockfile's existence we can then indeed ask the user to make sure if there is no other raiden instance running or ask him if the system just recovered from a crash. If the first is the case then we quit and ask the user to only have one instance of raiden running. If the latter is the case then raiden can automatically delete and reacquire the lock.

**Comment by pcppcp** [comment]
Fixed in PR #838
