### ISSUE TITLE
Increased presence problems?

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6724]
We have a high number of scenario failures that could be explained by matrix presence problems.

- [ ] Verify that these problems are caused by presence issues
- [ ] Find an explanation why the failure rate has increased

2020-12-07 afternoon
```
:sad_panda: [sp1, raiden] Scenario pfs4_use_best_path Failed 0:15:18
scenario_player.exceptions.ScenarioAssertionError: Value mismatch for “balance”. Should: “999000000000000000” Is: “1000000000000000000” Channel: {‘token_address’: ‘0x59105441977ecD9d805A4f5b060E34676F50F806’, ‘balance’: ‘1000000000000000000’,            ‘token_network_address’: ‘0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3’, ‘total_deposit’: ‘1000000000000000000’, ‘partner_address’: ‘0x12083A4022918dF662b3eb12aEfe66DF9BE158Dd’, ‘total_withdraw’: ‘0’, ‘settle_timeout’: ‘500’, ‘reveal_timeout’: ‘50’,       ‘state’: ‘opened’, ‘channel_identifier’: ‘16059’, ‘network_state’: ‘reachable’}

:sad_panda: [sp2, raiden] Scenario bf6_stress_hub_node Failed 0:16:23
 HTTP status code “409” while fetching http://127.0.0.1:41103/~AB983622C43Aaf. Expected 200: {“errors”: “Payment couldn’t be completed because: PFS: Target does not    
have a channel with sufficient capacity ([0] < 1000000000000000). Approximate block at the time of the request 3885140 (PFS error code: 2201)”} 

:sad_panda: [sp1, raiden] Scenario bf1_basic_functionality Failed 2:00:14
scenario_player.exceptions.ScenarioAssertionError: Expected sum value “2090000000000000000” for channel fields “balance”. Actual value: “2088000000000000000”. Channels: [{‘state’: ‘opened’, ‘token_address’: ‘0x59105441977ecD9d805A4f5b060E34676F50F806’,  ‘reveal_timeout’: ‘20’, ‘partner_address’: ‘0x830B8840AB9605D0A086031380D4F4E3aedE75d3’, ‘settle_timeout’: ‘40’, ‘balance’: ‘1008000000000000000’, ‘total_withdraw’: ‘0’, ‘token_network_address’: ‘0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3’,              ‘channel_identifier’: ‘15998’, ‘total_deposit’: ‘1000000000000000000’, ‘network_state’: ‘reachable’}, {‘state’: ‘opened’, ‘token_address’: ‘0x59105441977ecD9d805A4f5b060E34676F50F806’, ‘reveal_timeout’: ‘20’, ‘partner_address’:                           ‘0xA532d6D7927078579136da663Ce3048f14838b8c’, ‘settle_timeout’: ‘40’, ‘balance’: ‘1080000000000000000’, ‘total_withdraw’: ‘0’, ‘token_network_address’: ‘0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3’, ‘channel_identifier’: ‘15999’, ‘total_deposit’:         ‘1000000000000000000’, ‘network_state’: ‘reachable’}]
```

nightly run starting on 2020-12-07
```
 :sad_panda: [sp2, raiden] Scenario mfee4_combined_fees Failed 0:10:20
 HTTP status code “409” while fetching http://127.0.0.1:41601/~5F1e3d943cE6A2. Expected 200: {“errors”: “Payment couldn’t be completed because: PFS: No route between   
nodes found. (PFS error code: 2201)”}

 :sad_panda: [sp2, raiden] Scenario bf7_long_path Failed 0:10:20
HTTP status code “409” while fetching http://127.0.0.1:39879/~29Bc8B15D45506. Expected 200: {“errors”: “Payment couldn’t be completed because: there is no route        
available”} 

 :sad_panda: [sp2, raiden] Scenario bf6_stress_hub_node Failed 0:32:38
scenario_player.exceptions.ScenarioAssertionError: Value mismatch for “balance”. Should: “502000000000000000” Is: “497000000000000000” Channel: {‘token_network_address’: ‘0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3’, ‘balance’: ‘497000000000000000’,      ‘reveal_timeout’: ‘50’, ‘token_address’: ‘0x59105441977ecD9d805A4f5b060E34676F50F806’, ‘total_withdraw’: ‘0’, ‘total_deposit’: ‘0’, ‘state’: ‘opened’, ‘channel_identifier’: ‘16130’, ‘partner_address’: ‘0x6F4c224Ab1227dF7881b92769CBec2D83887A951’,        ‘settle_timeout’: ‘500’, ‘network_state’: ‘reachable’}

 :sad_panda: [sp1, raiden] Scenario bf1_basic_functionality Failed 2:03:52
scenario_player.exceptions.ScenarioAssertionError: Expected sum value “2090000000000000000” for channel fields “balance”. Actual value: “2088000000000000000”. Channels: [{‘total_withdraw’: ‘0’, ‘partner_address’:                                          ‘0x9EC430821f6D31D2565a1f17007F4dE1b0F71C29’, ‘total_deposit’: ‘1000000000000000000’, ‘balance’: ‘1009000000000000000’, ‘state’: ‘opened’, ‘reveal_timeout’: ‘20’, ‘channel_identifier’: ‘16107’, ‘settle_timeout’: ‘40’, ‘token_network_address’:            ‘0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3’, ‘token_address’: ‘0x59105441977ecD9d805A4f5b060E34676F50F806’, ‘network_state’: ‘reachable’}, {‘total_withdraw’: ‘0’, ‘partner_address’: ‘0xD3f40f841F3dE206d5b1581ec16f7C5d10803989’, ‘total_deposit’:         ‘1000000000000000000’, ‘balance’: ‘1079000000000000000’, ‘state’: ‘opened’, ‘reveal_timeout’: ‘20’, ‘channel_identifier’: ‘16108’, ‘settle_timeout’: ‘40’, ‘token_network_address’: ‘0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3’, ‘token_address’:            ‘0x59105441977ecD9d805A4f5b060E34676F50F806’, ‘network_state’: ‘reachable’}]
```

**Comment by andrevmatos** [comment]
Ok, I may have found a reliable and backwards compatible workaround!
- From what we know, the presence bug seem to manifest on some high-load scenarios when several nodes suddenly join different servers on the network, open channels with each other and do some requests (usually room creation/invite/join) on a short timespan
- When this happens, the presence view of an user from a server different than their own gets stuck at offline and doesn't get updated even upon following `/sync` calls (which is usually responsible for keeping their status as `online`)
- However, while fixing another issue (`avatar_url`/Capabilities updates weren't propagated either), I discovered an **explicit**  [`PUT /presence/$userId/status`](https://matrix.org/docs/spec/client_server/latest#put-matrix-client-r0-presence-userid-status) (`matrix.setPresence` in our lib) **does force** the presence to be propagated again to peers and federated servers!
  - Notice the new status must be different than the previous, or else it gets deduplicated, but a simple `{ presence: 'online', status_msg: Date.now().toString() }` was enough to get it through every time
- This API can be quite heavy, since it triggers all `/sync` requests on listening nodes and syncing servers to complete with the new event, so it's essential to not spam it and instead call it on key times
  - Currently, we're doing this on `channelOpen` and `channelDeposit` confirmation events, since these must presumably happen before transfers are attempted on scenarios, but I confess this implementation is a little bit SP-centric
  - We could come up with an optional (i.e. backwards-compatible) message where partners could tell us we look offline from their perspective, and we could then reload our presence as per above, but this would only work if the client has partners on other servers. Maybe PFS could be a little proactive on this notification as well, upon detecting updates from offline peers.

We conducted a complete SP run with `toDevice` capability **turned off**, which usually was enough to trigger the presence bug in the federation, and it worked fine. We're still working on our final implementation of it, but the WIP can be seen in https://github.com/raiden-network/light-client/pull/2453

**Comment by andrevmatos** [comment]
https://github.com/raiden-network/light-client/pull/2453#issuecomment-747753175 :
> Ok, checking the logs from BF4 and BF6 and running BF4 locally, I could confirm the BF4 failure was NOT caused by the presence issue, which seems to be fixed by the approach on this PR ()!!!
> 
> The error on BF4 was caused by a race where both LCs would create and invite the other to rooms, and then keep switching between them and not being able to get the message through.
> 
> The fix is included on this PR, and is taking the same approach as the PC and the one we use for caller/callee choice on our WebRTC: only one of the nodes in a pair (the lower address, when sorting lexically) is responsible for creating the room.
> 
> With this, ALL our supported scenarios (all but mfee) are **green**  even with `toDevice` disabled, which was shown to definitely trigger the presence bug before!

**Comment by GataKamsky** [comment]
Very good find André. @ulope and @fredo can look into this when they are back next week.

**Comment by fredo** [comment]
In the past two weeks, @andrevmatos , @ulope and @fredo worked on improving @andrevmatos proposed solution to workaround the presence bug. 
Furthermore, I like to present another workaround which removes the affect of the presence bug on the PFSes (it is not viable for raiden nodes), which is easy to implement and currently is deployed on the test transport servers for testing.

## PFS syncing presence from respective homeservers
This is a relatively easy implementation to make the PFS completely free of wrong behavior caused by the `presence bug`. As described above, the presence bug explicitly occures in the propagation process of the federation. Thus, it can be assumed that a homeserver always keeps the correct state of its own users' presences. As a PFS is also a simple user connected to its homeserver, it can only guarantuee that presences of users from the same server are legit. 
As the number of PFSes, and homeservers in our federation is limited to a reasonable number (lets say <100), every PFS can simply connect to every homeserver and start syncing on presences.
In order to not receive duplicates, the PFS will filter presences for users from the homeserver on which the sync responded. The image below describes the change:


![](https://i.imgur.com/XvXmh6E.jpg)

![](https://i.imgur.com/4EN6273.jpg)



### Thoughts and implementation details
With this change it can be assumed that the PFS always has the correct state of presences of the whole network. It must be said that this might not be sufficient in the current state as raiden nodes also need to know about the correct presence of their neighbours, targets and initiators. 
But at least for finding routes, this change should completely remove trouble caused by the presence bug.

#### Implementation Details
It is important that the PFS should not crash if it is not possible to connect to another server. This is due to the fact that the PFS should work even if one transport server is offline. The new feature is rather building on top using it as an additional layer of security. If it cannot connect to another transport server for whatever reason or is not able to sync, it will automatically fall back to the old mechanism and fetch presences by the main client.

Therefore, the transport clients are separated in a `main_client` (the one it used to connect to) and `other_clients` as they behave differently.

- main client
    -  process presences of all clients which are not in `other_clients`
    -  fetch and process messages in the broadcasting room (capacity updates, etc.)
- other client
    - only process presences of users of its own homeserver

Unfortunately, it is not possible to filter presences with a regex therefore, filtering must be done client-side.

**Comment by fredo** [comment]
I also provided a document with a summary of the work of the last two weeks which will be shared with all team members

**Comment by karlb** [comment]
The workarounds work as expected, now. So at least we have an understanding of what works and what doesn't. We still have to find out with which combinations of workarounds we feel confident enough to release.
