### ISSUE TITLE
Test code path for monitoring balance check

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6736]
The following code path is tested neither in our integration tests nor in our SP testnet runs:
https://github.com/raiden-network/raiden/blob/develop/raiden/services.py#L111-L152

This can cause failures during mainnet release testing, which should be avoided. Make sure this is tested regularly. Probably an integration test would make sense.

**Comment by ezdac** [comment]
There is a test https://github.com/raiden-network/raiden/blob/d03aa0d0adcd1e43d6cb817ab0ef823a21c83ccb/raiden/tests/integration/network/transport/test_matrix_transport.py#L632 but it is heavily mocked, and due to the mocking it only tests the initial condition for the `DAI` token.

Can you specify what failures occur? Do you think it is sufficient to modify above test so that both conditions will be checked?
If we want to go for tests with less mocking, would it even make sense to test `environment_type=Environment.PRODUCTION` in local integration tests or wouldn't the SP be the best place to test that?

**Comment by karlb** [comment]
The MS1 scenario failed because no monitor request got sent due to that check.

The channel balance looks wrong to me. I would expect
```
        channel_balance = get_balance(
            sender=channel_state.partner_state,
            receiver=channel_state.our_state,
        )
```
but I didn't verify that, yet.
