### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#69]
some items need persistence in case of a process exit, i.e.: 
- [ ] secrets
- [ ] merkle tree of pending transfers
- [ ] peers / reputation
- [ ] channels
- [ ] net balance of channels
- [ ] local ledger of transfers

**Comment by heikoheiko** [comment]
see also #1

**Comment by hackaugusto** [comment]
Persistence alone is not sufficient, we also need to make the tasks restartable or change the architecture to drop the use of tasks and their state in favor of events and state saved in the persistence layer.

**Comment by LefterisJP** [comment]
As set out in https://github.com/raiden-network/raiden/issues/205 in order to have recoverable (also from sudden power failure e.t.c.) persistence we need to do a bit more work.

But for restartable persistence (i.e.: restart after a proper shutdown), we are going to be able to achieve this with the developer preview milestone (https://github.com/raiden-network/raiden/issues/593)

**Comment by hackaugusto** [comment]
Closing in favor of #298
