### ISSUE TITLE
Coordindate update of demo env after geth 1.10 fix release

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6964]
Since the latest release does not support geth 1.10 (and thus infura), the demo env can only be used with openethereum. This make the demo env much less useful. When a Raiden release that includes the geth 1.10 fix has been made, we should update the demo env soon.
Since the demo env is used by external parties, this should be coordinated with @eorituz .

**Comment by eorituz** [comment]
@karlb Thank you for reaching out! 
I don't see a way around deprecating the old demoenv and deploy a new one....

**Comment by ezdac** [comment]
What version should the demo-env update be based on?
- `v2.0.0` - including significant, compatibility breaking transport changes:
  - Since we would want to migrate to 2.0.0 at some point anyways, it probably makes sense to simply use this for the demo-env,  to keep the number of upgrades low.
  - breaking compatibility is not the issue, since we have to coordinate client updates anyways
  
- a new version `v1.2.1` - including the Geth 1.10 fix:
  - the demo-env is supposed to be very stable, and we don't know the characteristics of the v2.0.0 in real-life scenarios
  - we might not need to upgrade the RSB with this solution

Related: #666

**Comment by ezdac** [comment]
After a preliminary discussion, we want to update directly to `2.0.0a1`.
Therefore we have to wait for a stable RSB release and also upgrade the RSB for the demo-env as well.

**Comment by fredo** [comment]
Demo env RSB is updated as well as an dockerimage  to run on the demo environment. It supports Raiden v2.0.0
