### ISSUE TITLE
Flaky test_matrix_transport_handles_metadata

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden#6976]
The test test_matrix_transport_handles_metadata is flaky:
https://app.circleci.com/pipelines/github/raiden-network/raiden/11383/workflows/4ef051e1-e0b8-4682-855e-0dcc80bca21c/jobs/177791

Is the a problem with the test, or is it really a bug?

**Comment by ezdac** [comment]
I wrote this test - I can look into it

**Comment by ezdac** [comment]
Fixed in #6985 - the test was not considering `Delivered` messages from an additional transport.
A lower message count than actually present was used to wait for incoming messages. The non-deterministic order of messages made this flaky in the following message-identifier check.

An additional remark: 
We are sending out messages in the transport, even if the `address_metadata.user_id` could not possibly correspond to the `queue_identifier.recipient` (more specifically a mismatched address-part of the user-id).
We could avoid this by introducing a check e.g. here:

https://github.com/raiden-network/raiden/blob/5f634a0c0e1c5d7553a70c6c913f45a8257a1a75/raiden/network/transport/matrix/transport.py#L242-L248
