### ISSUE TITLE
refactor out logic duplication

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden#70]
[`messages.py`](https://github.com/raiden-network/raiden/blob/master/raiden/messages.py) and [`encoding/messages.py`](https://github.com/raiden-network/raiden/blob/master/raiden/encoding/messages.py) share some logic - this should be refactored.

**Comment by hackaugusto** [comment]
Notes:
- `structs` was considered first, it wasnt used because the formatting strings were getting too large and easy to err.
- the `namedbuffer` implementation turned out too complex and not flexible enough, we need a binary parsing library that supports repetition
- dropping the logic in the messages and using classes as PODs or just plain dict is probably a good idea

**Comment by konradkonrad** [comment]
I don't believe this is still an issue.
