### ISSUE TITLE
Drop invalid Metadata before sending the message

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden#7049]
In case of direct transfers we have the following issue: 

If Metadata are invalid they should get dropped. They are going to be dropped but after the LockedTransferMessage is being sent away. This leads to the fact that the Locked Transfer will be sent to a non validated user id. 

This should not happen in the first place. Metadata need to be dropped before a Locked Transfer is passed to the transport. 
Secondly, It lead to a confusing error message because the missing metadata caused the secret reveal to fail as metadata were dropped already.

Fixing the order of dropping and creating the locked transfer should do the trick.

**Comment by ulope** [comment]
@ezdac @istankovic and I had a call about this.

We agreed on the following:
- The `RouteState` dataclass will validate the metadate on instantiation
  - This will cover both the Initiator as well as the Mediator cases
- If any of the address metadata in a route are found to be invalid (i.e. signature check fails or no signature) that entire route is dropped (exact implementation TBD)
- Empty / missing metadata are not considered a failure at this point 
  - Due to refunds which currently don't have the metadata available at the point where the `RouteState` is constructed
  - Once we drop refunds the check could be tightened to also consider missing metadata as invalid
 
Additionally the PFS should never hand out Routes or address metadata that are invalid. Needs discussion.

**Comment by fredo** [comment]
I'm not so sure if I would agree with dropping missing or invalid metadata. As we currently store Matrix related information in the metadata, a payment could still succeed if the raiden nodes use a different transport other than matrix. This could be i.e. WebRTC. If we prohibit payments with missing or invalid metadata, we also cancel transfers which would actually succeed. IMHO the transport layer should decide whether to use the metadata or not. In our case, that would be invalid metadata should not be used for matrix transfers, but they dont matter for web rtc communication. 

As a consequence, we could discuss if the PFS should make validations on metadata. It might avoid routes with invalid metadata but then it also prevents the problem above. I would see the PFS as a pure forwarder of information and validating this data must be done by the respective raiden clients anyway.

**Comment by ezdac** [comment]
I agree that supporting different transports and not getting too Matrix-centric is a fair point to make.

Some notes:
- Communication of failing transfer is harder in this scenario and would involve Lock-timeouts being the main cause for failures: We wouldn't fail when the initial locked-transfer hit the "Cannot send raw message without address metadata" the first time and the message will be stuck in the retry queue until the lock times out.
If we would already verify e.g. on querying the PFS and see that we possibly can't send out messages to the relevant nodes, we can fail the payment before even entering the state-machine. 

- If we explicitly want to allow invalid metadata to pass to the node's transport, we should also consider reverting the validation of the `messages.metadata.RouteMetadata`, since this is dropping invalid entries upon passing on metadata to the next hop - the validation then should only be done inside the `_send_raw`, after the WebRTC "switch".

- Smaller inconvenience: Handling validation in the transport would involve more introspection in the content of the address-metadata during batching of messages, since we need to explicitly  consider the displayname during batching - there could be a valid signature "overruled" by invalid signatures in a batch. It's still an edgecase, so maybe this it not necessary, but a node could potentially poison the batching in other nodes for a specific address.

**Comment by ulope** [comment]
After further more discussion we agreed to implement it as is for now.

Conceptually this validation should happen in the transport layer. 
Also the address metadata may contain arbitrary other information in the future.

If and when this happens the current solution needs to be re-evaluated.
