### ISSUE TITLE
Define penalization scheme

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden#86]
Define how malicious participants should be penalized.

**Comment by heikoheiko** [comment]
do we need penalization if we can resolve every dispute?

**Comment by czepluch** [comment]
I guess not, but maybe it could prevent people from trying to be malicious. Nonetheless this is not a necessity and the MVP can do without.

**Comment by hackaugusto** [comment]
We need to pay for disputes resolved by third parties

**Comment by hackaugusto** [comment]
Penalization is implicit in the transferred amount, since each party can only provide the proof of how much token it received and by lying it may only provide a lower value.

Incentives to third parties may be discussed on different issues:

Allow third parties to withdraw locks #541
Allow third parties to update the counterparty transfer #293
Allow third parties to close the channel #182
